### ISSUE TITLE
Only tvOS Pre-Compiled Framework is Available via Github Release and Carthage

### ISSUE THREAD

**Issue by csaper** [mixpanel/mixpanel-iphone#1003]
Hi there @zihejia, @jaredmixpanel  & team -

It appears that only the pre-compiled MixPanel framework for tvOS is available for the latest Release on Github ([download link](https://github.com/mixpanel/mixpanel-iphone/releases/download/v5.0.0/Mixpanel.framework.zip)).

![Pre-Compiled Framework for tvOS Only](https://user-images.githubusercontent.com/316563/200034321-01c3a90b-6c89-4476-8dcc-82808c0b3b05.png)

<hr/>

When attempting to alternately build via Carthage, even when specifying a non-tvOS platform via command line argument (i.e. `carthage build --no-skip-current --cache-builds --platform iOS`), only the tvOS framework appears to be built and archived.

Any way to get an iOS-only .xcframework of Mixpanel v5.0.0?

Thanks!

**Comment by jaredmixpanel** [comment]
@csaper This is fixed in v5.0.1. The Carthage builds attached to the Releases are fixed (and changed to XCFrameworks). You should be able to build an iOS-only XCFramework with `carthage build --platform ios --use-xcframeworks --no-skip-current`

**Comment by csaper** [comment]
Thanks very much @jaredmixpanel!
