### ISSUE TITLE
How to dynamically enable/disable the sdk?

### ISSUE THREAD

**Issue by RNG-Tank** [mixpanel/mixpanel-iphone#1015]
Hi guys, we are using iOS and Android SDK, and we hope to dynamically enable or disable the SDK when the app is running. 
Is there any API? 
If not, are there any plans for support it in the future?

**Comment by jaredmixpanel** [comment]
@RNG-Tank you could use the `optInTracking` and `optOutTracking` methods or create your own wrapper class to add an `enabled` check before calling the actual SDK methods. There are no plans to add such functionality.
