### ISSUE TITLE
v5.0.5 not have PrivacyInfo.xcprivacy

### ISSUE THREAD

**Issue by maningLaien** [mixpanel/mixpanel-iphone#1023]
Mixpanel.xcframework.zip not have PrivacyInfo.xcprivacy, There is also no PrivacyInfo.xcprivacy file after Cocoapods is pulled.

**Comment by rnwellman** [comment]
PrivacyInfo.xcprivacy has to be added to the "Copy Bundle Resources" build phase for all the targets.

**Comment by jaredmixpanel** [comment]
`v5.0.6` is released with the `PrivacyInfo.xcprivacy` added as a `resource` in the `.podspec`, `Package.swift` and `Copy Bundle Resources` build phase for all targets. Also, bumped the min iOS target down to `11.0`: https://github.com/mixpanel/mixpanel-iphone/pull/1024

**Comment by gsantiago** [comment]
@jaredmixpanel do you guys have plans to update the react native version? There is this [issue](https://github.com/mixpanel/mixpanel-react-native/issues/227) open there, but without any response from mixpanel

**Comment by willianlemes** [comment]
Guys, when will you update the react native version?
