### ISSUE TITLE
Binary Rejected - [ASIdentifierManager advertisingIdentifier]

### ISSUE THREAD

**Issue by neoneye** [mixpanel/mixpanel-iphone#109]
I had [my app](https://itunes.apple.com/us/app/triangle-draw/id733036480?mt=8) in review and it got rejected. My app doesn't show any ads. I have tried to remove the `AdSupport.framework`, but MixPanel depends on it.

Below is the detailed text I got from Apple describing the problem

---

PLA 3.3.12

We found your app uses the iOS Advertising Identifier but does not include ad functionality. This does not comply with the terms of the [iOS Developer Program License Agreement](http://developer.apple.com/membercenter/index.action#agreements), as required by the [App Store Review Guidelines](https://developer.apple.com/appstore/resources/approval/guidelines.html#terms-conditions).

Specifically, section 3.3.12 of the iOS Developer Program License Agreement states:

"You and Your Applications (and any third party with whom you have contracted to serve advertising) may use the Advertising Identifier, and any information obtained through the use of the Advertising Identifier, only for the purpose of serving advertising. If a user resets the Advertising Identifier, then You agree not to combine, correlate, link or otherwise associate, either directly or indirectly, the prior Advertising Identifier and any derived information with the reset Advertising Identifier."

Please check your code - including any third-party libraries - to remove any instances of:

class: **ASIdentifierManager**
selector: **advertisingIdentifier**
framework: **AdSupport.framework**

If you are planning to incorporate ads in a future version, please remove the Advertising Identifier from your app until you have included ad functionality.

To help locate the Advertising Identifier, use the “nm” tool. For information on the “nm” tool, open a terminal window and enter, “man nm.” 

If you do not have access to the libraries source, you may be able to search the compiled binary using the "strings" or "otool" command line tools. The "strings" tool lists the methods that the library calls, and "otool -ov" will list the Objective-C class structures and their defined methods. These techniques can help you narrow down where the problematic code resides.

**Comment by lemonkey** [comment]
Still a problem if you're using CocoaPods unless you manually update your Pods-Mixpanel target build settings to add the preprocessor macro MIXPANEL_NO_IFA=1.

**Comment by drmarshall** [comment]
If you remove AdSupport framework (assuming you're not using it and it was erroroneously included) does it pass Apple's pre-submission test with the preprocessor flag?

Marshall
—
Manager, Support
Mixpanel




On Sat, Jan 10, 2015 at 1:29 PM -0800, "Ari Braginsky" <notifications@github.com> wrote:












Still a problem if you're using CocoaPods unless you manually update your Pods-Mixpanel target build settings to add the preprocessor macro MIXPANEL_NO_IFA=1.

**Comment by lemonkey** [comment]
I'm not using the AdSupport framework anywhere in the project, and Apple did mention in the rejection notice:

> Note: iAd does not use the AdSupport framework, ASIdentifierManager, or the Advertising Identifier. Therefore they are not required for iAd implementations and should not be included in your app for iAd support.

**Comment by lemonkey** [comment]
Was there any traction on a pod spec that allows you to specify that you want to disable IFA?  See

> neoneye commented on Feb 1, 2014 
> Perhaps make a cocoapod subspec where MIXPANEL_NO_IFA is defined
> s.subspec 'NOIFA' do |subspec|
>    subspec.prefix_header_contents = #define MIXPANEL_NO_IFA
> end
> (untested)

**Comment by lemonkey** [comment]
Apple wrote back:

> Thank you for the information. However, iAd does not use the AdSupport framework, ASIdentifierManager, or the Advertising Identifier. Therefore they are not required for iAd implementations and should not be included in your app for iAd support. 

I'm going to have to resubmit, making sure that MIXPANEL_NO_IFA is set on the Pod target for Mixpanel.  It would be nice to have a subspec that can do this...

**Comment by justking14** [comment]
But i need the iAd framework to make the Facebook framework work

**Comment by cww0128** [comment]
How do I get IDFA with PHP?

**Comment by pchien** [comment]
@cww0128 I'm not sure I understand what you're asking. Do you have some iOS framework that lets you use PHP to integrate our library?

**Comment by cww0128** [comment]
@pchien 
Our boss told me to write an interface in PHP language, and let the IOS system user access the interface to get the unique identifier of the IOS user's cell phone, that is, IDFA. But when the client accesses my interface through the browser, I can only get the cell phone, Android or IOS, and the model of the phone, so I can't get the IDFA of the IOS phone!

the boss is kidding me?! At least I think the simple grab HTTP response header information, simply can not get IDFA, so I want to change a train of thought, I do not know if there is no interface to get IOS IDFA!



I'm sorry, I wrote it through Baidu translation. It might be a bit awkward to read

**Comment by pchien** [comment]
@cww0128 sorry I don't know what's accessible through PHP in the browser. Our SDK is for people trying to integrate Mixpanel in native apps.
