### ISSUE TITLE
Podspecs installer mechanism is great for simple projects but not appropriate for complex apps

### ISSUE THREAD

**Issue by tooluser** [mixpanel/mixpanel-iphone#110]
Podspecs is great for simple projects, but for anything with complex targets or hand-tuned build systems it's really a non-starter. 

The documentation for anything but pod specs is one line, though, and doesn't exactly work ("copy it into your project.") 

It'd be nice if build systems other than Podspecs were supported - I would imagine even most people who start with Podspecs graduate to manual configuration eventually. 

Thanks.

**Comment by malectro** [comment]
Hi guys, sorry this took so long. I have a release out that removes the need for a prefix header file, and I've tested building from source by copying the lib over to a new project.

With the addition of MPCategoryHelpers you'll also have to make sure to link that lib and use the ```-ObjC``` linker flag. I have a much more lengthy explanation here (in the last paragraph). #225

**Comment by tooluser** [comment]
That’s great! Thanks.

-- 
Poor spelling does not prove poor knowledge, but is fatal to the argument by intimidation.
    -- Gene Ward Smith
