### ISSUE TITLE
MIXPANEL_NO_IFA Define

### ISSUE THREAD

**Issue by dannenwhite** [mixpanel/mixpanel-iphone#112]
If I'm using CocoaPods, where's the best place to set this define in my workspace/project without changing the actual mixpanel pod target? Is this possible? Dumb question? :D

Thanks,
Chris

**Comment by adolfo** [comment]
It appears that CocoaPods 0.38.x breaks this fix. The solution is to change `project` to `pods_project`.

`installer.pods_project.targets.each do |target|`
