### ISSUE TITLE
flushTimer is not started after init

### ISSUE THREAD

**Issue by realf** [mixpanel/mixpanel-iphone#117]
Invocation of ```startFlushTimer``` in ```initWithToken:andFlushInterval:``` was removed in this commit e5d85f14d695be2fb9a3e28dc59fc9197a659ec9.
If the library is initialized not in application:didFinishLaunchingWithOptions:, flushing is delayed until the application enters background. This happens if some wrapper like https://github.com/segmentio/analytics-ios is used. Segment.io stores API keys on the server. When application:didFinishLaunchingWithOptions: is called our application cannot init Mixpanel, because we have to retrieve the Mixpanel API key from the Segment.io server and this request takes some time.
Starting flushTimer at the end of ```initWithToken:andFlushInterval:``` could be a possible fix.

**Comment by malectro** [comment]
Sorry for the major delay!

Your use case is totally valid, but I'm not comfortable starting the flush timer in the initialization method and am pretty sure it was changed on purpose. The timer should only be running when the app is "active", and setting it on initialize could cause this to not be the case.

That said, you should be able to start the timer manually at any time by doing the following
```[Mixpanel sharedInstance].flushInterval = [Mixpanel sharedInstance].flushInterval;```.
