### ISSUE TITLE
installation documentation does not mention dependencies

### ISSUE THREAD

**Issue by RQEBMM** [mixpanel/mixpanel-iphone#129]
UIImage+MPImageEffects uses functions from the Accelerate framework. This dependency is at no point mentioned in the non-cocoapod installation "documentation"

(mentioning them here in case someone googles it in the meantime)
"_vImageMatrixMultiply_ARGB8888"
vImageBoxConvolve_ARGB8888

**Comment by malectro** [comment]
Looks like this was solved. Updated instructions for adding the lib to a project without Cocoapods are coming soon.
