### ISSUE TITLE
Setting distinctId for two different users using the same device doesn't associate them as two distinct users for events

### ISSUE THREAD

**Issue by iwasrobbed** [mixpanel/mixpanel-iphone#130]
We came across a scenario today where two users using the same device (e.g. each has their own account and distinct internal id) doesn't allow tracking of their events separately even though we are identifying them with the proper (internal) distinct id upon login.

When we look in the Mixpanel web app, User B's events all turn into User A's events and vice versa because Mixpanel is actually associating events by the IFA rather than by the distinct ids that are being passed in from the iOS SDK, almost as if the distinct ids are just being used as an alias under the hood.

This feels very much like a bug to me, unless I'm misunderstanding the purpose of the `[[Mixpanel sharedInstance] identify:usersUUIDHere];` call.  My understanding is that any event that is logged after calling that `identify` method *should* be associated with the last set distinct id, but that is not happening.  Instead, it's being associated with the IFA regardless of whatever distinct id the client is passing in.

**Comment by malectro** [comment]
Looks like this is a request for an enhancement to the mixpanel service (and not the iOS lib) so I'm gonna close it. Please reopen if I'm wrong.

**Comment by flavordaaave** [comment]
If someone has the same issues as the OP there's a good summary of the problem and a possible solution here:
https://mixpanel.com/blog/2015/09/21/community-tip-maintaining-user-identity
