### ISSUE TITLE
Property with 'retain (or strong)' attribute must be of object type

### ISSUE THREAD

**Issue by juanpdelat** [mixpanel/mixpanel-iphone#131]
I am getting a semantic error that doesn't let me run my project after adding the library.
The error is caused by serialQueue being ```strong``` in it's declaration ```@property (nonatomic, strong) dispatch_queue_t serialQueue;``` on Mixpanel.m.

Changing the ```strong``` property to ```assign``` or removing it seems to remove the semantic error but I am not sure what other implications it has.

**Comment by malectro** [comment]
sorry, this response is coming so late. is this still an issue? if so, what version of xcode, the simulator, and the lib are you using?

**Comment by aramazhari** [comment]
It is still an issue with the latest release.
If you target build is less than iOS 6.0 you will still have this problem.

Changing the target to 6.0 (used to be 5.1.1) solved it for me.

**Comment by samgreen** [comment]
We actually dropped support for iOS versions below 6.0 in 2013 when we launched surveys.
