### ISSUE TITLE
Phonegap and/or JS-improvements

### ISSUE THREAD

**Issue by sandstrom** [mixpanel/mixpanel-iphone#132]
Mixpanel is great, but would be even more useful if we could use surveys and in-app notifications in JS-based mobile apps.

Either via a Phonegap plugin wrapping this iOS lib, or if surveys/notifications were available in the JS-SDK.

Examples of other plugins:
- TestFlight (https://build.phonegap.com/plugins/306)
- Distimo (https://build.phonegap.com/plugins/694)
- Auth0 (https://build.phonegap.com/plugins/429)

**Comment by samgreen** [comment]
Honestly, this is outside the scope of work for this repo. We have noted this as a feature request and it's something we can consider in the future.

Also note that we are happy to review a pull request if you want to wrap the library with JS. Also review the JS library that we provide, it may be possible using this: https://mixpanel.com/blog/2014/11/25/web-inapp
