### ISSUE TITLE
Documentation bug for incrementing counts

### ISSUE THREAD

**Issue by iwasrobbed** [mixpanel/mixpanel-iphone#134]
In the docs (https://mixpanel.com/help/reference/ios#storing-user-profiles), 

`[mixpanel.people increment:@"point count" by:500];`

should be

`[mixpanel.people increment:@"point count" by:@500];`

since that method expects an instance of `NSNumber` rather than an integer.

**Comment by malectro** [comment]
This has been fixed. Thanks for looking out!
