### ISSUE TITLE
Documentation bug for sign up funnels

### ISSUE THREAD

**Issue by iwasrobbed** [mixpanel/mixpanel-iphone#135]
Per our support emails, in the docs (https://mixpanel.com/help/reference/ios#user-identity), the following sentence needs to be more explicit to ensure the Mixpanel generated distinct id is set for the signup funnel.  Otherwise, if you set the `identify` to your own user ID upon signup, it's possible to hit a race condition in which the events are associated between two different buckets (one is the IFA/IFV and the other is your own internal user ID)

Please consider changing this: 

> The recommended usage pattern is to call both createAlias: and identify: when the user signs up, and only identify: (with their new user ID) when they log in. 

to this:

> The recommended usage pattern is to call both createAlias: and identify: (with the Mixpanel generated distinctId, as shown in the example above) when the user signs up, and only identify: (with their new user ID) any time they login thereafter.

**Comment by ryanseams** [comment]
Thanks for pointing this out @iwasrobbed -- went ahead and made the change you requested in the docs. If you see anything else which should be changed please let me know!
