### ISSUE TITLE
Support for importing Mix Panel as a subproject/dependency

### ISSUE THREAD

**Issue by colincornaby** [mixpanel/mixpanel-iphone#142]
Thanks for making the SDK available via Git! That makes it really easy to bring in as a submodule, or flow down into our source control if we want to try to make patches. But there are a few problems...

- The import process is kind of awful if one isn't using CocoaPods and is using a pure Git submodule setup. I have to import all the source directly into my project, including a second asset catalog. Can a project have two asset catalogs? I'm not entirely sure, I guess I'll find out.
- Without the second project, the UI to control which Git remote/branch you're using for a dependency in Xcode doesn't work at all. With the normal dependency setup where I reference another project as a dependency, I can toggle where the branch is being pulled from for that dependency. Without a sub project, Xcode can't track that.
- This also seems like a nice setup for frameworks in future versions of iOS. The best way to handle frameworks is to have an Xcode project I can reference from my project, which does the building and then imports the framework into my bundle. This also solves the duplicate assets problem by bundling the assets into your framework.

It looks like I could use CocoaPods to generate a workspace, but that just seems like a mess considering that none of our build systems have CocoaPods installed, and if I did a one-off, I'd have to do it every time I reconfigured the branches. Blech.

What I'd like to see is really just an xcodeproj present in MixPanel that I can do a one shot import of into my xcodeproj.

**Comment by Paul-van-Klaveren** [comment]
Any status updates? 
Blocked on something that we can maybe "help unblocking"?

**Comment by tabuchid** [comment]
*bump*

**Comment by samgreen** [comment]
We plan to support Carthage in the near future, and we are open sourcing the static library so that should resolve the issues you are experiencing in adding the library as a submodule.
