### ISSUE TITLE
Is it possible to use the Mixpanel iOS library inside an application extension?

### ISSUE THREAD

**Issue by barfoon** [mixpanel/mixpanel-iphone#152]
If so, how? Currently there are many referenecs to [UIApplication sharedApplication], which is not accessible in application extensions.

Thanks,

**Comment by iamtony** [comment]
@alex-hofsteede - Hello, are there any updates to this?

**Comment by athasach** [comment]
Looks like it's fixed in v2.8.0. https://github.com/mixpanel/mixpanel-iphone/releases/tag/v2.8.0

**Comment by arittr** [comment]
@iamtony @athasach yes, this is now fixed as of v2.8.0 - let us know if you run into any issues

**Comment by alex-hofsteede** [comment]
yep use `pod "Mixpanel/AppExtension"` for your app extension target in your Podfile. I'll put up some docs on the site about this.

**Comment by piemonte** [comment]
nice :ok_hand:
