### ISSUE TITLE
doesn't appear mixpanel will work in the background if data protection is enabled

### ISSUE THREAD

**Issue by ericcj** [mixpanel/mixpanel-iphone#153]
it writes data using the simple [NSKeyedArchiver archiveRootObject:p toFile:filePath] method, but instead it should probably create the files with an explicit data protection mode that allows it to collect events from the background?

**Comment by samgreen** [comment]
Hey @ericcj I'm happy to make any changes that might be required to support explicit data protection. However, I'm not really clear on what iOS feature you're describing. Would you mind showing me some documentation that describes this feature?

**Comment by ericcj** [comment]
e.g., use the following instead to make mixpanel available after the user first unlocks their device, or let the user specify this option when initializing mixpanel:

    [[NSKeyedArchiver archivedDataWithRootObject:p] writeToFile:filePath options:NSDataWritingFileProtectionCompleteUntilFirstUserAuthentication error:&error]

**Comment by samgreen** [comment]
@ericcj This option is actually more restrictive than what we're currently doing. It appears that the default is `NSDataWritingFileProtectionNone`, which will allow Mixpanel to write to the file in the background.

**Comment by samgreen** [comment]
Closing this issue. If you have issues with Mixpanel working successfully in the background, please open another issue and we'll get it resolved.
