### ISSUE TITLE
Unset Device Tokens

### ISSUE THREAD

**Issue by mullen3** [mixpanel/mixpanel-iphone#164]
I have a use case for "unsetting" device tokens via the iOS sdk. We have log-in and log-out functionality in our app. It's possible for a user to log-in with account X, log-out of that account, and then log in with account Y (all on the same device). 

I would like to be able to unregister the deviceToken for account X when they log-out.

**Comment by cerupcat** [comment]
Is there a status update to this?

**Comment by samgreen** [comment]
This can be easily accomplished by calling `unset:` and passing `@"$ios_devices"` however, I can see how this would be really useful for people so I added `removePushDeviceToken` to the public API. This will be usable in next release, 2.9.2.

#419

**Comment by alpennec** [comment]
I Sam, thanks for the addition. The code seems to be removing all the tokens. If my user is logged in on 2 devices, and logs out from device A, he is still logged in on a device B so he should still receive the notification, so Mixpanel's should only remove the current device token from the array of device token.

**Comment by jaredmixpanel** [comment]
@alpennec Currently there is no API to remove a a specific value from a List property. See @samgreen 's comment here: https://github.com/mixpanel/mixpanel-iphone/pull/419#issuecomment-174096297
