### ISSUE TITLE
In-app notifications with image zoomed in uncorrectly

### ISSUE THREAD

**Issue by diegopizzocaro** [mixpanel/mixpanel-iphone#172]
After setting up an in app notification with mixpanel.com and loading up an image which is displayed in full size in the in app notification image field. The in app is then displayed zoomed in, previously with Xcode 5, iOS7  and 2.4.1 SDK the in app notification was displayed correctly.

I am experiencing this with XCode 6 and 2.5.3 Mixpanel SDK it was also happening with 2.5.2.
Previously the image was displayed correctly, in particular with the 2.4.1 SDK and Xcode 5.
The issue seems due to Xcode 6 and how it compiles the SDK.
I have been able to reproduce the issue with both iOS 7 and iOS 8.

Here is the setup on mixpanel.com
![screen shot 2014-09-17 at 23 30 19](https://cloud.githubusercontent.com/assets/481178/4311748/eab88682-3eb1-11e4-9fd7-057ca1b04c44.png)

And here it is how it is displayed on an iPhone 5
![foto 4](https://cloud.githubusercontent.com/assets/481178/4311751/f402ddb4-3eb1-11e4-9b2b-860d921421c5.PNG)

**Comment by malectro** [comment]
looks like this is stale :(
