### ISSUE TITLE
Linker Error After Updating

### ISSUE THREAD

**Issue by abakerSavings** [mixpanel/mixpanel-iphone#173]
I updated to newest version with Cocoapods, and I am now getting this:

Undefined symbols for architecture i386:
  "_utf8_nextCharSafeBody", referenced from:
      _validate_dispatch_data_partial_string in libPods.a(MPWebSocket.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I am running on Xcode 6 GM, and it built with a previous version of Mixpanel.

**Comment by malectro** [comment]
related to https://github.com/mixpanel/mixpanel-iphone/issues/225

**Comment by aldo-jlaurenstin** [comment]
Thanks @waaed Linking libicucore.dylib worked for me.

**Comment by samgreen** [comment]
This should be resolved with the latest podspec.

**Comment by jasonwiener** [comment]
can this please be added to the manual install process on the Mixpanel Blog post? 
https://mixpanel.com/blog/2014/09/30/integrating-the-mixpanel-ios-sdk-without-cocoapods

**Comment by samgreen** [comment]
@jasonwiener can you elaborate a bit? I see `libicucore` in the screenshot from step 3.

**Comment by jasonwiener** [comment]
@samgreen i'm sorry, where do you see it in the blog post? i just looked again and can't seem to find it.
