### ISSUE TITLE
Possible issue with CTTelephonyNetworkInfo

### ISSUE THREAD

**Issue by weibel** [mixpanel/mixpanel-iphone#182]
We're seeing some crashes related to CTTelephonyNetworkInfo. Mixpanel is the only framework in our code that uses this class so I want to hear if you know anything about this or I need to look elsewhere. We're on Mixpanel v2.5.3

```
Crashed: CTTelephonyNetworkInfo
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0x5000000c

Thread : Crashed: CTTelephonyNetworkInfo
0  libobjc.A.dylib                0x36ccaf46 objc_msgSend + 5
1  CoreTelephony                  0x29e97887 _ServerConnectionCallback(__CTServerConnection*, __CFString const*, __CFDictionary const*, void*) + 34
2  CoreTelephony                  0x29ea951d ___ZNK13CTServerState21sendNotification_syncE7CTEventPK10__CFStringPK14__CFDictionary_block_invoke14 + 16
3  libdispatch.dylib              0x3721e8cb _dispatch_call_block_and_release + 10
4  libdispatch.dylib              0x37226651 _dispatch_queue_drain + 952
5  libdispatch.dylib              0x3722109d _dispatch_queue_invoke + 84
6  libdispatch.dylib              0x37227ba1 _dispatch_root_queue_drain + 320
7  libdispatch.dylib              0x37228cd7 _dispatch_worker_thread3 + 94
8  libsystem_pthread.dylib        0x3737fe31 _pthread_wqthread + 668
```

**Comment by geoffnix** [comment]
I'm getting the same error on 2.6.0, and Mixpanel is the only framework which uses CTTelephonyNetworkInfo in my app as well.

**Comment by rodrigobartels** [comment]
Hello!

We are seeing this error too in our app, any ideas how this can be fixed?

R.

**Comment by arittr** [comment]
hey @rodrigobartels so sorry to hear you're experiencing this issue as well. can you try updating our SDK to the latest version (v2.8.1) and see if that helps? we just patched a ton of bugs in the last few releases. let me know how this goes!

**Comment by jbwyme** [comment]
Closing this issue. Please re-open if you are still having problems.
