### ISSUE TITLE
Feature request: Create mixpanel 'lite' podspec

### ISSUE THREAD

**Issue by rromanchuk** [mixpanel/mixpanel-iphone#191]
Is there any chance you can create a podspec that bundles _only_ tracking API? For those of us not using user facing features, the spec is becoming extremely bloated  with assets, storyboards, and controllers. 

A few hundred KB add up, especially when other SDK maintainers like facebook refuse to fix their mess of a SDK https://github.com/facebook/facebook-ios-sdk/issues/648

With arm64 soon becoming a requirement, it's getting to the point where every single KB added from 3rd parties need to be audited.

**Comment by michalzelinka** [comment]
If you are still interested, I've made I trimmed version we use in our company's apps:

https://github.com/michalzelinka/Mixpanel-minified

It contains just basic events logging, with all notifications, surveys, A/B testing and other stuff dropped.
Feel free to use & improve, pull requests are welcome.
