### ISSUE TITLE
How to disable tracking in certain environment?

### ISSUE THREAD

**Issue by kong707** [mixpanel/mixpanel-iphone#193]
Are there a method to disable Mixpanel for entire cycle of app ?
I would like to disable tracking when in development profile .

Thanks

**Comment by oney** [comment]
Not initializing the Mixpanel will cause exceptions.
```objective-c
#if DEBUG
    Mixpanel.sharedInstanceWithToken("")
#else
    Mixpanel.sharedInstanceWithToken(MixpanelToken)
#endif
```
This way works.
