### ISSUE TITLE
Cocoapods doesn't add MixPanel correctly to swift project

### ISSUE THREAD

**Issue by samirahmed** [mixpanel/mixpanel-iphone#194]
In my swift project.  

1. I add `pod 'Mixpanel', '~> 2.5.4'` to my `podfile`
2. `pod install`  (i am running `0.34.4`)
3. open xcode add `#import "mixpanel.h"` to my objective-c bridging header
4. create a shared instance of `Mixpanel`
5. try to build and see errors saying `Mixpanel` is not defined

**my temp fix**
1. Add `lib-*-mixpanel.a` to linked binaries
2. now i see `"_utf8_nextCharSafeBody", referenced from: _validate_dispatch_data_partial_string in libPods.a(MPWebSocket.o)`
3. Add `libuicore.dylib` to my linked binaries

now my build works :)

I was persistent but you almost lost a customer there :)

**Comment by malectro** [comment]
https://github.com/mixpanel/mixpanel-iphone/issues/225

**Comment by samgreen** [comment]
This should be resolved now if you want to do a `pod install`.
