### ISSUE TITLE
Why is timeEvent a string ?

### ISSUE THREAD

**Issue by samirahmed** [mixpanel/mixpanel-iphone#195]
Why is `timeEvent` "Duration" method logging a string and not an integer of milliseconds or double of seconds or something ... 

seems really silly to not use the type system to help filter events

see [here](https://github.com/mixpanel/mixpanel-iphone/blob/f0418f2c861b082e4f98b2ccb2222ef984fe2254/Mixpanel/Mixpanel.m#L540)
`p[@"$duration"] = [NSString stringWithFormat:@"%.3f", epochInterval - [eventStartTime doubleValue]];`

It makes my analytics look like this ... 
![screen shot 2014-11-20 at 7 37 00 am](https://cloud.githubusercontent.com/assets/839972/5127270/0f7f6e1a-7088-11e4-880b-6d5c9e26c45a.png)

Any reason as to why this is? 

Regardless I am logging my own `Duration`  numeric property

**Comment by malectro** [comment]
you should be able to switch the type with the selector on the right in the UI, but i agree that the default should be a number. will add it in a coming release.
