### ISSUE TITLE
Localise survey alert

### ISSUE THREAD

**Issue by R1ckye** [mixpanel/mixpanel-iphone#202]
Hey,

I used Mixpanel and it's awesome, but I had one issue which made me unable to use a part of it: survey. Before a user takes a survey, Mixpanel asks him if he'd like to take it but the alert's strings are hardcoded (it's in Mixpanel.m around the 1300th line). Would it be possible to make this whole library localisable? I only noticed this one, are there any other hardcoded strings in the library that's presented to the user?

Many thanks,
Richard

**Comment by malectro** [comment]
hey @R1ckye , this is a totally valid request and will make more sense as the surveys product grows. we'll keep it open as a requested enhancement.

**Comment by andrey-krukovskiy** [comment]
+1 for this request

**Comment by samgreen** [comment]
Scheduling this for the next major release.

**Comment by samgreen** [comment]
Closing this in favor of the feature request from #492
