### ISSUE TITLE
Add possibility change @"time" attribute

### ISSUE THREAD

**Issue by teanet** [mixpanel/mixpanel-iphone#205]
Some users have wrong timezone or date set. So it would be great tweak this value.

```
        p[@"time"] = epochSeconds;
        if (eventStartTime) {
            [self.timedEvents removeObjectForKey:event];
            p[@"$duration"] = [NSString stringWithFormat:@"%.3f", epochInterval - [eventStartTime doubleValue]];
        }
```

**Comment by malectro** [comment]
hi @teanet sorry it took so long to respond. if you pass something like ```@{@"time": @86400}``` as the ```properties``` dictionary to the ```track``` call, it will overwrite the default time value we set.
