### ISSUE TITLE
Linker Error for _utf8_nextCharSafeBody, even after including libicucore.dylib

### ISSUE THREAD

**Issue by tindercylinder** [mixpanel/mixpanel-iphone#211]
I am trying to integrate Mixpanel into my app with a manual install (no cocoapods), but I'm getting this error:
![screen shot 2015-01-14 at 11 46 23 pm](https://cloud.githubusercontent.com/assets/6435128/5754046/d8b13d8c-9c47-11e4-9709-12e7e3ba1955.png)

I already saw the other issue #173 that stated that I should include libicucore.dylib, but it still doesn't work, even though I've added all necessary libraries and frameworks:
![screen shot 2015-01-14 at 11 45 57 pm](https://cloud.githubusercontent.com/assets/6435128/5754054/fd7869a6-9c47-11e4-9c40-7a6519ffc5e9.png)

Is there any part of the installation process I'm missing? I followed the tutorial for manual install on the blog exactly, but I can't shake this error. I've already tried cleaning and re-building. I also tried putting
-libicucore flag in Other Linker Flags. Nothing works. Any ideas?

**Comment by alex-hofsteede** [comment]
hi @tindercylinder, can you also make sure that you have `-licucore` in your 'Other Linker Flags' setting. I think that might be it.

If that solves the problem I'll add it to our documentation.

**Comment by alex-hofsteede** [comment]
hi @tindercylinder, can you also make sure that you have `-licucore` in your 'Other Linker Flags' setting. I think that might be it.

If that solves the problem I'll add it to our documentation.

**Comment by tindercylinder** [comment]
@alex-hofsteede 
Oh I mentioned I had the -libicucore flag, I meant
-licucore. Either way, I'm still having the issue.

**Comment by diogowbrito** [comment]
@alex-hofsteede [this step-by-step instruction](https://mixpanel.com/blog/2014/09/30/integrating-the-mixpanel-ios-sdk-without-cocoapods) is missing that info.

**Comment by joshblour** [comment]
adding `-licucore` solved it for me
