### ISSUE TITLE
crash on flushQueue:endpoint:

### ISSUE THREAD

**Issue by teanet** [mixpanel/mixpanel-iphone#212]
Crashed: com.mixpanel.e9386a1100754e8f62565a1b8cda8d8c.0x15746500
EXC_BREAKPOINT UNKNOWN at 0xe7ffdefe

Thread : Crashed: com.mixpanel.e9386a1100754e8f62565a1b8cda8d8c.0x15746500
0  CoreFoundation                 0x2e05a9f8 __CFBasicHashDeallocate + 48
1  CoreFoundation                 0x2df70127 CFRelease + 466
2  IAPFreeService.dylib           0x00844795 -[IAPFreeConfiguration reload] + 140
3  IAPFreeService.dylib           0x00844985 +[IAPFreeConfiguration sharedInstance] + 80
4  IAPFreeService.dylib           0x00851de9 _ZL65$$NSURLConnection$sendSynchronousRequest$returningResponse$error$P10objc_classP13objc_selectorP12NSURLRequestPP13NSURLResponsePP7NSError + 60
5  ***                          0x0026e8c9 -[Mixpanel flushQueue:endpoint:] (Mixpanel.m:761)
6  ***                          0x0026e6e1 __17-[Mixpanel flush]_block_invoke (Mixpanel.m:728)
7  libdispatch.dylib              0x38cbfd53 _dispatch_call_block_and_release + 10
8  libdispatch.dylib              0x38cc4cbd _dispatch_queue_drain + 488
9  libdispatch.dylib              0x38cc1c6f _dispatch_queue_invoke + 42
10 libdispatch.dylib              0x38cc55f1 _dispatch_root_queue_drain + 76
11 libdispatch.dylib              0x38cc58dd _dispatch_worker_thread2 + 56
12 libsystem_pthread.dylib        0x38df0c17 _pthread_wqthread + 298

version 2.6.2

**Comment by malectro** [comment]
Hi @teanet, a quick search for IAPFreeService.dylib (the lib references on line 2) tells me this is a jailbroken phone. Seems like they've hijacked the NSURLConnection request and done something nasty. Suffice to say, I don't think there's a solution to this without uninstalling whatever software the user has added to this phone.

**Comment by teanet** [comment]
Hello @malectro, I have received this crash from unknown user, maybe he has jailbroken device.
thank you for response.
