### ISSUE TITLE
crash on checkForDecideResponseWithCompletion:useCache:

### ISSUE THREAD

**Issue by teanet** [mixpanel/mixpanel-iphone#213]
Thread : Crashed: com.mixpanel.cbf84d3a959d264d62c06a48d03b1a28.0x165c5b10
0  CoreFoundation                 0x2e05a9f8 __CFBasicHashDeallocate + 48
1  CoreFoundation                 0x2df70127 CFRelease + 466
2  IAPFreeService.dylib           0x00844795 -[IAPFreeConfiguration reload] + 140
3  IAPFreeService.dylib           0x00844985 +[IAPFreeConfiguration sharedInstance] + 80
4  IAPFreeService.dylib           0x00851de9 _ZL65$$NSURLConnection$sendSynchronousRequest$returningResponse$error$P10objc_classP13objc_selectorP12NSURLRequestPP13NSURLResponsePP7NSError + 60
5  ***                          0x00282fb3 __58-[Mixpanel checkForDecideResponseWithCompletion:useCache:]_block_invoke (Mixpanel.m:1149)
6  libdispatch.dylib              0x38cbfd53 _dispatch_call_block_and_release + 10
7  libdispatch.dylib              0x38cc4cbd _dispatch_queue_drain + 488
8  libdispatch.dylib              0x38cc1c6f _dispatch_queue_invoke + 42
9  libdispatch.dylib              0x38cc55f1 _dispatch_root_queue_drain + 76
10 libdispatch.dylib              0x38cc58dd _dispatch_worker_thread2 + 56
11 libsystem_pthread.dylib        0x38df0c17 _pthread_wqthread + 298

version 2.6.???

**Comment by malectro** [comment]
IAPFreeService.dylib also seems to be the culprit here (not mixpanel). It would appear that it has a reference counting issue since it's crashing on dealloc.
