### ISSUE TITLE
Definition of 'NSString' must be imported from module 'Foundation.NSString' before it is required

### ISSUE THREAD

**Issue by pedro380085** [mixpanel/mixpanel-iphone#214]
I'm getting the following error:

Mixpanel/MPLogger.h:15:35: Definition of 'NSString' must be imported from module 'Foundation.NSString' before it is required

Mixpanel/UIImage+MPImageEffects.m:102:9: In file included from Mixpanel/UIImage+MPImageEffects.m:102:

All frameworks deemed as necessary have been included. I though at first it could be a duplicate issue, but haven't found any reference to this being the case. Someone can help? Thanks.

**Comment by Quuxplusone** [comment]
Indeed, "MPLogger.h" should have these lines near the top:

    #import <Foundation/NSString.h>
    #include <stdarg.h>

**Comment by alex-hofsteede** [comment]
XCode initializes new projects with a `ProjectName-Prefix.pch` file in `Supporting Files` file that includes ` <Foundation/Foundation.h>` in all source files in a project. We have basically relied on that feature of XCode to provide the foundation classes like NSString, NSDictionary, etc. but we probably should include the Foundation classes import explicitly for projects that don't have a `.pch` file.

**Comment by pedro380085** [comment]
@alex-hofsteede I would be thankful if an update could be provided with these modifications.

**Comment by malectro** [comment]
@pedro380085 sounds like this is related to https://github.com/mixpanel/mixpanel-iphone/issues/215 should be fixed with the next release.
