### ISSUE TITLE
Cannot find interface declaration for 'NSValueTransformer', superclass of 'MPPassThroughValueTransformer'

### ISSUE THREAD

**Issue by pedro380085** [mixpanel/mixpanel-iphone#215]
Foundation framework has been included, but the following error keeps coming up: Mixpanel/MPUIFontToNSDictionaryValueTransformer.m:4:9: In file included from Mixpanel/MPUIFontToNSDictionaryValueTransformer.m:4:

**Comment by arittr** [comment]
@pedro380085 can you try integrating via cocoapods? this is an issue we're working through - it seems like a linker problem when building from source that doesn't happen with pods.

**Comment by Quuxplusone** [comment]
Indeed, "Mixpanel/MPValueTransformers.h" is missing the following line at the top of the file:

    #import <Foundation/Foundation.h>

It seems to have been accidentally removed in d1351a13c4dca374ce0494f0b7869b84d66ff6f2.

**Comment by pedro380085** [comment]
@Quuxplusone comment seems to be the right solution. Thanks!

**Comment by malectro** [comment]
this seems to be because xcode 6 stopped autocreating a Prefix.pch file. i'll have the solution https://github.com/mixpanel/mixpanel-iphone/pull/222 out soon.

**Comment by pedro380085** [comment]
Good, thanks!
