### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation) 

### ISSUE THREAD

**Issue by FredvanRijswijk** [mixpanel/mixpanel-iphone#216]
Installing with pods and review all the link file errors, still keeping this error: clang: error: linker command failed with exit code 1 (use -v to see invocation) 

After installing Pod, error is missing link to: libMPCategoryHelpers.a, manual link to this library is also not working because I get the error above ;-(

**Comment by malectro** [comment]
@FredvanRijswijk what version of cocoapods do you have installed? i'm worried older versions aren't correctly linking our libs.

**Comment by malectro** [comment]
related to #225

**Comment by samgreen** [comment]
This will be resolved in the next release since we have removed the static library.

**Comment by DataGreed** [comment]
same problem today

**Comment by zihejia** [comment]
Hi @DataGreed , could you provide more information as which version you are using and how you integrate Mixpanel? Did you try a clean a build?

**Comment by DataGreed** [comment]
Tried cleaning build, did not help. I ended up reinstalling mixpanel sdk with Carthage and it finally worked.
