### ISSUE TITLE
Issues related to disabling ABDesigner with CocoaPod

### ISSUE THREAD

**Issue by LanceFu** [mixpanel/mixpanel-iphone#224]
It's related to #221 and #220, sort of. Now that MPLog is replaced by MixpanelError, which is great, we no longer see logs from Mixpanel. However, it's still running in the background, just not ouputing it. I would love an easier way to disable ABDesigner. It's a feature that I will probably never use. I don't want it running in the background when I am debugging and optimizing. It's fine if Mixpanel decides it should be on by default, but at least provide us a way to opt out without having to resort to forking the project. 

Yes, I am aware of the DISABLE_MIXPANEL_AB_DESIGNER flag we can add to our preprocessor macros in the project settings. However, I am using CocoaPod to manage all the dependencies in my project. Adding the flag to my project does nothing, it has to be added to the Pods-Mixpanel target, which is created by CocoaPod automatically. It's overwritten every time we run "pod update". It means it has to be a manual process every time just to turn it off. 

Can we add a boolean value on Mixpanel object, which can default to YES, but expose it for developers to set it to NO if choose to? There must be an easier way. Thanks a lot.

**Comment by jadar** [comment]
Yes I don't really understand the idea behind using Preprocessor Macros in a library. Most of the time you're either using a static lib or building a CocoaPod. 

While there is a way to set build flags with Cocoapods in the `post_install` method, it'd be way easier to be able to toggle it in the Mixpanel `+ (instancetype) sharedInstanceWithLaunchOptions:(NSDictionary *)launchoptions` message.

**Comment by malectro** [comment]
hey guys, using the macro allows some customers to compile versions of the lib that do not include the ab testing functionality (vs just shutting it off) so it was a must. it also makes it easy for them to use the macro differently with different build targets.

that said, we're in a small debate now about whether the addition of a flag would be good to add as well, but it looks likely we'll add it if a better solution doesn't present itself. sorry again about all the console spam.

**Comment by samgreen** [comment]
@LanceFu You can add the macro to the Podfile and it will prevent it from being overwritten when you perform a `pod update`.

http://guides.cocoapods.org/syntax/podfile.html#post_install

Closing this issue, please re-open if this doesn't solve your problem.
