### ISSUE TITLE
Cocoapods fails to link some library files

### ISSUE THREAD

**Issue by malectro** [mixpanel/mixpanel-iphone#225]
In an effort to centralize the conversation about this issue:

The Mixpanel cocoapods is set to link libMPCategoryHelpers.a and libuicore.dylib but sometimes fails to do so during installation. In most cases customers have been successful in manually linking the libs within their projects, but we're currently working on a more better solution.

Edit:
After some digging, it looks like Cocoapods requires the ```-ObjC``` linker flag (and amends the "Other Linker Flags" Build Setting) upon installation. Though adding ```-ObjC``` flag is the preferred method for [loading static libraries with Categories](https://developer.apple.com/ibrary/mac/qa/qa1490/_index.html), developers that have fine-tuned library and framework linking can mess up their build process by doing so. This could be why some libraries aren't linking in the first place, but I'm not yet sure.

Cocoapods effectively made this a wont-fix with the idea that "frameworks are on the horizon", but it's possible to link each lib manually using the ```force_load``` tag. For an app using the latest version of Cocoapods (as of 0.35) and Mixpanel 2.7, the Other Linker Flags should look like this

![screen shot 2015-02-03 at 6 33 54 pm](https://cloud.githubusercontent.com/assets/249565/6046774/d8b6e9e0-ac59-11e4-95f4-494d51f37e3f.png)

For apps integrating Mixpanel without Cocoapods, I'd recommend simply adding the ```-ObjC``` flag, but if this isn't possible, customers can force_load MPCategoryHelpers by adding ```-force_load $(SRCROOT)/path/to/libMPCategoryHelpers.a``` to their linker build settings. (Note that "path/to" is just a placeholder for the path to the lib within the app.)

**Comment by Suz** [comment]
I just had this problem with SocketRocket and nothing made sense:  the -ObjC flag is there and the libraries are linked, but it was still giving errors. Finally realised that I had added SocketRocket to both my App and to the test target, but I had only linked the App against the library. I was getting the error because the test target also needed to be linked. Duh.

**Comment by samgreen** [comment]
This will be resolved with #288.

**Comment by samgreen** [comment]
This should be resolved now if you want to do a `pod install`.

**Comment by shaunbruno** [comment]
This is not fixed

**Comment by shaunbruno** [comment]
<img width="580" alt="screen shot 2015-11-20 at 12 49 33 pm" src="https://cloud.githubusercontent.com/assets/757901/11311514/34ac1932-8f85-11e5-9a4c-f08b399d8373.png">
