### ISSUE TITLE
Calling Mixpanel flush from application:didReceiveRemoteNotification:fetchCompletionHandler:

### ISSUE THREAD

**Issue by bejar37** [mixpanel/mixpanel-iphone#226]
I want to log an event in this method, even if it is called while the application is in the background state. Currently, just using `trackEvent:` would just save the event, which would then be sent next time the application is brought to the foreground. 

Calling `flush` right after `trackEvent` Doesn't seem particularly safe though, since all flush does it place a task on a serial queue. Is flush supposed to be able to be called from the background state?

**Comment by malectro** [comment]
hi @bejar37, by default the Mixpanel lib calls flush when an application is backgrounded so it should be safe to call when receiving a remote notification too. unfortunately we don't expose the ```serialQueue``` publicly so you wouldn't be able to ensure that the flush completed before calling the ```fetchCompletionHandler```, but it should be totally fine if the flush is cut short (as shown here github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L1037).

regardless an optional completion handler for flush would be a better long term solution. i'll keep this open as an enhancement.

**Comment by bejar37** [comment]
Thanks for getting back to me! Yes I noticed that in `- didEnterBackground:` there is a call to `beginBackgroundTaskWithExpirationHandler:`, which won't be called when I call `flush` from the background. 

Here is some example code (In an app delegate):

    - (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
        switch (application.applicationState) {
             case UIApplicationStateBackground:
                 [[Mixpanel sharedInstance] trackEvent:@"received_background_notif" properties:properties];
                 [[Mixpanel sharedIntance] flush];
                 //do some other stuff
                 completionHandler(UIBackgroundFetchResultNewData);
                 break;
              // do more stuff
         }
    }

I need to guarantee that this event get flushed while in the background, because otherwise it won't be logged until the next time the user foregrounds the app. Since flush doesn't take a callback and isn't synchronous, I'm forced to call `completionHandler` without the flush being completed.

So, to be clear, this library doesn't currently support my use case?

**Comment by malectro** [comment]
yeah, unfortunately we wouldn't be able to ensure that the flush finished, but you make a good case. i'll discuss with the team and get a solution out in a coming release.

**Comment by samgreen** [comment]
We'll get this change merged in to master for the latest release.
