### ISSUE TITLE
-[__NSCFType headIndent]: unrecognized selector sent to instance on iOS

### ISSUE THREAD

**Issue by ventayol** [mixpanel/mixpanel-iphone#230]
I've installed Mixpanel in my iOS app but it crashes every time I try to track an event.

Here you have a screenshot of the crash information:

![screen shot 2015-02-16 at 23 15 24](https://cloud.githubusercontent.com/assets/1505998/6220080/daec8490-b631-11e4-9a1a-608e66dd882d.png)

I haven't been able to use the product at all.

**Comment by nwinter** [comment]
I'm getting the same crash. Did anyone ever come up with a workaround?

**Comment by ventayol** [comment]
Looks fine in the last version

**Comment by zdravkin** [comment]
I get the same crash using iPad Air iOS 8.3. The issue looks to be in the attributed string. This is not fixed.

Error:
-[__NSCFType headIndent]: unrecognized selector sent to instance 0x7fa2ec611890

**Comment by samgreen** [comment]
This is a bug in the Foundation framework. We have filed a radar with Apple. Unfortunately since we don't call `headIdent` anywhere in the Mixpanel library, there's nothing we can do to fix this. Hopefully this will be resolved in iOS 8.4
