### ISSUE TITLE
`reset` should reset `shownSurveyCollections` and `shownNotifications`

### ISSUE THREAD

**Issue by peymano** [mixpanel/mixpanel-iphone#232]
In our app, when a user signs out, we call Mixpanel's `reset` method. If a different user signs in, user 2 wont see any in-app notifications that user 1 has already seen.

This seems like an oversight of the `reset` method. It resets all archived properties except `self.shownSurveyCollections` and `self.shownNotifications`.

```
- (void)reset
{
    dispatch_async(self.serialQueue, ^{
        self.distinctId = [self defaultDistinctId];
        self.nameTag = nil;
        self.superProperties = [NSMutableDictionary dictionary];
        self.people.distinctId = nil;
        self.people.unidentifiedQueue = [NSMutableArray array];
        self.eventsQueue = [NSMutableArray array];
        self.peopleQueue = [NSMutableArray array];
        self.timedEvents = [NSMutableDictionary dictionary];
        [self archive];
    });
}
```

**Comment by Grubas7** [comment]
Same with surveys.

**Comment by Grubas7** [comment]
Probably in reset method, boolean value of `decideResponseCached` should be set to NO to allows `-checkForDecideResponseWithCompletion: useCache:` method call success block of `if (!useCache || !self.decideResponseCached)`.

**Comment by samgreen** [comment]
This is resolved in #295

**Comment by yas375** [comment]
@Grubas7 @samgreen thanks for taking care of this!

Re: 3b31d3f8a3dfb6adf95b0adaf23b96e756525680
Could you please elaborate a little more why `self.shownNotifications` doesn't need to be reset too as it was suggested by @peymano?

**Comment by yas375** [comment]
In my understanding `self.shownNotifications` needs to be reset too:


```
- (void)checkForDecideResponseWithCompletion:(void (^)(NSArray *surveys, NSArray *notifications, NSSet *variants, NSSet *eventBindings))completion useCache:(BOOL)useCache
{
    dispatch_async(self.serialQueue, ^{
        MixpanelDebug(@"%@ decide check started", self);
        ...
        if (!useCache || !self.decideResponseCached) {
          ...
        }
        ...
        NSArray *unseenNotifications = [self.notifications objectsAtIndexes:[self.notifications indexesOfObjectsPassingTest:^BOOL(id obj, NSUInteger idx, BOOL *stop) {
            return [self.shownNotifications member:@(((MPNotification *)obj).ID)] == nil;
        }]];
        ...
    });
}
```

**Comment by Grubas7** [comment]
@yas375 Yeap, shownNotifications should be reset too. My PR fixed only surveys feature. I had never use norifications via Mixpanel, so I couldn't test this. That's why I didn't try to fix it.
