### ISSUE TITLE
identify method does not add nothing on mixpanel people dashboard

### ISSUE THREAD

**Issue by dorinsimina** [mixpanel/mixpanel-iphone#233]
Hi all,

I have a problem using the iOS API – identify. In mixpanel dashboard, people – explore tabs it constantly says that I haven’t sent any data.

The following code is reachable and the obtained app user ID is valid:
Mixpanel *mixpanel = [Mixpanel sharedInstance];
[mixpanel identify:[NSString stringWithFormat:@"%@", [standardUserDefaults valueForKey:APP_USER_ID]]];

Does anyone have a fix?

**Comment by matthewellis** [comment]
Had to contact support to figure this one out but you also need to set a user property for the user to be created with that identity. 

This can be done without adding any dummy data using [mixpanel.people set:@{}];

**Comment by Grubas7** [comment]
@dorinsimina 
I had same problem. Everything start to work well after I added some property for object people, eg:
> [mixpanel.people set:@{ @"$name": userId }];
so after all:
> [mixpanel identify:userId];
> [mixpanel.people set:@{ @"$name": userId }];

**Comment by samgreen** [comment]
`identify:` doesn't actually make any network calls, so until data is flushed to the network we don't have this information on the back end. For more details about User Profiles you can read the documentation here: https://mixpanel.com/help/reference/ios#storing-user-profiles
