### ISSUE TITLE
Clear preferences on Logout

### ISSUE THREAD

**Issue by somghosh** [mixpanel/mixpanel-iphone#240]
How can I clear the preferences on logout in my app using Mixpanel iOS library? I am looking at something similar to the functionality in java : https://github.com/mixpanel/mixpanel-android/issues/151

**Comment by joeatwork** [comment]
Thanks for this report! Maintainers, this is a reference to the MixpanelAPI.reset method on Android, with the following semantics:

```
    /**
     * Clears all distinct_ids, superProperties, and push registrations from persistent storage.
     * Will not clear referrer information.
     */
```

**Comment by simonlinj** [comment]
any other action to make after a user logout beside this [[Mixpanel sharedInstance] reset] ?

**Comment by samgreen** [comment]
Resolved.
