### ISSUE TITLE
Use timeEvent in session length example?

### ISSUE THREAD

**Issue by nozaq** [mixpanel/mixpanel-iphone#242]
Hi, 

In HelloMixpanel example, the session start time is manually managed by AppDelegate.
https://github.com/mixpanel/mixpanel-iphone/blob/master/HelloMixpanel/HelloMixpanel/AppDelegate.m#L145

Is there any specific reason not using MixPanel#timeEvent instead of manually managing the start time?

**Comment by samgreen** [comment]
@nozaq No specific reason, and the sample code should likely be updated.
