### ISSUE TITLE
[UIApplication sharedApplication] is unavailable in app extensions

### ISSUE THREAD

**Issue by chamarapaul** [mixpanel/mixpanel-iphone#244]
I'm trying to use Mixpanel with a Watchkit extension, and I'm getting the following error: 
'sharedApplication' is unavailable: not available on iOS (App Extension)

Any way to guard against unsupported APIs in extensions? Thanks.

**Comment by arittr** [comment]
hey @chamarapaul - our SDK hasn't been tested for WatchKit compatibility yet. once we get a few test devices we should be able to figure out a workaround here. we're all really excited about the possibility of Mixpanel on the Apple Watch - awesome that you're already getting started! I'll update this thread when I have a patch for this.

**Comment by noremac** [comment]
+1

Could a cocoapod subspec be written that only includes the analytics engine? That would solve this issue most likely.

**Comment by robmaceachern** [comment]
+1

Here's the discussion in AFNetworking regarding the issue https://github.com/AFNetworking/AFNetworking/issues/2119

**Comment by gtranchedone** [comment]
+1 Just got the same issue. There's no need for all the UI tracking stuff in there. Just make it a subspec for CocoaPods. I might managed to do it later and try it. If it works fine I'll send a Pull Request.

**Comment by sethroot** [comment]
Has there been any progress on this issue? It is critical for our project that we be able to track events in a keyboard extension.

**Comment by alex-hofsteede** [comment]
@sethroot I expect to have a version of the Mixpanel library that works in all app extensions (including watch extensions) out by tomorrow.

**Comment by appsforall** [comment]
Hi there! Did you already manage to get a new version out? We are stuck with the exact same problem as @sethroot. We would love to use Mixpanel in our extensions (widget + watch), but cannot since we have this sharedApplication problem.

**Comment by neerajbaid** [comment]
+1

**Comment by alex-hofsteede** [comment]
Working to get this out asap.

**Comment by alex-hofsteede** [comment]
https://github.com/mixpanel/mixpanel-iphone/releases/tag/v2.8.0

**Comment by obuseme** [comment]
What's the correct way to do this with MixPanel 2.9 since the AppExtension subspec was replaced with a WatchOS specific version?  Is there a way to use MixPanel from iOS extensions?

**Comment by samgreen** [comment]
@obuseme Is it a watchkit extension or something else, like a today extension?

**Comment by obuseme** [comment]
iOS Share Extension

**Comment by samgreen** [comment]
Thanks @obuseme, it was actually an oversight that the extension was removed from the podspec. We still support it, and I'll make sure the subspec gets re-added to 2.9.4

**Comment by obuseme** [comment]
Great thanks

**Comment by samgreen** [comment]
@obuseme This is out now with v2.9.4
