### ISSUE TITLE
[2.7.3] Assertion failed in MPWebSocket.m:300, automatic tracking setup with Personnal Device

### ISSUE THREAD

**Issue by lucasgerard** [mixpanel/mixpanel-iphone#255]
Hi, I'm getting a crash trying to set up the automatic tracking with a device:

Assertion failed: (request.URL), function -[MPWebSocket initWithURLRequest:protocols:], file /Users/lucasgerard/rails_projects/shotguntheapp/ios/Shotgun/Pods/Mixpanel/Mixpanel/MPWebSocket.m, line 300.
![mixpanel](https://cloud.githubusercontent.com/assets/5589858/7364607/b5643824-ed88-11e4-827a-d6c89c6b3476.png)

Thank you for your support!

**Comment by lucasgerard** [comment]
Hi, still having the same issue with v2.8.1.

Cheers,

Lucas

**Comment by samgreen** [comment]
Closing this due to valid workaround. Please file another issue if you find another problem.
