### ISSUE TITLE
Build errors in MPSurveyNavigationController.m and MPSurveyQuestionViewController.m in XCode 6.3

### ISSUE THREAD

**Issue by tringkishorekumar** [mixpanel/mixpanel-iphone#256]
When I set the "Treat Warnings as Errors" as YES in build settings and build in XCode 6.3, I'm getting build errors in MPSurveyNavigationController.m and MPSurveyQuestionViewController.m.

In MPSurveyNavigationController the error shows "Auto property synthesis will not synthesize property 'view'; it will be implemented by its superclass, use @dynamic 
to acknowledge intention”. We should not be having an UIImageView named view. This is overriding the UIViewController “view” property, which should not be the case. This property should be renamed.

I'm not sure if we are actually using this "view" property.

We have similar issues in "question" property in MPSurveyMultipleChoiceQuestionViewController and MPSurveyTextQuestionViewController where we are overriding the "question" property from its parent "MPSurveyQuestionViewController".

We should acknowledge these properties with an @dynamic to let the compiler know that these variables will be synthesized in the parent and we can still override it in the child.

**Comment by arittr** [comment]
@tringkishorekumar thanks so much for posting this - we're going to take a look at getting this patched for a future release. i'll update this thread when we push a fix - thanks again!

**Comment by jamietsao** [comment]
I'm seeing the same warnings.  Any updates on this?

**Comment by samgreen** [comment]
I show this as resolved, can you please chime in and let me know if you're still having this issue?
