### ISSUE TITLE
App Store Submit for Review not accepted due to "Your app is using the Advertising Identifier (IDFA)"

### ISSUE THREAD

**Issue by dwalintukan** [mixpanel/mixpanel-iphone#264]
I am trying to submit my app for App Store Review, but it is stating that I am using the Advertising Identifier, but I am not.

1. Using Cocoapods to import Mixpanel, `pod 'Mixpanel'`
2. Using this at the end of my podfile
`post_install do |installer|
    installer.project.targets.each do |target|
        target.build_configurations.each do |config|
            preprocessor_definitions = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']
            preprocessor_definitions = ['$(inherited)'] if preprocessor_definitions == nil
            preprocessor_definitions.push 'MIXPANEL_NO_IFA' if target.to_s.include? 'Mixpanel'
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = preprocessor_definitions
        end
    end
end`
3. This creates the `MIXPANEL_NO_IFA` preprocessor macro in the `Pods-Mixpanel target`
4. I tested by putting breakpoints in the `#ifndef` function that uses `ASIdentifierManagerClass` and the `NSString ifa` is returning nil and ran in in debug mode

I did a full search of `ASIdentifierManager` and Mixpanel and HockeyApp are the only two that referenced that class. And I checked with HockeyApp and they do not use the IDFA. So that leaves Mixpanel with the only reference to it.

What else can I do to make this work? Please help!!!

**Comment by drmarshall** [comment]
@dwalintukan – an awesome support engineer sent you an email to reduce back-and-forth spam. You can see some troubleshooting on it in Issue#112   We'll post the final solution here.

**Comment by tichise** [comment]
I also ran into the same problem. Please tell me the solution.

**Comment by tichise** [comment]
@drmarshall 

I also ran into the same problem. Please tell me the solution.

1. I have been reject in 3.3.12 Once you apply for the app put the mixpanel sdk by select are using idfa in app store.
2. After one, I put MIXPANEL_NO_IFA to preprocessor macros, and re-application Build by select not using idfa. But the following error it failed to apply for leave.

This App uses the ad ID (IDFA). You can provide the details of the IDFA usage, you will need to re-send the binary to remove the IDFA from App.

**Comment by alex-hofsteede** [comment]
@tichise Couple of things. 
1. `MIXPANEL_NO_IFA` needs to go in the preprocessor macros for the `Pods-Mixpanel` target, not your main application target. 
2. You should also make sure that `AdSupport.framework` is not included in your linked libraries and frameworks. Even if you're not using it, apple may still be rejecting the binary if it links against this framework.

**Comment by tichise** [comment]
@drmarshall  @alex-hofsteede 

#### 1. I have to add the MIXPANEL_NO_IFA to Pods-Mixpanel target.
I am writing a code of this feeling in Podfile.

```
post_install do | installer |

     installer.project.targets.each do | target |
         target.build_configurations.each do | config |
             preprocessor_definitions = config.build_settings ['GCC_PREPROCESSOR_DEFINITIONS']
             preprocessor_definitions = ['$ (inherited)'] if preprocessor_definitions == nil
             preprocessor_definitions.push 'MIXPANEL_NO_IFA' if target.to_s.include? 'Mixpanel'
             config.build_settings ['GCC_PREPROCESSOR_DEFINITIONS'] = preprocessor_definitions
         end
     end
end
```

#### 2. I apply Remove all I already AdSupport.framework.

Even in this state, could not be submitted to the app store is a setting that does not use idfa because of the advertisingIdentifier exists in ipa file.

**Comment by alex-hofsteede** [comment]
Could you please open `Mixpanel.m` in the Xcode assistant editor and choose 'Preprocess' from the counterparts list? This should show you the file after it has been preprocessed (all `#import`s expanded, all macros evaluated etc.) You should see that the `IFA` function is reduced to 2 lines that effectively just returns nil and there is no mention of `advertisingIdentifier` or anything related to AdSupport anywhere in the file. 

If the preprocessor is evaluating those macros correctly, it should be impossible for the output ipa file to contain `advertisingIdentifier` unless it is also being referenced somewhere else in the code.

http://cometapp.us/c/oikUA47j

**Comment by samgreen** [comment]
Closing this due to lack of recent communication.
