### ISSUE TITLE
Add support for Carthage

### ISSUE THREAD

**Issue by alec-c4** [mixpanel/mixpanel-iphone#265]
Hi.
could you please add support for https://github.com/Carthage/Carthage?

**Comment by wtmoose** [comment]
+1

**Comment by Rupert-RR** [comment]
+lots

We simply need a framework target, and uses of ``[NSBundle mainBundle]`` should be replaced with ``[NSBundle bundleForClass:]`` to correctly reference its resources (this is considered good practice anyway).

**Comment by wmalloc** [comment]
+∞

**Comment by pcantrell** [comment]
+1

**Comment by hemantasapkota** [comment]
For carthage support, you can checkout https://github.com/hemantasapkota/mixpanel-swift.

It adds the mixpanel-iphone project as a git subtreee module and wraps it with a Swift framework with Carthage support.

Thanks

**Comment by Rupert-RR** [comment]
@hemantasapkota Thanks for that, but obviously it is better for all concerned if Carthage support is provided by the repo owner.
PR #252 should make this possible (thanks to @simX)

**Comment by hemantasapkota** [comment]
Yep, I agree. This is meant as a temporary solution.

**Comment by samgreen** [comment]
Carthage support is added now with #252. You can build from carthage from master now.

**Comment by alpennec** [comment]
Hi,

Carthage does not seem to be working anymore (either updating for all platforms or only for iOS).
Can you help please?

Thanks,
Axel

<img width="1426" alt="screenshot 2016-01-29 17 17 58" src="https://cloud.githubusercontent.com/assets/2082662/12681030/d9f228ce-c6ac-11e5-9f13-40dac792c2b9.png">

**Comment by samgreen** [comment]
Hey @alpennec this is definitely an issue. Looking at it now.

**Comment by alpennec** [comment]
Thanks @samgreen. Any idea when this is going to be resolved? Thanks!

**Comment by JagCesar** [comment]
@alpennec: A quick workaround is to set the version to 2.9.1 by writing this in your Cartfile:
```
github "mixpanel/mixpanel-iphone" == 2.9.1
```

**Comment by JagCesar** [comment]
I created an issue for this btw, found here: https://github.com/mixpanel/mixpanel-iphone/issues/427
