### ISSUE TITLE
In app message has break UIAlertView

### ISSUE THREAD

**Issue by SvenSven2009** [mixpanel/mixpanel-iphone#268]
We have a issue with "In-app message" and UIAlertView. If UIAlertView is shown and   Mixpanel presents "In-app message" (above alert) after i dismiss in-app message(by click cross button in the upper right corner) UIAlertView was shifted to the upper left corner. Please, see attached screenshots.
Could you please investigate this issue ...
![1](https://cloud.githubusercontent.com/assets/2912582/7811828/00520f80-03b6-11e5-8342-5d23fe54dba9.png)
![2](https://cloud.githubusercontent.com/assets/2912582/7811829/04f7bdf0-03b6-11e5-8f58-d7dca447f7f9.png)
![3](https://cloud.githubusercontent.com/assets/2912582/7811860/3e97a660-03b6-11e5-8f7c-6abfff369c40.png)

**Comment by arittr** [comment]
@SvenSven2009 so sorry for the delay as we work through this - thanks for your patience.

@alex-hofsteede can you take a look at this when you get a chance?

**Comment by SvenSven2009** [comment]
Hi guys,
May be any updates?

**Comment by yas375** [comment]
We are experiencing the same issue. I made a simple [sample project](https://github.com/yas375/ExampleApp/tree/mixpanel/mixpanel-iphone/268) to see if I can get this issue to reproduce in isolated environment with just simple UIAlertView, UIAlertController and UIViewControllers. Indeed, we shouldn't try to present any view controller from UIAlertController.
