### ISSUE TITLE
Continuos crash at MPObjectSerializer.m:274

### ISSUE THREAD

**Issue by lucaseverini** [mixpanel/mixpanel-iphone#273]
Hello,

Latest version of mixpanel crashes my app at the moment I try to connect (Happens on both phone and simulator).
Please advise how to solve that.
Do you have an older, stable version?
Thank you!

Stack trace
#0	0x00000001952dfbd0 in objc_msgSend ()
#1	0x0000000184a63e7c in -[__NSSetM addObject:] ()
#2	0x0000000189628f88 in -[UIControl allTargets] ()
#3	0x00000001001021c4 in -[UIView(MPHelpers) mp_targetActions] at /Users/acanyon/mixpanel-iphone-helpers/MPCategoryHelpers/UIView+MPHelpers.m:64
#4	0x0000000100102cf8 in -[UIView(MPHelpers) mp_varSetD] at /Users/acanyon/mixpanel-iphone-helpers/MPCategoryHelpers/UIView+MPHelpers.m:169
#5	0x0000000184b7c3c0 in __invoking___ ()
#6	0x0000000184a7a138 in -[NSInvocation invoke] ()
#7	0x0000000184a7ecd0 in -[NSInvocation invokeWithTarget:] ()
#8	0x000000010029e168 in -[MPObjectSerializer propertyValueForObject:withPropertyDescription:context:] at /Jobs/Sommly/sommly-frontend/Pods/Mixpanel/Mixpanel/MPObjectSerializer.m:274
#9	0x000000010029b918 in -[MPObjectSerializer visitObject:withContext:] at /Jobs/Sommly/sommly-frontend/Pods/Mixpanel/Mixpanel/MPObjectSerializer.m:67
#10	0x000000010029b3d0 in -[MPObjectSerializer serializedObjectsWithRootObject:] at /Jobs/Sommly/sommly-frontend/Pods/Mixpanel/Mixpanel/MPObjectSerializer.m:45
#11	0x0000000100285fbc in -[MPApplicationStateSerializer objectHierarchyForWindowAtIndex:] at /Jobs/Sommly/sommly-frontend/Pods/Mixpanel/Mixpanel/MPApplicationStateSerializer.m:68
#12	0x0000000100283c80 in __72-[MPABTestDesignerSnapshotRequestMessage responseCommandWithConnection:]_block_invoke45 at /Jobs/Sommly/sommly-frontend/Pods/Mixpanel/Mixpanel/MPABTestDesignerSnapshotRequestMessage.m:80
#13	0x0000000100830df0 in _dispatch_client_callout ()
#14	0x000000010083e88c in _dispatch_barrier_sync_f_slow_invoke ()
#15	0x0000000100830df0 in _dispatch_client_callout ()
#16	0x000000010083575c in _dispatch_main_queue_callback_4CF ()
#17	0x0000000184b2dfa4 in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
#18	0x0000000184b2c04c in __CFRunLoopRun ()
#19	0x0000000184a590a4 in CFRunLoopRunSpecific ()
#20	0x000000018dbfb5a4 in GSEventRunModal ()
#21	0x000000018938e3c0 in UIApplicationMain ()
#22	0x00000001000bb9c4 in main at /Jobs/Sommly/sommly-frontend/Sommly/main.m:13
#23	0x000000019593aa08 in start ()
Thread 2Queue : com.apple.libdispatch-manager (serial)

**Comment by arittr** [comment]
@lucaseverini so sorry about this issue - have you tried dropping back down to v2.8.0 to see if that fixes the problem? did you experience this issue with previous SDK versions? i would also make sure libMPCategoryHelpers.a is correctly linked, either via the -ObjC or -force-load ld flags.

**Comment by samgreen** [comment]
Closing stale issue. Please re-open if you're still experiencing this problem.

**Comment by vikingosegundo** [comment]
I see this issue. In 2.8.1 and 2.9.0
