### ISSUE TITLE
How to disable Mixpanel programmatically in a certain condition? 

### ISSUE THREAD

**Issue by xareelee** [mixpanel/mixpanel-iphone#277]
I want to disable Mixpanel programmatically in a certain condition. How to do that? and how to re-enable Mixpanel again?

**Comment by arittr** [comment]
@xareelee this can be one in several ways depending on what exactly you're trying to do. you could:

1) Use our A/B testing framework to define a boolean tweak which can be set from the UI. Wrap your .track and .people calls in a handler that only fires when the boolean is true. With this method you can turn tracking on/off from our UI, but the Mixpanel object will still be initialized.

2) Use APNs (or some other push / message framework) to send a bit of JSON from your servers to the client on startup (probably a boolean as well). Check the value on didFinishLaunchingWithOptions and only init the sharedInstance if the value is true. 

Each of these can be done in a variety of different ways, but I think in general this type of thing is the best way to selectively enable tracking.

**Comment by xareelee** [comment]
I need to disable Mixpanel when the user is in China. I've written a IP observer, and when the IP address is detected from China, the Mixpanel will be disabled. 

I can disable Google Analytics by setting `optOut`, but I'm not sure how to opt out Mixpanel temporary.

**Comment by arittr** [comment]
you can use .register to set "$ignore":true, which will force our servers to drop the event when it comes in. this won't prevent events from being flushed in the first place - to do that you'll need to suppress the .track calls or the Mixpanel singleton entirely. let me know if this helps!

**Comment by xareelee** [comment]
Hi @arittr, thanks for your reply. 

I'll try to solve this problem by aspect-oriented programming to make `-[Mixpanel sharedInstance]` return `nil` in the runtime to suppress the event tracking.

**Comment by arittr** [comment]
that sounds good - lmk if you run into any issues with this!

**Comment by samgreen** [comment]
Marking resolved.
