### ISSUE TITLE
Documentation is wrong for in-app notifications

### ISSUE THREAD

**Issue by samgreen** [mixpanel/mixpanel-iphone#289]
The docs here https://mixpanel.com/help/reference/ios-inapp-notifications

Mention surveys in the comments and repeatedly throughout this section.

**Comment by samgreen** [comment]
Paging @ryanseams, if you get a chance this would be hugely helpful.

**Comment by ryanseams** [comment]
Will take a look and remove all of the survey references

**Comment by samgreen** [comment]
My hero!

**Comment by ryanseams** [comment]
https://github.com/mixpanel/analytics/pull/4127 if you can merge now feel free, otherwise I will go through the official review for it

**Comment by samgreen** [comment]
Deploying now. Thanks @ryanseams for the PRQ.
