### ISSUE TITLE
Crash when calling `MPTweakBind` when using address sanitizer in iOS 9

### ISSUE THREAD

**Issue by srking** [mixpanel/mixpanel-iphone#293]
With address sanitizer enabled in iOS 9, a crash occurs when a call to `MPTweakBind` is made.

Steps to reproduce:

 1. Install Xcode 7 (issue found to be occurring when using beta 3).
 2. Enable address sanitiser (Open 'Product' ... 'Scheme' ... 'Edit scheme...', check 'Enable Address Sanitizer').
 3. Launch an app that makes a call to `MPTweakBind`.

Expected outcome: the app does not crash.
Actual outcome: the app crashes.

I have created a sample app to demo this issue: https://github.com/srking/turbo-wookie

**Comment by samgreen** [comment]
Awesome bug report. Will review it today. Thanks!

**Comment by samgreen** [comment]
@srking Sorry for the delay on this. Took me a while to get a hold of the Xcode beta. I was able to reproduce this issue (thanks to your sample project!) using Xcode 7 Beta 4. 

Unfortunately I think the address sanitizer may be confused by CocoaPods. I'm investigating the issue further, but the code it points to appears completely valid. Let's wait and see how it goes once XC7 is out of beta.

**Comment by samgreen** [comment]
Does not occur with Xcode 7.2.1

Looks like Apple may have fixed it?

**Comment by michalzelinka** [comment]
Still crashing for me:

![screen shot 2016-02-22 at 13 20 57](https://cloud.githubusercontent.com/assets/5228484/13218050/3448f3b2-d967-11e5-91a2-ac6250fb0ab9.png)

Works fine when suppressing all `MPTweakValue()` calls.

Xcode 7.2.1, Build platform iOS 9.2 Simulator.

**Comment by szigetics** [comment]
It is crashing for me as well using Xcode 9.0 + iOS 10 iPad Pro : 
<img width="1110" alt="screen shot 2017-10-27 at 12 57 30" src="https://user-images.githubusercontent.com/7099208/32100991-784ecacc-bb16-11e7-9e4b-e006a27fa0f7.png">
