### ISSUE TITLE
Problem of surveys for multiple users

### ISSUE THREAD

**Issue by Grubas7** [mixpanel/mixpanel-iphone#294]
There's few problem with SDK which block Mixpanel support for surveys multiple user.

Scenario:
1. Login as UserXX
2. Show survey
3. Answer
4. Logout
5. Login as UserYY
6. Show survey
-> Survey doesn't appear

The reason of problem are:
1. `decideResponseCached` and `shownSurveyCollections` are never reseted.
2. Lack of `-flushPeople` after user select the answer.

**Comment by samgreen** [comment]
Solid. Looks like an issue, thanks for the PR.
