### ISSUE TITLE
-[UIView mp_snapshotImage]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by ldiqual** [mixpanel/mixpanel-iphone#299]
Hey there,

I'm using the `Mixpanel` pod via segment.io's `Analytics` pod. So in my podfile I have this:
```
pod 'Analytics/Segmentio', '1.12.1'
pod 'Analytics/Mixpanel', '1.12.1' // Installs Mixpanel 2.8.1, not 2.8.2 (in case this matters)
```

Now when receiving an inapp notification, I get a crash on this line: https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L1393.

```
2015-07-21 16:34:06.167 App[65672:4250872] -[UIView mp_snapshotImage]: unrecognized selector sent to instance 0x7a862120
```

My guess is that `libMPCategoryHelpers.a` is not loaded correctly. I don't see any reference to this file in `Mixpanel.podspec`, is that on purpose? Is there a workaround to this issue?

**Comment by samgreen** [comment]
Hello @ldiqual, I'm so sorry that you're having trouble with the library. It seems to me that you need segment.io to update their subspec in the analytics pod to use Mixpanel 2.8.2.

We release 2.8.2 last week and this removes the `libMPCategoryHelpers.a` static library. Instead this code is now part of our main source repo. Alternatively you may be able to specify the version manually.

It may also be worthwhile to reach out to the segment.io folks and let them know the issue you're having. Hope that helps!

**Comment by ldiqual** [comment]
@samgreen Thanks for the quick response! I PR'd this change on the segment repo, waiting for them to update `master` and I'll get back to you as soon as I can test.

**Comment by samgreen** [comment]
Closing this issue.
