### ISSUE TITLE
Cannot build on Xcode7 Beta 2 with the latest Mixpanel SDK

### ISSUE THREAD

**Issue by kamoljan** [mixpanel/mixpanel-iphone#301]
<img width="255" alt="screen shot 2015-07-23 at 6 37 35 pm" src="https://cloud.githubusercontent.com/assets/228822/8848458/0efdbe8a-316a-11e5-9706-8059227ae397.png">

Any idea what I should do?

**Comment by kamoljan** [comment]
I have tried on version 2.6.* to 2.8.*
But still keep getting the shame error on Xcode7 Beta 2.

<img width="256" alt="screen shot 2015-07-24 at 6 06 15 pm" src="https://cloud.githubusercontent.com/assets/228822/8872473/e0ee7d56-322f-11e5-8f0d-b5152c4c7f76.png">

**Comment by samgreen** [comment]
Are you building for Carthage? This is a beta SDK so we haven't tried building for it yet.

That said, it should work fine. I'll take a look today and get back to you.

**Comment by samgreen** [comment]
I'm asking about Carthage because it looks like your attempting to build Mixpanel as a framework, not as a CocoaPod.

**Comment by samgreen** [comment]
@kamoljan I just built the pod successfully with Xcode 7 beta 4. No problems here. Perhaps you should try the latest beta?

**Comment by samgreen** [comment]
![image](https://cloud.githubusercontent.com/assets/276118/8886557/5d182c60-3221-11e5-8eda-1170a7580449.png)

**Comment by kamoljan** [comment]
It was my xcode7 beta 2 issue.
@samgreen thank you very much.
