### ISSUE TITLE
New Warnings Under Xcode 7 - Designated Initializer

### ISSUE THREAD

**Issue by colincornaby** [mixpanel/mixpanel-iphone#305]
In many places, it looks like Mixpanel adds an initializer but doesn't override the designated initializer. This is causing new warnings under Xcode 7 all over the place.

Example of warning:
/Users/ccornaby/discover-ios9/SDKs/Mixpanel/Mixpanel/MPPropertyDescription.m:54:17: Method override for the designated initializer of the superclass '-init' not found
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/usr/include/objc/NSObject.h:60:1: Method marked as designated initializer of the class here

I'm adding Mixpanel to my project as raw source, we don't use CocoaPods.

**Comment by samgreen** [comment]
Yeah, these were added automatically by Xcode when we updated the code base to Modern Objective-C. These should be removed.

**Comment by JetForMe** [comment]
Same here.
