### ISSUE TITLE
v2.8.2 does not include xcodeproj

### ISSUE THREAD

**Issue by schwa** [mixpanel/mixpanel-iphone#311]
Want to build mix panel with carthage build system - by default it grabs the latest tag (v2.8.2) I note 2.8.2 does NOT include a .xcodeproj file. Master branch does.

Suggest a release of a new tag that includes the xcodeproj?

**Comment by samgreen** [comment]
You're absolutely right. We shouldn't have updated the readme yet. Grab master for now. We'll push a new release this week. You have my word.

**Comment by schwa** [comment]
I see this hasn't happened yet. There hasn't been a release past 2.8.2. What's shaking?

**Comment by samgreen** [comment]
@schwa Doing final testing and release today.

**Comment by samgreen** [comment]
@schwa Release is out now.
