### ISSUE TITLE
Error building Xcode 7 Beta 4 due to MPSurvey.storyboard

### ISSUE THREAD

**Issue by ryanseams** [mixpanel/mixpanel-iphone#313]
Submitting on behalf of another user.

In Xocde 7 Beta 4 they are receiving an error when trying to build due to MPSurvey.storyboard.

It looks like lines 134 and 135 (below) are the culprit:
```<constraint firstItem="vot-vr-03f" firstAttribute="top" secondItem="yBe-16-sDN" secondAttribute="bottom" id="VHB-6i-oGx"/>```
```<constraint firstItem="yeI-nh-85p" firstAttribute="top" secondItem="0dH-sL-neW" secondAttribute="bottom" id="cWG-iv-oFU"/>```

"If I comment out these lines, the project builds correctly. My Xcode build is Version 7.0 beta 4 (7A165t). My deployment target is 6.0 and I'm building against iOS 9.0."

![image](https://cloud.githubusercontent.com/assets/9201737/9100767/44a01654-3b93-11e5-8845-a1399e8b2882.png)

**Comment by olivaresf** [comment]
Heya! I'm the user. Let me know if I can help.

**Comment by ccombes** [comment]
Xcode 7 Beta 5 crashes if I try to view MPSurvey.storyboard

**Comment by sclancy** [comment]
Also having same issue, cannot build for iOS9 beta. if I open the MPSurvey.storybaord it crashes Xcode could you please look into this?

**Comment by samgreen** [comment]
@sclancy @olivaresf Is this resolved with the final release?
