### ISSUE TITLE
Linking error with Mixpanel 2.8.4 via Cocoa Pods

### ISSUE THREAD

**Issue by yuvalwe** [mixpanel/mixpanel-iphone#318]
I tried upgrading to Mixpanel 2.8.2 through Cocoa Pods. After running 'pod install' I had the following linker issue:
`ld: library not found for -lMPCategoryHelpers`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Going back to version 2.7.4 fixes this issue. Any ideas?

**Comment by samgreen** [comment]
Have you tried running `pod update`?

**Comment by yuvalwe** [comment]
Yep.. still same problem

**Comment by samgreen** [comment]
One last thing, can you please try removing Mixpanel from the `Podfile`, running `pod install` then adding it back, and running `pod install` again. It seems like you are in a bad state, installing the pod in a fresh project works perfectly for me, and `pod update` from a previous version also works perfectly.

**Comment by samgreen** [comment]
Bump @yuvalwe

**Comment by yuvalwe** [comment]
@samgreen, sorry about that, not quite sure what was the issue, but i'm not experiencing it anymore. I think it might have been due to my attempt to use the 'use_frameworks' flag. Several pod installs somehow fixed the issue.

**Comment by samgreen** [comment]
No worries! Glad you got it resolved.

**Comment by DataGreed** [comment]
so should i use `use_frameworks!` or not?
