### ISSUE TITLE
No Shared Framework Schemes via Carthage Install

### ISSUE THREAD

**Issue by katoree** [mixpanel/mixpanel-iphone#319]
Keep getting the following when trying to build via Carthage

`Dependency "mixpanel-iphone" has no shared framework schemes`

`If you believe this to be an error, please file an issue with the maintainers at https://github.com/mixpanel/mixpanel-iphone/issues/new `

**Comment by simX** [comment]
It looks like Mixpanel 2.8.3 with Carthage support is not officially out yet.  You'll need to use the branch syntax in your cartfile until 2.8.3 is released, like so:

github "mixpanel/mixpanel-iphone" "master"

The following syntax is the release syntax, which looks in the official releases, which is only 2.8.2 so far.

github "mixpanel/mixpanel-iphone"

**Comment by samgreen** [comment]
@simX thanks for helping out on this one. We'll get a proper release out this week!

**Comment by samgreen** [comment]
@katoree @simX New release (2.8.3) is out.
