### ISSUE TITLE
Cannot run apps linking Mixpanel on iOS 7

### ISSUE THREAD

**Issue by bgulanowski** [mixpanel/mixpanel-iphone#320]
Mixpanel refers directly to UIKit class `UIAlertAction` that was only introduced in iOS 8. Code that uses this class is currently conditionally compiled, but needs to be conditionally executed at runtime and the class resolved indirectly using `NSClassFromString(@"UIAlertAction")`.

**Comment by samgreen** [comment]
Do you have an exception with more information? Mixpanel is currently being used in many apps that were linked against only the iOS 7 run times.

**Comment by bgulanowski** [comment]
If you _link_ against iOS 8 and _run_ on iOS 7 (which is very common), then dyld fails at launch, with undefined symbol. There is no exception.

**Comment by samgreen** [comment]
What build settings are leading you to this? I just tested with a Base SDK of iOS 8.4 and a deployment target of iOS 7. Runs on simulator and device without issue.

**Comment by bgulanowski** [comment]
We aren't doing anything unusual. I suspect it might be because we're linking to Mixpanel as a framework, which in turn linked to UIKit strongly instead of weakly.

Turns out the fix is to set the deployment target of Mixpanel framework to iOS 7. Fixed.

**Comment by bgulanowski** [comment]
I'm reopening this to request that you change the deployment target to 7.0, because that's what you actually support, and it's necessary to run on iOS 7.

**Comment by samgreen** [comment]
@bgulanowski I would love to get this resolved for you. What are you requesting we change? Do you want the deployment target on the sample code changed? The deployment target is managed by each developer for their project. Perhaps I'm missing something? 

Happy to review a PR today as well!

**Comment by bgulanowski** [comment]
The framework target in the Mixpanel project needs its deployment target changed.

**Comment by samgreen** [comment]
@bgulanowski Quick question that will help me clarify things. What method are you using to integrate Mixpanel? Cocoapods, Carthage, Manual?

**Comment by bgulanowski** [comment]
Git submodule and including mixpanel project in our workspace.

**Comment by samgreen** [comment]
Thanks for clarifying everything. This should be resolved with #322
