### ISSUE TITLE
Debugging and logging with MIXPANEL_DEBUG=1 does not work (v2.8.3 using Carthage)

### ISSUE THREAD

**Issue by alpennec** [mixpanel/mixpanel-iphone#324]
Hello,

I followed the instructions in the [Debugging and logging](https://mixpanel.com/help/reference/ios#debugging-and-logging) iOS API guides, but nothing is printed in my console. I have added the MIXPANEL_DEBUG=1 & MIXPANEL_ERROR=1. Also tried with MIXPANEL_LOG=1. I'm using Carthage with v2.8.3 (Xcode 6.4).

Thanks for your help,
Axel

**Comment by samgreen** [comment]
These macros must be added to the project before Carthage builds the framework.

**Comment by alpennec** [comment]
Can you explain me how I can do that please? Where should I put that? Should I write a custom runscript?

Thanks

**Comment by samgreen** [comment]
Hey @alpennec You will need to add these to the `Mixpanel.xcodeproj` that is found in `Carthage/Checkouts/Mixpanel/`
