### ISSUE TITLE
Ability to track app crashes

### ISSUE THREAD

**Issue by ViktorasJucikas** [mixpanel/mixpanel-iphone#33]
Folks, I would like to track  stack trace & exception reason in my main.m when the app crashes as a property of  "App Crashed" event + increment "Crashed" property in people.

However at that point none of the hooks to archive data get called and flush doesn't push data out because app quits right away.

What about making archive method public so that it could be called manually in this situation?

Thanks,
Viktoras

**Comment by AlejandroHCruz** [comment]
Hi everyone, I've been wondering if such crash-catching could be done with the mixpanel-android library. Has anyone experience on that? Thanks
