### ISSUE TITLE
Crash when fetching device model

### ISSUE THREAD

**Issue by ryanseams** [mixpanel/mixpanel-iphone#333]
Submitting this on behalf of a customer.

Currently their app is logging crashes when it accesses the line at https://github.com/mixpanel/mixpanel-iphone/blob/v2.6.2/Mixpanel/Mixpanel.m#L297 which can be found in the most recent release at https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L871. Since this pod is old the issue could have been resolved, but since the code has not changed I wanted to post this here.

Suggested fix by the customer is to handle this as an exception, but I might argue we simply ignore assignment of the property in this instance. Here is their fix:
```
- (NSString *)deviceModel 
{ 
size_t size; 
sysctlbyname("hw.machine", NULL, &size, NULL, 0); 
char answer[size]; 
@try { 
sysctlbyname("hw.machine", answer, &size, NULL, 0); 
NSString *results = @(answer); 
return results; 
} 
@catch (NSException *exception) { 
return @""; 
} 
}
```

Here is the stack trace:
0	
libsystem_platform.dylib 0x0000000197585a80 OSAtomicDequeue + 8 
1	
libsystem_malloc.dylib 0x000000019752d064 nano_malloc + 40 
2	
libsystem_malloc.dylib 0x000000019751d3e4 malloc_zone_malloc + 112 
3	
CoreFoundation 0x0000000184f96e08 _CFRuntimeCreateInstance + 372 
4	
CoreFoundation 0x0000000185083f28 __CFStringCreateImmutableFunnel3 + 2196 
5	
CoreFoundation 0x0000000184f9857c CFStringCreateWithBytes + 40 
6	
Foundation 0x0000000185eca6b8 -[NSPlaceholderString initWithBytes:length:encoding:] + 140
7	
Foundation 0x0000000185eca608 +[NSString stringWithUTF8String:] + 156 
8	
**Redacted** 0x00000001002e9c8c -[Mixpanel deviceModel] (Mixpanel.m:297) 
9	
**Redacted** 0x00000001002f5a94 -[MixpanelPeople collectAutomaticPeopleProperties] (Mixpanel.m:1745) 
10	
**Redacted** 0x00000001002f5904 -[MixpanelPeople initWithMixpanel:] (Mixpanel.m:1730) 
11	
**Redacted** 0x00000001002e8f88 -[Mixpanel initWithToken:launchOptions:andFlushInterval:] (Mixpanel.m:138) 
12	
**Redacted** 0x00000001002e8e1c __50+[Mixpanel sharedInstanceWithToken:launchOptions:]_block_invoke (Mixpanel.m:111) 
13	
libdispatch.dylib 0x00000001973ad954 _dispatch_client_callout + 12 
14	
libdispatch.dylib 0x00000001973ae82c dispatch_once_f + 92 
15	
**Redacted** 0x00000001002e8dc0 +[Mixpanel sharedInstanceWithToken:launchOptions:] (once.h:68) 
16	
**Redacted** 0x00000001003cb4cc -[MTAppDelegate trackAppOpen] (MTAppDelegate.m:392) 
17	
**Redacted** 0x00000001003c8df0 -[MTAppDelegate application:didFinishLaunchingWithOptions:] (MTAppDelegate.m:103) 
18	
**Redacted** 0x000000010010c714 -[DAAppDelegate application:didFinishLaunchingWithOptions:] (DAAppDelegate.m:48) 
19	
UIKit 0x0000000189ba7124 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 400 
20	
UIKit 0x0000000189dbe7e8 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 2372 
21	
UIKit 0x0000000189dc119c -[UIApplication _runWithMainScene:transitionContext:completion:] + 1500 
22	
UIKit 0x0000000189dbf70c -[UIApplication workspaceDidEndTransaction:] + 180 
23	
FrontBoardServices 0x000000018d8f93c8 __31-[FBSSerialQueue performAsync:]_block_invoke_2 + 28 
24	
CoreFoundation 0x000000018507427c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 16 
25	
CoreFoundation 0x0000000185073384 __CFRunLoopDoBlocks + 308 
26	
CoreFoundation 0x00000001850719a8 __CFRunLoopRun + 1752

**Comment by Coeur** [comment]
According to the log, it is not `sysctlbyname()` which is throwing, but `@(answer)`. In fact, `sysctlbyname()` cannot throw.

A simple check on `size != 0` would be better than the try-catch.

**Comment by patedit** [comment]
You are totally right, @Coeur . Thanks for the PR :)
