### ISSUE TITLE
Carthage and survey: mp_snapshotImage crash

### ISSUE THREAD

**Issue by alpennec** [mixpanel/mixpanel-iphone#335]
Hello,
I'm using mixpanel.showSurvey() but getting a crash

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UILayoutContainerView mp_snapshotImage]: unrecognized selector sent to instance 0x7f91db798fd0'`

I use Carthage to add the framework ("v2.8.3") in my app.

Regards,
Axel

**Comment by thbaja** [comment]
:+1: 
I get it when sending in-app message, also using carthage and version 2.8.3

**Comment by samgreen** [comment]
This will be resolved in the next release.

**Comment by samgreen** [comment]
This is resolved in v2.9.0. Thanks!

**Comment by alpennec** [comment]
Thanks for the fix.

I want to manually trigger the appearance of the survey.
I created a survey online, and I target all my users.
I then call in my app: 

let mixpanel = Mixpanel.sharedInstance()
mixpanel.showSurvey()

But nothing happens in my app.
