### ISSUE TITLE
Carthage: Invalid Deployment Target

### ISSUE THREAD

**Issue by flovilmart** [mixpanel/mixpanel-iphone#336]
The deployment target is invalid for App Store submission as it is set to 6.0. 

The builds work properly while using them in the context of development, simulator and ad-hoc but the app store uploader rejects the host app.

**Comment by smweber** [comment]
+1 I'm seeing this too. Any updates on this issue? I'm new to Carthage - is there a way to force the deployment target to 8.0 specifically for Carthage builds?

**Comment by samgreen** [comment]
Hi guys, we have a released planned and we want to get it out to you as soon as possible. In the meantime things should work perfectly if you specify the master branch if your Cartfile for Mixpanel. Please let me know if you're still having issues or if this resolves things for you.

**Comment by smweber** [comment]
Actually just thought to try master an hour ago, and it seems to clear things up. Thanks!

**Comment by schickling** [comment]
Master branch works. Eta for next release including this change?

**Comment by samgreen** [comment]
We don't like to give timelines for releases in case we get held up. If everything goes well we should be pushing a release this week.

**Comment by schickling** [comment]
Great!

**Comment by samgreen** [comment]
This is resolved in v2.9.0. Thanks!
