### ISSUE TITLE
MPCategoryHelpers.h exists but there is no implementation

### ISSUE THREAD

**Issue by welshm** [mixpanel/mixpanel-iphone#339]
The library was removed at some point, so there's no linked filed which actually implement the declared methods.

Unless I'm missing something, this will certainly crashed if any of those methods are called.

**Comment by samgreen** [comment]
These are *all* implemented in UIView+MPHelpers.m

You can see the implementation here: https://github.com/mixpanel/mixpanel-iphone/blob/3a2b5531260c8cd3b1a3c9de0ee7bdb2981e2f65/Mixpanel/UIView%2BMPHelpers.m
