### ISSUE TITLE
iOS 9 App Transport Security server settings

### ISSUE THREAD

**Issue by ichibod** [mixpanel/mixpanel-iphone#341]
Any suggestions for the settings to allow Mixpanel to support ATS? I simply whitelisted mixpanel.com.

**Comment by mixpanel-travisci** [comment]
In my testing with the beta it worked with no changes. Are you getting an
exception? Console output would be helpful.

**Comment by ichibod** [comment]
I turned it off, looks like you are correct. Just double checking before submission :point_up: Thanks!

**Comment by samgreen** [comment]
No problem. Happy to help!
