### ISSUE TITLE
XCode not compile

### ISSUE THREAD

**Issue by gali8** [mixpanel/mixpanel-iphone#347]
I tried all installations types:
- cocoapods
- project in project
- manual library
- frameworks

But always XCode (6.4) freeze during the build phase.

**Comment by samgreen** [comment]
Are you using Alcatraz? Working fine here on 6.4, and this is the first report we've received. You could also update to Xcode 7.

**Comment by gali8** [comment]
Not I'm not using Alcatraz. Unfortunately I can't update to XCode 7 because I have many frameworks that are not supported by Swift 2.0.

Any help?

**Comment by samgreen** [comment]
@gali8 Are you still having issues compiling?
