### ISSUE TITLE
Changing Variants in A/B Test Causing Crash

### ISSUE THREAD

**Issue by ryanseams** [mixpanel/mixpanel-iphone#348]
I have a A/B test which I created within Mixpanel. To create my test, I start by creating a new variant and editing a text element. When I create the next new variant, Mixpanel is automatically persisting the change from the first variant into my second variant.

As I do not want each variant to depend on one another and be independent, I first clear the second variant of all changes from the first, and then make a change on the same text element. On my third variant I do the same as the second -- clear all prior changes and then make edits on the same text element.

At this point I have an original and three variants, where each variant has only one change made on the same UI text element.

When I apply this to a device or browse a single variant, there are no issues as a single variant has no problems. However, when I switch from one of the variants to the other -- either through the UI when viewing the variants in the test or by re-configuring the variants percentages to my user's devices -- my app is crashing as the changes to the same element are causing a conflict.

While I can avoid this crash by leaving prior variant changes layered within my test or simply by not changing the variant percentage allocation, this crash seems dependent on the way I create an A/B test. The way I create a test should not cause a crash, and if it does, it should be known ahead of time so I avoid creating a test in this manner.

The code is breaking on [this line](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/MPVariant.m#L559).

Here is the trace:
![image](https://cloud.githubusercontent.com/assets/9201737/10030939/2b1691a6-612f-11e5-97f0-733c07d14cf7.png)

In case it's needed here is a video recreating the whole crash:
https://www.dropbox.com/s/geqvswlvv6jd8f8/AB_testing_crash.mov?dl=0

**Comment by samgreen** [comment]
Resolved in #443
