### ISSUE TITLE
In-App Notifications violate App Transport Security (ATS)

### ISSUE THREAD

**Issue by fluidsonic** [mixpanel/mixpanel-iphone#349]
App Transport Security (ATS) forbids non-encrypted HTTP connections in iOS 9 - i.e. it requires the use of HTTPS.
However Mixpanel is still using HTTP for some resources.

This results in the following error:
> Transport security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.

Cause by an image loaded for an in-app notification:
http://images.mxpnl.com/382369/934f73146ab9770a79a3175aadf0eb33.jpg

Temporary workaround is to disable ATS for `mxpnl.com` in `Info.plist`:
```xml
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSExceptionDomains</key>
	<dict>
		<key>mxpnl.com</key>
		<dict>
			<key>NSExceptionAllowsInsecureHTTPLoads</key>
			<true/>
			<key>NSExceptionRequiresForwardSecrecy</key>
			<false/>
			<key>NSIncludesSubdomains</key>
			<true/>
		</dict>
	</dict>
</dict>
```

**Comment by samgreen** [comment]
Hey @fluidsonic thanks for the update. We're investigating now. Can you tell me where this URL came from? An in-app notification perhaps?

**Comment by fluidsonic** [comment]
@samgreen Exactly.

**Comment by vandutran** [comment]
+1 having the exact same issue. This worked:

<img width="476" alt="screen shot 2015-10-16 at 11 11 22 am" src="https://cloud.githubusercontent.com/assets/4130142/10545714/21332bf0-73f8-11e5-8263-7c8e5f7292a6.png">

**Comment by samgreen** [comment]
We're waiting on the CDN to update their SSL cert.

**Comment by samgreen** [comment]
This is now resolved @vandutran @fluidsonic

**Comment by vandutran** [comment]
So does this mean we can remove the whole "mxpnl.com" entry?

**Comment by samgreen** [comment]
Yes. @vandutran
