### ISSUE TITLE
Document URLs for App Transport Security

### ISSUE THREAD

**Issue by kevboh** [mixpanel/mixpanel-iphone#351]
Can you include domains and permissions in the README to whitelist for App Transport Security, similar to what Facebook has done at https://developers.facebook.com/docs/ios/ios9#whitelist?

**Comment by yas375** [comment]
+1 on this

**Comment by vandutran** [comment]
I'm having issues with in-app notifications, seems to be related to this.

**Comment by samgreen** [comment]
Sorry about this guys, we're waiting on the CDN to update their SSL.

**Comment by samgreen** [comment]
In the meantime please use the work around in #349.

Please don't disable ATS all together.

**Comment by samgreen** [comment]
This has been resolved on the backend.
