### ISSUE TITLE
Warnings in XCode 7, Swift 2.0, installed with Pod

### ISSUE THREAD

**Issue by ded** [mixpanel/mixpanel-iphone#352]
Hi there,
I'm building an app with Swift 2.0 using Cocoapods via `use_frameworks!`, `pod Mixpanel`, targeting iOS 8.4, running on Xcode 7.

I've managed to get all my other dependencies upgraded to the appropriate `swift-2.0` branches, eliminating all warnings. At this point Mixpanel is of the last still throwing warnings that I'm unable to silence.

Any clue as to what I can do about this?

![image](https://cloud.githubusercontent.com/assets/372683/10236365/7a3529a6-6859-11e5-940f-fe12addfdfac.png)

**Comment by Paul-van-Klaveren** [comment]
already fixed in `master`; replacing the `NSUInteger` with `UIInterfaceOrientationMask` silenced the warning.

**Comment by ded** [comment]
thanks!
