### ISSUE TITLE
Notify delegate when a notification was presented

### ISSUE THREAD

**Issue by yas375** [mixpanel/mixpanel-iphone#353]
In our app we'd like to limit frequency of how often we can show Mixpanel's notification to the user. We'd like to keep track when a notification (takeover notification) has been presented the last time. Depending on it we are going to call `Mixpanel#showNotification` less frequently.

In order to do this we need to know when a notification when actually presented the last time. Looking into the source I see that we can add a method to `MixpanelDelegate` and then notify the delegate from `Mixpanel#showNotificationWithObject:` when needed.

Does it make sense for you? Would you be interested in having a pull request with this? Or maybe do you have something similar in plans or already working on it?

Thanks in advance!

**Comment by samgreen** [comment]
Would be interested in a PR for this @yas375

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features, please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation. Sorry for the inconvenience.
