### ISSUE TITLE
How to handle with "createAlias" for crossplatform app

### ISSUE THREAD

**Issue by loryhuz** [mixpanel/mixpanel-iphone#355]
In the documentation you always refer to "Signup phase" when speaking about createAlias.
But how to handle this thing if the app is cross-platform (Desktop, Webapp, Android, iOS in my case). In fact I've already a lot of users who are already registered when they download the app, and the login is skippable so it's doesn't merge datas when I identify after they logged in since I doesn't use createAlias yet.

**Comment by ryanseams** [comment]
hi @loryhuz thanks for writing in about this!

the best practice here is to call createAlias when a user initially signs up, and then call identify with the value used for the alias on all future app opens (typically done in didFinishLaunchingWithOptions).

provided you know who a user is on the new platform -- by some id -- you can simply call identify with the alias on app open and the user will be linked to other platforms. if you do not know who the user is, and they do not need to authenticate, things do get tricky -- is there anything you know on your end we can tag this user by to be able to correct link their account across platforms?

there is more info on this [here](https://mixpanel.com/blog/2015/09/21/community-tip-maintaining-user-identity) and if you let me know your specific scenario i am happy to help further!

**Comment by loryhuz** [comment]
"if you do not know who the user is, and they do not need to authenticate, things do get tricky"

In fact this is the case, login is skippable and you only need to login when you want to validate your cart (e-commerce app). So without creating alias we lost user data before the cart validation if it was considered as an anonymous.

"is there anything you know on your end we can tag this user by to be able to correct link their account across platforms?"

When you are logged in we have a userId returned by our webservice but it doesn't resolve (I think) our main problem (merging data between the anonymous and the logged user, both are the same person) that createAlias can be used only once.

**Comment by ryanseams** [comment]
hi @loryhuz -- given your scenario, there are a few options here to keep your data consistent for these users:
1. keep separate profiles for users on the different platforms
2. hold off on sending events from the client side until a user signs in so you can correct their distinct id
3. utilize a hybrid server-client implementation to ensure id stays consistent pre-login

ultimately the choice you make here really depends on your scenario -- for ex, if most users sign up on iOS without a web account anyways then this may be an edge case you address specially. mind emailing support@mixpanel.com and we can discuss a solution tailored to your scenario in detail?
