### ISSUE TITLE
Cocoa Pods 2.8.3

### ISSUE THREAD

**Issue by zveljkovic** [mixpanel/mixpanel-iphone#356]
Cocoa Pods isn't pulling latest fixes for XCode 7 / iOS 9. Warnings are issued in MPNotificationViewController.m

....
- (NSUInteger)supportedInterfaceOrientations
{
    return UIInterfaceOrientationMaskPortrait;
}

....

**Comment by Blahartinger** [comment]
This is a dupe. See https://github.com/mixpanel/mixpanel-iphone/issues/352

**Comment by Blahartinger** [comment]
Somewhere on here I had read earlier this week that Mixpanel was looking to drop a new build later this week...however, today being Friday I'm now doubtful and sad. :(

**Comment by Blahartinger** [comment]
Here is where a new release was mentioned for last week https://github.com/mixpanel/mixpanel-iphone/issues/229
