### ISSUE TITLE
poeple properties "SurveysReceived"  and "Responses"has default value 30565 and 28273

### ISSUE THREAD

**Issue by sharjeelnisar1** [mixpanel/mixpanel-iphone#357]
These properties don't appear in all users, only appearsin two of my users and display such a large value for new user
![img_6260](https://cloud.githubusercontent.com/assets/5243688/10409838/6cfe256c-6f48-11e5-9e3a-b2650c777f5d.JPG)

**Comment by ryanseams** [comment]
hi @sharjeelnisar1 thanks for writing in!

the numbers you are actually viewing here are the survey id and response group id for the user -- this is not the number of times the user has seen the survey or the number of responses they have provided.

if the user was sent another survey, you would also see the id for this survey and response group here. these properties are lists which will be appended to each time a new survey is shown to the user.

you can verify these are the survey id and response group id by going to the surveys tab and looking at the numbers which show in the URL within Mixpanel.
