### ISSUE TITLE
UIView+MPHelpers.m missing from the framework

### ISSUE THREAD

**Issue by kballard** [mixpanel/mixpanel-iphone#358]
The repository has a file named `UIView+MPHelpers.m`, but it's not in the Xcode project and therefore not compiled as part of the framework. It seems this file is what provides the implementations of the 3 methods declared in `MPCategoryHelpers.h`:

```objc
@interface UIView (MPHelpers)

- (UIImage *)mp_snapshotImage;
- (UIImage *)mp_snapshotForBlur;
- (int)mp_fingerprintVersion;

@end
```

So the lack of this `UIView+MPHelpers.m` means these methods will crash when they're called. I don't know under what circumstances they will be called, but I searched the project and there's 2 invocations of `mp_snapshotImage` (I didn't check the other 2 methods).

**Comment by samgreen** [comment]
Do you have a crash log?

**Comment by kballard** [comment]
I didn't crash, my coworker did. I'll see if he has one.

**Comment by samgreen** [comment]
The file is in the repo and the project.

**Comment by kballard** [comment]
No it's not. Are you verifying with CocoaPods? Because that doesn't use the project. Using a fresh checkout of the latest `master`, the `Mixpanel.xcodeproj` project does not contain the `UIView+MPHelpers.m` file.

**Comment by kballard** [comment]
(this problem arose when using mixpanel via Carthage, which builds the xcodeproj, unlike CocoaPods which uses a different way of specifying the source)

**Comment by kballard** [comment]
Coworker says he doesn't have a crash log either, he hit the issue with the debugger attached (so no crash log was generated). The workaround we went with was to literally copy `UIView+MPHelpers.m` into our own project, which fixed the crash.

**Comment by samgreen** [comment]
What version of the SDK are you using?

**Comment by kballard** [comment]
The tip of `master`. Our `Cartfile` is just specifying `github "mixpanel/mixpanel-iphone"` (we're relying on the `Cartfile.resolved` to avoid accidental update breakage), and I confirmed by checking out a fresh copy of the repository.

**Comment by kballard** [comment]
@samgreen Any update on this? Can you at least reopen the ticket? The tip of `master` is definitely broken in regards to this file not being in the project.

**Comment by samgreen** [comment]
Sure thing, we'll verify this through carthage

**Comment by ekimia** [comment]
thank you!

**Comment by david6p2** [comment]
It seems I'm having the same issue. I update from mixpanel 2.8.1 to 2.8.3 because of the BitCode Support issue and now I have this new issue. It appears that MPCategoryHelpers was removed from 2.8.3

![captura de pantalla 2015-10-16 a las 5 18 10 p m](https://cloud.githubusercontent.com/assets/1909725/10554553/05b01406-742a-11e5-94fd-52f51bf39348.png)
![captura de pantalla 2015-10-16 a las 5 18 24 p m](https://cloud.githubusercontent.com/assets/1909725/10554554/08740468-742a-11e5-9ead-d6e90032438c.png)

**Comment by samgreen** [comment]
@david6p2 This is a separate issue. It appears you need to run `pod update Mixpanel`

**Comment by samgreen** [comment]
@kballard I'm so sorry for the confusion. You are absolutely correct and I have resolved the issue locally. We will get a release out ASAP.

Again so sorry for the misunderstanding, I was looking in the wrong place, thanks again for your patience.

**Comment by kballard** [comment]
Glad to hear it!

**Comment by samgreen** [comment]
This is resolved in v2.9.0. Thanks!

**Comment by david6p2** [comment]
@samgreen I think is the same error. I already did a `pod update Mixpanel` and it update to 2.9.0 but I keep seeing in the Podfile.lock that Mixpanel/MPCategoryHelpers were removed from version 2.8.2 and above. 

```
-  - Mixpanel (2.8.1):
-    - Mixpanel/Mixpanel (= 2.8.1)
-  - Mixpanel/Mixpanel (2.8.1):
-    - Mixpanel/MPCategoryHelpers
-  - Mixpanel/MPCategoryHelpers (2.8.1)
+  - Mixpanel (2.9.0):
+    - Mixpanel/Mixpanel (= 2.9.0)
+  - Mixpanel/Mixpanel (2.9.0)

```

And the project won't compile when I try to run it on my device trowing this error 

    ld: library not found for -lMPCategoryHelpers
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

If I run it on the simulator it runs fine.

**Comment by kballard** [comment]
@david6p2 The podspec was modified back [in July](https://github.com/mixpanel/mixpanel-iphone/commit/af67a4a0aaeee83dfa30599348f063651b2f24b6) to remove the `MPCategoryHelpers` subspec and stop depending on it. This change was in 2.8.2, and is completely unrelated to this ticket here. You should try ⌘⌥⇧K to Clean Build Folder. Beyond that, if you're still having a problem, open a new ticket.

**Comment by samgreen** [comment]
@kballard is correct with this advice.

@david6p2 In addition to cleaning, I would suggest temporarily removing Mixpanel from your podfile, performing a `pod install`, then re-adding and performing another `pod install`.

**Comment by kballard** [comment]
Or just run `git clean -xfd` to completely clear your working directory of all untracked files (which, presumably, should include the workspace that cocoapods is generating) and then re-running `pod install`.

**Comment by david6p2** [comment]
Thanks @kballard and @samgreen. You were correct. It was some weird problem with my Linker flags. I have to remove all my pods, erase the linker flags to them, git clean -xfd and then reinstall all the pods again. Sorry
