### ISSUE TITLE
Some warnings with Xcode 7 and iOS 9 UIViews+MPHelpers.m MPNotificationsViewController.m

### ISSUE THREAD

**Issue by vandutran** [mixpanel/mixpanel-iphone#359]
Two warnings:
UIViews+MPHelpers.m
MPNotificationsViewController.m

<img width="418" alt="screen shot 2015-10-13 at 10 44 16 am" src="https://cloud.githubusercontent.com/assets/4130142/10458225/d3f4a0ba-7197-11e5-9e5b-23749cebb619.png">

**Comment by samgreen** [comment]
This is resolved in v2.9.0. Thanks!
