### ISSUE TITLE
Error uploading to App Store - ITMS-90209 

### ISSUE THREAD

**Issue by iagomr** [mixpanel/mixpanel-iphone#360]
Hey,

I just installed Mixpanel and I get 2 errors, one is related with the minimum OS version stated in Mixpanel which is too low (6.0) and the other one is the following:

ERROR ITMS-90209: "Invalid segment alignment. The app binary at (...)/Frameworks/Mixpanel.framework/Mixpanel does not have proper segment alignment. Try rebuilding the app with the latest Xcode version"

I do have the latest Xcode version 7A1001. Can you pinpoint what's the fix or is there any issue on your side?

Cheers,
Tiago

**Comment by iagomr** [comment]
I also get these bunch of errors while building with Carthage:

/Users/xyz/Carthage/Checkouts/mixpanel-iphone/Mixpanel/MPNotificationViewController.m:150:1: warning: conflicting return type in implementation of 'supportedInterfaceOrientations': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned int') [-Wmismatched-return-types]
/Users/xyz/Carthage/Checkouts/mixpanel-iphone/Mixpanel/MPNotificationViewController.m:150:1: warning: conflicting return type in implementation of 'supportedInterfaceOrientations': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned long') [-Wmismatched-return-types]
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
/Users/xyz/Carthage/Checkouts/mixpanel-iphone/Mixpanel/MPNotificationViewController.m:150:1: warning: conflicting return type in implementation of 'supportedInterfaceOrientations': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned int') [-Wmismatched-return-types]
/Users/xyz/Carthage/Checkouts/mixpanel-iphone/Mixpanel/MPNotificationViewController.m:150:1: warning: conflicting return type in implementation of 'supportedInterfaceOrientations': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned long') [-Wmismatched-return-types]
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later

**Comment by thbaja** [comment]
:+1:  also here

**Comment by iagomr** [comment]
To circumvent, I'm using segment.io to send events to Mixpanel, and this works fine.

**Comment by thbaja** [comment]
Thanks for the tip @iagomr. 
But an easier fix is to let carthage point to "master".

It seems to be due to Deployment Target set to 6.0 in the framework scheme in the "v2.8.3" release.

**Comment by samgreen** [comment]
This is resolved in v2.9.0. Thanks!

**Comment by Allan-Nava** [comment]
I have this problem when I i try to upload the Archive Release.
> ERROR ITMS-90087: "Unsupported Architectures. The executable for Sportube.app/Frameworks/GoogleCast.framework contains unsupported architectures '[x86_64, i386]'."

I use this script:
```
APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

# This script loops through the frameworks embedded in the application and
# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
    FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
    FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
    echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

    EXTRACTED_ARCHS=()

    for ARCH in $ARCHS
    do
        echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
        lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
        EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
    done

    echo "Merging extracted architectures: ${ARCHS}"
    lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
    rm "${EXTRACTED_ARCHS[@]}"

    echo "Replacing original executable with thinned version"
    rm "$FRAMEWORK_EXECUTABLE_PATH"
    mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done
```

I use ionic cordova build ios --release and it works "build succeeded", but when I try to upload to app store I have this problem:
> ERROR ITMS-90087: "Unsupported Architectures. The executable for Sportube.app/Frameworks/GoogleCast.framework contains unsupported architectures '[x86_64, i386]'."

**Comment by pchien** [comment]
@Allan-Nava sorry for the late response, I was out for a while. It looks like your issue is with GoogleCast, not Mixpanel. Off the top of my head, x86_64 is for a simulator, and I think i386 might also be for a simulator. Perhaps you want to submit to the app store with a different build scheme than you test on so you can remove the simulator architectures.
