### ISSUE TITLE
Question about swizzling table view

### ISSUE THREAD

**Issue by jcavar** [mixpanel/mixpanel-iphone#361]
Hi there,
We are fighting leak which seems to be related to Mixpanel. We investigated it and here is what we found:

In `MPUITableViewBinding`'s execute method, block is passed to `MPSwizzler swizzleSelector`
Now, that block captures `rootViewController` which creates retain cycle. We can easily fix that by marking it `__weak` but I am not sure if we should do that. I expected that binding is going to be released manually(by calling `stop` method) from somewhere but this isn't the case.

Our app has this kind of flow:

On launch we set `LoginViewController` as `window.rootViewController`
After user is logged in we set `TableViewController` as `window.rootViewController`
After user logs out we again set `LoginViewController` as `window.rootViewController`

What I would expect is that binding is created when `TableViewController` is set as root and binding is released when user logs out(so when TableViewController should be released - it isn't currently because of described problem).

Can you please elaborate on how and when bindings are created and when they are(should be) released?

**Comment by jcavar** [comment]
After more investigation:
Moving 
`NSObject *root = [[UIApplication sharedApplication] keyWindow].rootViewController;` 
inside block fixes retain cycle and seems right thing to do? We want current `rootViewController` when user taps on table view row and call `isLeafSelected` on it.

**Comment by samgreen** [comment]
This will be resolved in the next release.

**Comment by samgreen** [comment]
This is resolved in v2.9.0. Thanks!

**Comment by jcavar** [comment]
Cool, thanks!
