### ISSUE TITLE
EXC_BAD_ACCESS on line 111 of UIView+MPHelpers.m on "object_getIvar(responder, ivar) == self".  

### ISSUE THREAD

**Issue by cerupcat** [mixpanel/mixpanel-iphone#362]
When using the A/B testing feature, I'm getting a crash on line 111 of UIView+MPHelpers.m on "object_getIvar(responder, ivar) == self".  

I've tried casting object_getIvar to the object type, but that doesn't seem to help (or I'm doing it wrong).

**Comment by samgreen** [comment]
What integration method are you using?

**Comment by cerupcat** [comment]
We're using cocoapods. Is that what you're asking?

**Comment by samgreen** [comment]
Thanks for the quick reply. Can you give me a bit more context or a simple way to reproduce? Would love to get this resolved.

**Comment by cerupcat** [comment]
Hi @samgreen, I've been communicating with Jared McFarland and have sent him some more information on this with attachments. Can you let me know if that works or whether I should post more here. Thanks!

**Comment by samgreen** [comment]
I'll sync up with Jared and get back to you ASAP

**Comment by cerupcat** [comment]
Hi @samgreen, I know we didn't follow up on this, but I wanted to check if this is closed because it was fixed or simply because we didn't follow up? We know it's still an issue on our app, but haven't had a chance to look deeper into it since it's tough to narrow down.

**Comment by samgreen** [comment]
Hi @cerupcat This should be resolved in v2.9.3. Can you upgrade the library and confirm that it is resolved?

**Comment by cerupcat** [comment]
I'll give it a try tomorrow and let you know if it's still an issue. Thanks!
