### ISSUE TITLE
Changelog not updated

### ISSUE THREAD

**Issue by codywinton** [mixpanel/mixpanel-iphone#365]
Version 2.9.0 was just recently released, however the Changelog was not updated to list the features/bug fixes with this release.

**Comment by samgreen** [comment]
What change log are you referring to?

Release notes were posted here: https://github.com/mixpanel/mixpanel-iphone/releases/tag/v2.9.0

**Comment by codywinton** [comment]
https://github.com/mixpanel/mixpanel-iphone/blob/master/CHANGES

**Comment by samgreen** [comment]
Please refer to the GitHub releases for changelog info.
