### ISSUE TITLE
Xcode 7.1 warning - umbrella header

### ISSUE THREAD

**Issue by soleares** [mixpanel/mixpanel-iphone#372]
Xcode 7.1 shows the following warning when installed via CocoaPods:

```
Umbrella header for module 'Mixpanel' does not include header 'MPCategoryHelpers.h'
```

See this discussion for more details:
https://github.com/CocoaPods/CocoaPods/issues/4420

I think the solution involves creating a custom module.modulemap and including the header in it.

**Comment by samgreen** [comment]
Thanks for opening the issue, and linking to documentation. We'll definitely add a modulemap in the next release.

**Comment by samgreen** [comment]
Is this in Objective-C or Swift?

**Comment by samgreen** [comment]
Not receiving this in Swift or ObjC with Xcode 7.2, closing this issue as stale.

**Comment by obuseme** [comment]
I'm getting this warning on my Jenkins slave.  It uses xcodebuild (with Xcode 7.3) to compile the app on the command line.  I used CocoaPods to install Mixpanel 2.9.4.
