### ISSUE TITLE
iOS 9 deprecated API warnings

### ISSUE THREAD

**Issue by jbardini** [mixpanel/mixpanel-iphone#376]
Builds with Xcode 7.x report the following deprecated API warnings:
* CFURLCreateStringByAddingPercentEscapes
* NSURLConnection sendSynchronousRequest:returningResponse:error:
* UIAlertView
* NSString stringByAddingPercentEscapesUsingEncoding:
* NSURL initWithScheme:host:path:

**Comment by yoeriboven** [comment]
I got the same warnings. Are they safe to ignore, Mixpanel?

**Comment by samgreen** [comment]
They are safe to ignore and will be resolved in the next release.

**Comment by jbardini** [comment]
Thanks for the feedback @samgreen!

Do you have an ETA for next release?

**Comment by samgreen** [comment]
No ETA, but we're working on it now and we'll get it out as soon as it passes final testing.

**Comment by twobitlabs** [comment]
Any word on this? Seems to keep getting pushed out? We keep our projects warning-free, and Mixpanel is the only library we're running at this point that still has deprecation warnings.

**Comment by byronrode** [comment]
Same as @twobitlabs above.

Changing alert view is fairly easy do.

**Comment by samgreen** [comment]
Sorry for the churn on this. Unfortunately higher priority issues like crashes and problems integrating will always take priority. This will definitely be resolved before the deprecated APIs disappear with iOS 10. 

Also there is an option to suppress warnings in a Podfile if you're using CocoaPods. I highly recommend this as you shouldn't have to worry about maintenance for your dependencies. 

As always, pull requests are happily accepted!

**Comment by twobitlabs** [comment]
We prefer not to use cocoapods. For now, we've chosen to [suppress the warnings with pragmas](https://github.com/twobitlabs/mixpanel-iphone/tree/suppress-warnings).

**Comment by samgreen** [comment]
@twobitlabs thanks for the feedback. I hate that we're forcing you guys to use pragmas, I'll make sure this takes priority.

For my own research, I would be really interested in learning why you have made the decision not to use a dependency manager. Would you mind sharing your insight in to that?

**Comment by byronrode** [comment]
Thanks Sam. Will suppress with CocoaPods in the mean time.

**Comment by twobitlabs** [comment]
@samgreen we feel like submodules are easier to manage over the long term. http://twobitlabs.com/2013/12/not-cuckoo-for-cocoapods/

**Comment by samgreen** [comment]
This is resolved in v3.0.0

Thanks for your patience.
