### ISSUE TITLE
Category names collide with SRWebSocket categories

### ISSUE THREAD

**Issue by jder** [mixpanel/mixpanel-iphone#378]
If you use both Mixpanel and SRWebSocket in a project, the following categories are defined by both projects and so produce warnings (in Xcode 7.1, at least):

    NSURLRequest (CertificateAdditions)
    NSMutableURLRequest (CertificateAdditions)

They don't actually define any colliding method names (since the methods themselves are prefixed SR_ and mp_) so I'm not sure what the runtime consequences are for this. Even if harmless, it would be nice to resolve the warning.

Can they be changed to, e.g., MPCertificateAdditions?

**Comment by samgreen** [comment]
Thanks, we'll get this changed in the next release.

**Comment by samgreen** [comment]
Resolved in #402
