### ISSUE TITLE
Submitting SDK 9.1 builds to itunes fails on CFBundleExecutable

### ISSUE THREAD

**Issue by Voxar** [mixpanel/mixpanel-iphone#379]
ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/Application.app/MixpanelResources.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

**Comment by samgreen** [comment]
Are you using Carthage or Cocoapods?

**Comment by samgreen** [comment]
Resolved in #417

**Comment by samgreen** [comment]
This is now released as v2.9.2, thanks for your patience!
