### ISSUE TITLE
sub spec issue - duplicate symbols

### ISSUE THREAD

**Issue by idomizrachi** [mixpanel/mixpanel-iphone#382]
Hi
I have an app that use Mixpanel for both the mobile app and the share extension.
I found that if the app contains both pods:
```
  pod 'Mixpanel', '2.9.0'
  pod 'Mixpanel/AppExtension', '2.9.0'
```
* This caused from a local pod with shared code for the App and the Share Extension

The project build fails with the following error:
```
duplicate symbol _MP_NewBase64Decode in:
    /Users/ido.mizrachi/Library/Developer/Xcode/DerivedData/TestMixpanel-eskzlbuzaelvagbnfkeppnxborde/Build/Products/Debug-iphonesimulator/libPods-TestMixpanel-Mixpanel.a(NSData+MPBase64-8960067CD7E31586.o)
duplicate symbol _MP_NewBase64Encode in:
    /Users/ido.mizrachi/Library/Developer/Xcode/DerivedData/TestMixpanel-eskzlbuzaelvagbnfkeppnxborde/Build/Products/Debug-iphonesimulator/libPods-TestMixpanel-Mixpanel.a(NSData+MPBase64-8960067CD7E31586.o)
ld: 2 duplicate symbols for architecture x86_64
```
I found an issue with the podspec and pushed the fix to my repository:
https://github.com/idomizrachi/Specs/blob/master/Mixpanel/2.9.0/Mixpanel.podspec.json

You can see the issue in this sample project: https://www.dropbox.com/s/86s8po04ea1o82q/TestMixpanel.zip?dl=0
* Uncomment source 'https://github.com/idomizrachi/Specs.git' and run 'pod update Mixpanel'

<img width="878" alt="screen shot 2015-11-15 at 10 25 56 pm" src="https://cloud.githubusercontent.com/assets/2949351/11170814/411e4a64-8be8-11e5-9c41-718e4b382539.png">
![screen shot 2015-11-15 at 10 25 38 pm](https://cloud.githubusercontent.com/assets/2949351/11170813/3d677daa-8be8-11e5-9557-8a2950e9e8c8.png)

**Comment by samgreen** [comment]
Seems like you could just add the AppExtension to the ShareExtension target. Not sure why you would need both in any given target.
