### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by zjszyms** [mixpanel/mixpanel-iphone#383]
![e1a5c299-ea56-45a0-8ddc-634f6c7a12d1](https://cloud.githubusercontent.com/assets/5733794/11261893/ef6bd03c-8eb3-11e5-91fc-7825bf3b6814.png)

**Comment by samgreen** [comment]
Hi @zjszyms, sorry you're having issues. No Mixpanel libraries are shown in that stack trace. This appears to be a crash caused by ZenDesk, and it's documented here: https://github.com/zendesk/zendesk_sdk_ios/issues/85
