### ISSUE TITLE
Build Failed For WatchOS2

### ISSUE THREAD

**Issue by RahilKarim** [mixpanel/mixpanel-iphone#384]
I am trying to integrate mixpanel in my watchextension (watchOS2). When I try install the mixpanel through cocoapods it doesnot compile and gives error "ld: library not found for -lPods-helloMixPannelWatchApp Extension-Mixpanel". I have also tried to install manually but the build fails with error "CoreTelephony/CTCarrier.h file not found".

I have successfully integrated mixpanel with watchOS1 extension. Is there any updates available for watchOS2?

**Comment by samgreen** [comment]
Can I please see your Podfile?

**Comment by RahilKarim** [comment]
target :HelloMixpanel do
    pod 'iOS-Color-Picker', '~> 0.0.6'
    pod 'Mixpanel'

end

target 'helloMixPannelWatchApp Extension' do
     pod 'Mixpanel/AppExtension'
end

**Comment by smaun** [comment]
Experiencing same issue, Do mixpanel supporting watchOS 2.0?? Any update..

**Comment by samgreen** [comment]
We are aware of the issue. We're working on a fix for watchOS 2. Looks like Apple totally changed the API. Look for a fix in 2.9.2 this month.

**Comment by samgreen** [comment]
This is now released as v2.9.2, thanks for your patience!
