### ISSUE TITLE
sdk is keeping my app awake in the background

### ISSUE THREAD

**Issue by joshblour** [mixpanel/mixpanel-iphone#386]
Using the new energy profiling tools in Xcode7, I noticed that my app energy usage spikes in the background about every 20 seconds. The only bar that is active is the networking bar and the only IP address that shows up is 184.173.79.84. Googling that address seems to indicate that it belongs to mixpanel.

**Comment by patedit** [comment]
Are you setting the flush interval to 20 seconds? I.e. `[Mixpanel sharedInstance].flushInterval = 20`
Could you add a screenshot of what you see?

Thanks!

**Comment by samgreen** [comment]
We are not seeing this behavior, and need more information to debug this. You also have the ability to set the flush interval yourself. Closing this issue until we get more information.
