### ISSUE TITLE
Possible Nil Dictionary access in Mixpanel.m

### ISSUE THREAD

**Issue by rroy1590** [mixpanel/mixpanel-iphone#393]
Our production app has been seeing crashes for the past few months in the following functions. It is likely the real problem is somewhere deeper but this code should probably be more defensive.

https://github.com/mixpanel/mixpanel-iphone/pull/392 

<img width="510" alt="screen shot 2015-12-08 at 4 32 06 pm" src="https://cloud.githubusercontent.com/assets/906694/11672974/dc5aeaa8-9dc9-11e5-9da2-4a0fc836dabe.png">
<img width="557" alt="screen shot 2015-12-08 at 4 31 57 pm" src="https://cloud.githubusercontent.com/assets/906694/11672976/dc6bde80-9dc9-11e5-8289-56bb1cd9639d.png">

**Comment by samgreen** [comment]
Resolved in #392
