### ISSUE TITLE
Mixpanel library needs to be audited for nullability

### ISSUE THREAD

**Issue by donholly** [mixpanel/mixpanel-iphone#397]
Is there a plan to do this to make Mixpanel safer when used in Swift?

**Comment by samgreen** [comment]
Hey @donholly, good to hear from you! This is definitely on the road map for the future. While we don't have an exact timeline to share, it is something that needs to be done soon. 

We're also happy to accept PRs!

**Comment by donholly** [comment]
Got it. Thanks, @samgreen! Hope all is well

**Comment by donholly** [comment]
@samgreen - We've decided we'll audit the Mixpanel library for nullability for 6 free months of service. Thoughts?

**Comment by samgreen** [comment]
@donholly Sent you an email.

**Comment by samgreen** [comment]
Resolved in #399
