### ISSUE TITLE
Apps with WatchKit framework report all events from Apple Watch

### ISSUE THREAD

**Issue by ryanseams** [mixpanel/mixpanel-iphone#409]
When you include the WatchKit.framework in your app, no matter what the Mixpanel SDK reports the events are coming from Apple Watch. This causes the property 'Watch Model' to be set as [this line](https://github.com/mixpanel/mixpanel-iphone/blob/47559612ab8ef8ca58818aed9eb5c13878312051/Mixpanel/Mixpanel.m#L895) is returning true because the framework is included in the build target.

To fix this there may need to be more conditions added to the above block of code or the SDK should use different logic that is more reliable at knowing the watch is actively being used (instead of simply existing within the build).

Below is a screenshot of this issue:
![here](https://cloud.githubusercontent.com/assets/9201737/12102672/3279ad02-b2f1-11e5-83b8-f3178c3e7adb.png)

**Comment by samgreen** [comment]
This is now released as v2.9.2, thanks for your patience!

**Comment by danieljimenez** [comment]
Did y'all test to confirm? I just put 2.9.2 in my project and am still seeing the same thing.
