### ISSUE TITLE
Question about 'service unavailable' log message

### ISSUE THREAD

**Issue by rsaunders100** [mixpanel/mixpanel-iphone#412]
Saw this in the logs earlier today (2016-01-14 12:18:02.797)

> [Mixpanel] <Mixpanel> decide check api error: service unavailable

Can someone confirm if this is caused by a Mixpanel outage or could it be something else network related?

**Comment by yinfeiru** [comment]
Hey,
Yinfei here from Mixpanel. Our decide servers were malfunctioning in the past ~20 mins and returning 503. It should be good now. I'll keep monitoring them for a bit.
