### ISSUE TITLE
Is it possible to remove yourself from all A/B tests?

### ISSUE THREAD

**Issue by stefandouganhyde** [mixpanel/mixpanel-iphone#414]
I've been wondering about ways of running an A/B test on the first view in an app, given the latency involved when calling `-joinExperimentsWithCallback:`.

One idea I had was that we could be quite aggressive about waiting for `-joinExperiments` to complete so that a given user would only be part of an A/B test if they receive the callback within a set time e.g.:
- start the app
- call `-joinExperimentsWithCallback:`
- if we get a result within, say, five seconds, then proceed as normal
- if the join experiments response takes longer than that, then the current user should **see default variants for the A/B tests and MixPanel should not include the user in the A/B test results**.

Is this possible?

**Comment by samgreen** [comment]
Does #420 help with this?

**Comment by peymano** [comment]
@stefandouganhyde We had a similar concern. You may be interested in our solution: https://github.com/mixpanel/mixpanel-iphone/issues/420#issuecomment-174567429

**Comment by stefandouganhyde** [comment]
@samgreen: see https://github.com/mixpanel/mixpanel-iphone/issues/420#issuecomment-174977049, which hopefully explains the difference between this and #420.

**Comment by stefandouganhyde** [comment]
Thanks for keeping us in the loop in the related issue #420, @samgreen.

I've been pondering this problem, and I'm starting to think that I worded this question the wrong way round. Maybe the real issue here is that there is no point where the Mixpanel SDK tells its servers that a user actually _saw_ their experiment variant. So rather than removing yourself from experiments, what about explicitly adding yourself to each experiment?

As an example of when this seems important, imagine you had an app with an A/B test on some obscure screen that users visit ~1% of the time. Now say the Mixpanel dashboard says this experiment has had 10,000 "users in the last 60 days". You'd be forgiven for believing that this was a large sample size, however only ~100 of those users have actually seen your experiment. Sure, as long as you're testing against appropriate metrics (like some event/funnel on the obscure screen), this isn't necessarily a problem, but it feels like it would be better if Mixpanel just showed the number of users that had actually seen your experiment.

I appreciate that this might represent a big change to the Mixpanel A/B testing architecture, but I'd still love to hear your thoughts.

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
