### ISSUE TITLE
Adding failure block to `joinExperimentsWithCallback:`?

### ISSUE THREAD

**Issue by yas375** [mixpanel/mixpanel-iphone#420]
## Current state

[Current API](https://github.com/mixpanel/mixpanel-iphone/blob/2106d67e4197b3244f202793d54d6e580152773e/Mixpanel/Mixpanel.h#L735):

```objective-c
- (void)joinExperimentsWithCallback:(nullable void (^)())experimentsLoadedCallback;
```

The callback is executed only in case everything was loaded successfully. For example if there is an [error with your service](https://twitter.com/mixpanel/status/689990498518458369) and it returns an error, then it just returns [here](https://github.com/mixpanel/mixpanel-iphone/blob/2106d67e4197b3244f202793d54d6e580152773e/Mixpanel/Mixpanel.m#L1278) and callback won't be called.

## The problem

I agree that in a lot of cases people doesn't need to know about a failure. But there might be a case when  we need. For example we want to test different navigation types in an app. To do this, we need to fetch variants at the end of sign in sign up before actually dismissing the sign up screen. We are fine to spin a spinner for some time while variants are fetched from Mixpanel's server. Was it successful or not - we need to dismiss our sign up screen. In case of a failure fetching variants we can use some default values, but we still need to dismiss the sign up screen. Currently if we do something like this:

```objective-c
  [self.mixpanel joinExperimentsWithCallback:^{
    // dismiss sign up screen
  }];
```

we are not getting guaranteed execution of the block.

## Proposed solution

Additionally to existent `joinExperimentsWithCallback:` we can add an additional method which will also take a failure callback:

```objective-c
- (void)joinExperimentsWithCallback:(nullable void (^)())experimentsLoadedCallback;
- (void)joinExperimentsWithCallback:(nullable void (^)())experimentsLoadedCallback onFailure:(nullable void (^)(NSError *))failureCallback;
```

Original method will call the new one passing `nil` as `failureBlock`.

This will also require similar modifications to `checkForVariantsWithCompletion:` and `checkForDecideResponseWithCompletion:useCache:`. It will by 100% backward compatible.

---

I'm happy to volunteer to implement this and submit a pull request. What do you think?

**Comment by samgreen** [comment]
Love it, and would be happy to merge a PR today or next week.

**Comment by samgreen** [comment]
Massive oversight on our part never calling the completion block.

**Comment by peymano** [comment]
In our scenario, we want to run the same code whether the call succeeds or fails—read a tweak variable and based on its value, do X or Y. I suspect that that is what most callers will want as well.

It would be better to keep the one callback, but provide an error object in case there is an error:

```
- (void)joinExperimentsWithCallback:(nullable void (^)(NSError *))experimentsLoadedCallback;
```

You see this pattern in many of Apple's CloudKit APIs.

**Comment by peymano** [comment]
In our app, we're using Mixpanel to test our onboarding experience. During first launch, we call Mixpanel's `identify:` and then `joinExperimentsWithCallback:` and wait for a response. Once we get a response, we read a tweak variable and use its value to decide which variant of our onboarding flow to show the user. We need to join experiments before reading the tweak variable, but we don't want to wait more than a few seconds in case Mixpanel's servers are slow to respond or the device has a poor network connection.

We considered adding a timeout to `joinExperimentsWithCallback:`, but given that the real work is done in `checkForDecideResponseWithCompletion:useCache:`, which queues a block on a serial queue, there's no way to ensure that the block runs before the timeout.

The solution we came up with was to wrap `joinExperimentsWithCallback:` with our own timer, and ensure that our callback is only invoked once.

```
  // Mixpanel's `joinExperimentsWithCallback:` only invokes our callback
  // on success. If there's an error (e.g., Mixpanel's service is down
  // or the network is unreachable), our callback is not invoked. We
  // also don't want to wait indefinitely in case the network is slow.
  //
  // We use a timer to ensure that our callback is invoked in a
  // timely manner and that it is invoked at most once.

  CGFloat timeout = 5; // in seconds

  __block BOOL didCallCompletionBlock = NO;
  dispatch_block_t callCompletionBlockOnce = ^{
    if (didCallCompletionBlock == NO) {
      didCallCompletionBlock = YES;
      if (completionBlock) {
        completionBlock();
      }
    }
  };

  dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(timeout * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
    callCompletionBlockOnce();
  });

  [self.mixpanel joinExperimentsWithCallback:^{
    dispatch_async(dispatch_get_main_queue(), ^{
      [CZSettings sharedInstance].didJoinAnalyticsExperiments = YES;
      callCompletionBlockOnce();
    });
  }];
```

**Comment by anderscarling** [comment]
Would love to see this as well!

**Comment by stefandouganhyde** [comment]
Thanks for sharing your solution, @peymano. Isn't there still an issue here if Mixpanel's servers are slow to respond? Consider the case where there is one A/B test set up, with two variants. This is the scenario I'm worried about:

- `-joinExperimentsWithCallback:` takes >5s.
- The completion block is called by the timer, and the application continues using the default A/B variant, say A.
- Mixpanel's servers respond and decide this user should be shown variant B.
- Future events sent to Mixpanel are all treated as the actions of a "B" user, which isn't true.
- We can't trust the results of the A/B test.

This was exactly the reasoning behind my issue #414. I want to be able to time out quickly, but also make sure Mixpanel knows what the user is actually shown.

**Comment by anderscarling** [comment]
@stefandouganhyde Short answer - Yes there is.

Basically what I do is that I setup my funnels/cohort analysis's so that only users who joined an experiment before first relevant action was performed is included in the set of users that i'm looking at.

Ie when looking at funnels i do something like
Step1: Joined Experiment filter experiment_id=
Step2: PageView for the page with the change.
Step3: Expected conversion event.

You are not able to setup multi-step goals like that in the AB-analysis tool though. :/

**Comment by peymano** [comment]
@stefandouganhyde Yes, that's an issue. The number of timeouts is low, so with enough data, it's not a factor. It would be great if Mixpanel automatically excluded these users.

**Comment by yas375** [comment]
Thanks everyone for the input! :+1: 
@samgreen I'm still happy to volunteer to work on implementation. But with the all input provided here and in #414 I think it's Mixpanel's turn to make a decision how do you guys want this to be. These two issues contain a lot of useful (imho) information about real use cases of A/B testing feature. Please let us know what directions you would like to go.

Thanks in advance.

**Comment by samgreen** [comment]
Thanks for brining this @yas375!

We're discussing internally and I hope to have an answer sometime this week.

**Comment by jmejiaa** [comment]
@samgreen has there been any updates on this?

**Comment by samgreen** [comment]
@jmejiaa @yas375 and anyone else interested. Does #470 resolve your issues sufficiently?

**Comment by jmejiaa** [comment]
@samgreen sounds like it would solve this issue. . I'll keep an eye out for it in the next releases

**Comment by samgreen** [comment]
Closing this issue since the fix has been released.
