### ISSUE TITLE
Upgrade to 2.9.2 from CocoaPods not supported?

### ISSUE THREAD

**Issue by coredream** [mixpanel/mixpanel-iphone#428]
Just a question - I'm using v2.9.1 currently and have 7.1 as my min deployment target.  It was my understanding that I should be able upgrade to 2.9.2, but not 3.0.0.
> In preparation for full Swift support, the next release (v3.0.0) will only support iOS 8+ via Carthage and CocoaPods

I believe this change doesn't allow me to upgrade:
https://github.com/mixpanel/mixpanel-iphone/commit/abbfdf609655e01c541eca2c8827f9ed6dfb805d

Does this mean 2.9.1 is the last version I can use with CocoaPods?

**Comment by samgreen** [comment]
This is resolved in v2.9.3
