### ISSUE TITLE
Crash in - (void)updateBindings:(NSArray *)bindingPayload

### ISSUE THREAD

**Issue by jcavar** [mixpanel/mixpanel-iphone#431]
When receiving list of bindings ```updateBindings``` is called. It loops through json objects and creates new collection of  ```MPEventBinding``` instances. It is possible that this 
        ```MPEventBinding *binding = [MPEventBinding bindingWithJSONObject:bindingInfo];```
results in ```nil``` so application crashes when trying to add that object to collection.

In our case we just renamed one view controller which was table view delegate, so translation from json was not possible because class was not found.

I am not sure if this should crash as it is now or we should just ignore that binding?

**Comment by samgreen** [comment]
Merged a fix for this. It will be 2.9.4

**Comment by jcavar** [comment]
Cool, thanks!
