### ISSUE TITLE
Property to know whether there is a survey available

### ISSUE THREAD

**Issue by Skorch** [mixpanel/mixpanel-iphone#433]
I have a feature requirement where we insert a call-to-action into a feed to complete a survey - but only if there's a survey targeted to that user. At the moment, there's no hook in the API to know whether showSurvey() will return a survey.  

I propose a property or function which will check whether the internal surveys NSArray has any data in it.

Alternately, to make `- (void)showSurveyWithID:(NSUInteger)ID;` more useful, maybe expose list of survey Ids?

**Comment by samgreen** [comment]
I'm adding a readonly property `isSurveyAvailable`. As far as exposing the survey IDs, I can't think of a scenario that would be useful for developers. You can already call `showSurvey` and it will show if one is available. Exposing the IDs would still require the developer to keep track of which survey ID is which on their end, and doesn't really improve the developer experience.

What are your thoughts @Skorch?

**Comment by samgreen** [comment]
This will be in 2.9.4

**Comment by Skorch** [comment]
Thanks @samgreen 

My product requirement is to use the Survey Name as a display name when passively prompting the user if they want to participate.  Is there any room for that to be returned?

**Comment by samgreen** [comment]
Sure that makes sense. Does #444 solve your issue?

You can use `survey.name` for your UI and `showSurveyWithID:survey.ID` to display the correct survey. Hope that makes sense.

**Comment by samgreen** [comment]
Marking as resolved.

**Comment by Skorch** [comment]
Perfect, thanks!
