### ISSUE TITLE
Crash: MPValueTransformers.h - [NSNull null] passed into *toType arg

### ISSUE THREAD

**Issue by Skorch** [mixpanel/mixpanel-iphone#434]
I've just installed Mixpanel (latest cocoapod), and I set up an A/B Experiment to update the text on a button. On launch, the app crashes on the function:

[MPValueTransformers.h](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/MPValueTransformers.h)
`__unused static id transformValue(id value, NSString *toType)`

on line 66:
`if ([value isKindOfClass:[NSClassFromString(toType) class]]) { `

toType is pointing to `[NSNull null]` rather than an `NSString` instance.

My base app is Swift. I'm running XCode 7.2.1

**Comment by samgreen** [comment]
Hey @Skorch, so sorry you're having trouble with A/B testing.

Is this Swift or Objective-C? You're on the latest release, 2.9.3?

**Comment by Skorch** [comment]
Yes, Mixpanel 2.9.3
My app is a Swift app.

**Comment by samgreen** [comment]
This appears to be a bug, though I am unable to reproduce it. Can you include any additional steps that may help me track this down?

**Comment by Skorch** [comment]
Are you able to look at the data returned from ab_test 12901 from mixpanel account 875147?

**Comment by samgreen** [comment]
Just pushed a fix for this crash, although more investigation is needed to find the underlying cause. I tested this fix with your data.

**Comment by Skorch** [comment]
Great, thanks!
