### ISSUE TITLE
Crash when archiving People records

### ISSUE THREAD

**Issue by mateagar** [mixpanel/mixpanel-iphone#453]
We are currently using the Mixpanel 2.8.2 and have experienced several thousand crashes in production when the `archivePeople` method is called. Apparently there is a problem serializing some of the people properties. Unfortunately, we don't have much information to go on, because this happens in the the background. Here is a canonical call stack from the exception logs:

`Thread : Crashed: com.mixpanel.a206232d2e8599e78679e4a25b088024.0x155668cc0`
`0  libsystem_kernel.dylib         0x182794140 __pthread_kill + 8`
`1  libsystem_pthread.dylib        0x18285cef8 pthread_kill + 112`
`2  libsystem_c.dylib              0x182705dac abort + 140`
`3  libsystem_malloc.dylib         0x1827c8d34 free_list_checksum_botch + 438`
`4  libsystem_malloc.dylib         0x1827c8d58 free_list_checksum_botch + 36`
`5  libsystem_malloc.dylib         0x1827beb1c tiny_malloc_from_free_list + 328`
`6  libsystem_malloc.dylib         0x1827bd5bc szone_malloc_should_clear + 268`
`7  libsystem_malloc.dylib         0x1827bd468 malloc_zone_malloc + 116`
`8  libsystem_malloc.dylib         0x1827c19ec malloc + 52`
`9  CoreFoundation                 0x182adaea8 -[__NSArrayM insertObject:atIndex:] + 156`
`10 Foundation                     0x18352ae4c addValueToTopContainerE + 196`
`11 Foundation                     0x18352b16c _encodeObject + 536`
`12 Foundation                     0x18352c8a4 -[NSKeyedArchiver _encodeArrayOfObjects:forKey:] + 448`
`13 Foundation                     0x18352c474 -[NSDictionary(NSDictionary) encodeWithCoder:] + 856`
`14 Foundation                     0x18352b3f0 _encodeObject + 1180`
`15 Foundation                     0x18352c8a4 -[NSKeyedArchiver _encodeArrayOfObjects:forKey:] + 448`
`16 Foundation                     0x18352b3f0 _encodeObject + 1180`
`17 Foundation                     0x183587584 +[NSKeyedArchiver archiveRootObject:toFile:] + 236`
`18 Lookout                        0x1003978f0 -[Mixpanel archivePeople] (Mixpanel.m:730)`
`19 Lookout                        0x1003a0a68 __65-[MixpanelPeople addPeopleRecordToQueueWithAction:andProperties:]_block_invoke (Mixpanel.m:1884)`
`20 libdispatch.dylib              0x182645630 _dispatch_call_block_and_release + 24`
`21 libdispatch.dylib              0x1826455f0 _dispatch_client_callout + 16`
`22 libdispatch.dylib              0x182651634 _dispatch_queue_drain + 864`
`23 libdispatch.dylib              0x1826490f4 _dispatch_queue_invoke + 464`
`24 libdispatch.dylib              0x1826455f0 _dispatch_client_callout + 16`
`25 libdispatch.dylib              0x182653a88 _dispatch_root_queue_drain + 2140`
`26 libdispatch.dylib              0x182653224 _dispatch_worker_thread3 + 112`
`27 libsystem_pthread.dylib        0x182859470 _pthread_wqthread + 1092`
`28 libsystem_pthread.dylib        0x182859020 start_wqthread + 4`

Is this a known issue? If not, do you have any suggestions on how we can track down the root cause?

**Comment by LeeMatthewHiggins** [comment]
I have a similar issue, currently my top crash 50% when app is in focus.

Thread : Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x182ad5900 __exceptionPreprocess
1  libobjc.A.dylib                0x182143f80 objc_exception_throw
2  CoreFoundation                 0x182adc61c __methodDescriptionForSelector
3  CoreFoundation                 0x182ad95b8 ___forwarding___
4  CoreFoundation                 0x1829dd68c _CF_forwarding_prep_0
5  Foundation                     0x18340f3f0 _encodeObject
6  Foundation                     0x1834108a4 -[NSKeyedArchiver _encodeArrayOfObjects:forKey:]
7  Foundation                     0x1834104c4 -[NSDictionary(NSDictionary) encodeWithCoder:]
8  Foundation                     0x18340f3f0 _encodeObject
9  Foundation                     0x1834108a4 -[NSKeyedArchiver _encodeArrayOfObjects:forKey:]
10 Foundation                     0x1834104c4 -[NSDictionary(NSDictionary) encodeWithCoder:]
11 Foundation                     0x18340f3f0 _encodeObject
12 Foundation                     0x1834108a4 -[NSKeyedArchiver _encodeArrayOfObjects:forKey:]
13 Foundation                     0x1834104c4 -[NSDictionary(NSDictionary) encodeWithCoder:]
14 Foundation                     0x18340f3f0 _encodeObject
15 Foundation                     0x1834108a4 -[NSKeyedArchiver _encodeArrayOfObjects:forKey:]
16 Foundation                     0x18340f3f0 _encodeObject
17 Foundation                     0x18346b584 +[NSKeyedArchiver archiveRootObject:toFile:]
18 Supe                           0x1001b4bd4 -[Mixpanel archiveEvents] (Mixpanel.m:744)
19 Supe                           0x1001b2c94 __29-[Mixpanel track:properties:]_block_invoke (Mixpanel.m:431)
20 libdispatch.dylib              0x182529630 _dispatch_call_block_and_release
21 libdispatch.dylib              0x1825295f0 _dispatch_client_callout
22 libdispatch.dylib              0x182535634 _dispatch_queue_drain
23 libdispatch.dylib              0x18252d0f4 _dispatch_queue_invoke
24 libdispatch.dylib              0x1825295f0 _dispatch_client_callout
25 libdispatch.dylib              0x182537a88 _dispatch_root_queue_drain
26 libdispatch.dylib              0x182537224 _dispatch_worker_thread3
27 libsystem_pthread.dylib        0x18273d470 _pthread_wqthread
28 libsystem_pthread.dylib        0x18273d020 start_wqthread

**Comment by szalap** [comment]
Is that issue already fixed or not resolved for that long?

**Comment by yarneo** [comment]
Issue is fixed in new release! Thanks for your patience
