### ISSUE TITLE
"Umbrella header not found" when using the library in Swift

### ISSUE THREAD

**Issue by dolma** [mixpanel/mixpanel-iphone#454]
Hello,

I followed all instructions to use the Mixpanel library in my swift project. I did:

1. Clone the git
2. Add the Mixpanel directory to my project directory in the Finder
3. Add the Mixpanel directory from the project directory in the Finder to the project hierarchy in XCode
4. Add the bridging header to my project
5. Added the line `#import "Mixpanel/Mixpanel.h"` in the bridging header
6. Added the line `import Mixpanel` in my Swift file (AppDelegate.swift)

When I do so and try to build the project, the build fails and I get the following errors:

> [My Project Directory Path]/Mixpanel/module.modulemap:2:21: Umbrella header 'Mixpanel.h' not found

And

> [My Project Directory Path]/AppDelegate.swift:14:8: Could not build Objective-C module 'Mixpanel'

I am guessing here that the second error is only resulting from the first one. But it still doesn't explain why the first error occurs in the first place.

I tried looking this error up. The solutions I found so far were:

- Checking in **Build Settings > Search Paths** that the _Always Search User Paths_ was set to No --> Mine already was
- in **Build Phases > Headers**, set the `Mixpanel.h` header file as having the visibility 'Public' --> Did that, didn't solve the error
- Removing the line: `umbrella header "Mixpanel.h"` in the **module.modulemap** file, but then I get the same error with the second line: `header "MixpanelWatchOS.h"`. I removed this as well, but then got another error with the last line of the file: `module * { export * }` but then got this error: 

> [My Project Directory Path]/Mixpanel/module.modulemap:6:12: Inferred submodules require a module with an umbrella

I thus removed this line as well, leaving only the line: `export *` in the **module.modulemap** file, and that removed the error, but I'm guessing it would also break the code and any call to the Mixpanel library.

What can I do to solve this problem ? I have tried looking everywhere, and all solutions either don't apply or don't work. Plus, the documentation about how to use Mixpanel in Swift is very scarce (only one very short paragraph about it, and then all examples are presented in Objective-C), so it's hard to find any answer.

Thanks!
Dolma

**Comment by samgreen** [comment]
Typically you manually integrate by dragging Mixpanel.xcodeproj in to Xcode. This is a swift module issue however, so I'm curious if you can add a bridging header and just import Mixpanel that way. Can you give that a shot?

**Comment by dolma** [comment]
Ok, so I followed your advice and after a few tests here and there I ended up solving the problem.

I removed the files from the project, and instead linked the **Mixpanel.xcodeproj** as a subproject in my project (as you said by drag-and-dropping it in XCode). However I couldn't use the bridging header with this method because I couldn't figure out how to reference it in my bridging header.
I tried a few different things and what worked for me was to simply go to the **Build Phases > Link Binary With Libraries** and add the _Mixpanel.framework (from target 'Mixpanel')_ to the list (which could be found there after adding the subproject).

So, if anyone wants to import the Lib in a swift project, no need for a bridging header, just follow these simple steps:

1. Clone the git
2. Drag and drop the file **Mixpanel.xcodeproj** to your project directory in XCode
3. Go to **Build Phases > Link Binary With Libraries**, click the **+** button and choose the **Mixpanel.framework** from the list (if you see two of them, just add the one that says it's from the Mixpanel target)
4. Add `import Mixpanel` at the start of any of the swift files you want to use Mixpanel with
5. You might also need to add the list of dependencies but I feel like it's not necessary since they are already linked to the Mixpanel subproject (not sure about that since I already added them to the build phase before trying out this solution and didn't remove them)

The procedure of copying the Mixpanel folder and using the bridging header was described here: https://mixpanel.com/blog/2014/09/30/integrating-the-mixpanel-ios-sdk-without-cocoapods and the information about using the bridging header was presented as:

> If you're using Swift, you will need to add #import "Mixpanel/Mixpanel.h" to your project's Objective-C Bridging Header.

(in https://mixpanel.com/help/reference/ios#installing)

Even though the first link is not specifically for swift, the two informations combined can lead to confusion when trying to integrate Mixpanel in a swift project. Hoping whoever encounters this problem later can use these steps to solve it.

Thanks a lot for the help @samgreen !
Dolma

**Comment by samgreen** [comment]
So glad you got it resolved! Thanks for the detailed feedback, we'll take a second look at the docs to make it more clear.

Out of curiosity why do you prefer manually integrating versus automated (CocoaPods or Carthage)? We want to make integration as easy as possible for every developer so your feedback would be very helpful.
