### ISSUE TITLE
In-app notifications truncating instead of moving text to second line

### ISSUE THREAD

**Issue by ryanseams** [mixpanel/mixpanel-iphone#455]
When support for landscape in-apps was added to the library, we stopped using auto layout in the [storyboard](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/MPNotification.storyboard) for in-app notifications and removed some [constraints](https://github.com/mixpanel/mixpanel-iphone/commit/bc946c791d28700bfe775689e5c448dcfcaac05d) from the [view](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/MPNotificationViewController.m).

Because of these changes, the text for an in-app longer than one line is being truncated instead of being properly displayed within the frame (images are below). This issue can be fixed by adding back the constraints + auto layout, however, this will cause landscape in-apps to continue to not work.

For the time being, the easiest fix was to simply move the call to action button further down the storyboard and extend the height of the UILabel container of the body ([bodyView](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/MPNotificationViewController.m#L71)), allowing for text to flow onto multiple lines. I am happy to submit a PR for this, however, since this is a design decision I decided to bring this up in the form of an issue so we can discuss what solution makes the most sense.

Here is an in-app from lib 2.9.1 functioning properly:
![image](https://cloud.githubusercontent.com/assets/9201737/13475676/1b42445e-e079-11e5-8184-04d96bcac447.png)
Here is the same in-app from lib 2.9.4 being truncated:
![image](https://cloud.githubusercontent.com/assets/9201737/13475697/2e099484-e079-11e5-9344-3e0a01fe44a3.png)
Finally here is the same in-app from lib 2.9.4 with my storyboard edits included:
![image](https://cloud.githubusercontent.com/assets/9201737/13476158/5793aefa-e07b-11e5-9ac7-513dd28635fc.png)

**Comment by doridayan** [comment]
Hi Ryan,

We're having the same issue in our app. I've notified Jared from Mixpanel about this and provided him with a screenshot illustrating it. Running iOS SDK version 2.9.2.

Thanks,
Dori

**Comment by alkuhnda** [comment]
Hi!

We recognized the same issue. We are running on iOS SDK 2.9.3.

Thanks,
Alex

**Comment by samgreen** [comment]
We're taking a look at this and hoped to have it resolved in the near future. Probably not next release, but soon.

**Comment by samgreen** [comment]
We have a PR open for this now, and it will be resolved in the next release.

**Comment by samgreen** [comment]
This is resolved in v2.9.5 which is now released.

**Comment by pradeepb28** [comment]
i dont see the max limit for notification? May I know what is the max limit?

**Comment by yarneo** [comment]
Hi @pradeepb28, the max limit is 90 characters for the subtitle, and 50 character for the title. I would also recommend seeing that the number of characters you decide to put in, fits well visually when you build the notification in the builder on the website.
