### ISSUE TITLE
Include non-modular framework 

### ISSUE THREAD

**Issue by soheilbm** [mixpanel/mixpanel-iphone#468]
I'm trying to add Mixpanel as one of my cocoapod dependency, but I noticed that inside 'Mixpanel+HostWatchOS.h' there is a non-modular header. I noticed in Xcode 7.3 even when I turn on non-modular header inside framework it still shows an error.

**Comment by samgreen** [comment]
Hi @soheilbm, what is the error you're seeing?

**Comment by soheilbm** [comment]
include of non-modular header inside framework module 'Mixpanel.Mixpanel_HostWatchOS'
<img width="1362" alt="screen shot 2016-04-08 at 2 13 17 pm" src="https://cloud.githubusercontent.com/assets/6387886/14375461/1ea28db0-fd94-11e5-8aaf-bef4937dc85b.png">

**Comment by soheilbm** [comment]
I close this issue, I found a solution already. I just needed to add pre post hook to my podspec. 

```
s.prepare_command = <<-CMD
                          find Pods -regex 'Pods/Mixpanel.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)Mixpanel\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'
                     CMD
```
