### ISSUE TITLE
Changing the value of a tweak variable doesn't update existing users

### ISSUE THREAD

**Issue by peymano** [mixpanel/mixpanel-iphone#479]
1. Setup a new A/B test where 100% of users get the value "A" for your tweak

2. Launch the app and confirm that the user receives "A"

3. Edit the A/B test split such that 100% of users get the value "B"

4. Background & foreground the app to force a call to `joinExperiments`

Expected: user sees "B"
Actual: user sees "A"

5. Background the app + force quit + launch the app

Expected: user sees "B"
Actual: user sees "A"

This may be expected behavior or not. I'd love to know.

**Comment by peymano** [comment]
I just tested this scenario with the Mixpanel Android sample app and the tweak value changes from "A" to "B" when the app is foregrounded (step 4).

It seems the iOS and Android SDKs are inconsistent here.

**Comment by ryanseams** [comment]
I am seeing the change apply on the second backgrounding and foregrounding of the app, but not the first... Is it possible to confirm you are seeing the same behavior?

I took the same steps as your initial case and just backgrounded and foregrounded the app once again.

**Comment by peymano** [comment]
@ryanseams I just tried it again. When I flip from value "A" to "B", then foreground the app, it picked up the new value. When I flipped the value back to "A", then foregrounded the app again, it stuck with "A". Backgrounding and foregrounding the app several times didn't change antyhing—it's still "A".

I debugged into the Mixpanel library a bit, in `checkForDecideResponseWithCompletion:...`, after the response is parsed:

```
(lldb) po rawVariants
<__NSCFArray 0x7f94ab5047b0>(
{
    actions =     (
    );
    "experiment_id" = 9689;
    id = 19343;
    tweaks =     (
                {
            default = "";
            encoding = "@";
            maximum = "<null>";
            minimum = "<null>";
            name = "Services Panel";
            type = string;
            value = FOO3;
        }
    );
}
)


(lldb) po parsedVariants
{(
    <MPVariant: 0x7f94ab49da20>
)}

(lldb) po [0x7f94ab49da20 tweaks]
<__NSArrayM 0x7f94ab4cd460>(
Tweak: Services Panel = FOO3
)
```

…so far so good, but then, after `runningVariants` and `finishedVariants` are set...


```
(lldb) po self.variants
{(
    <MPVariant: 0x7f94ab4b7f20>,
    <MPVariant: 0x7f94ad30bac0>
)}

(lldb) po [0x7f94ab4b7f20 tweaks]
<__NSArrayM 0x7f94ab4b9ee0>(
Tweak: Services Panel = none
)


(lldb) po [0x7f94ad30bac0 tweaks]
<__NSArrayM 0x7f94ad3054e0>(
Tweak: Services Panel = FOO3
)

(lldb) po runningVariants
{(
    <MPVariant: 0x7f94ab4b7f20>,
    <MPVariant: 0x7f94ad30bac0>
)}

(lldb) po finishedVariants
{(
    <MPVariant: 0x7f94ab4b7f20>,
    <MPVariant: 0x7f94ad30bac0>
)}

```

…is it expected to have 2 running variants with the same name?

**Comment by ryanseams** [comment]
Is the default value of your tweak also "A" in this case? Is it possible to try this where the default is one value, say "A", and the tweak in one variant changes this to "B" and the tweak in the other variant changes this to "C"?

In the above scenario it is definitely working on the second app open. You can see this in a video [here](https://www.dropbox.com/s/h57cjmezg89jeon/ABTestVariants.mov?dl=0) where the default value is 5, then after enabling the experiment + background/foreground twice the tweak changes this value to 15, and then after changing the variant allocation + background/foreground twice the tweak changes the value to 10.

As for the variants themselves, the variants they will have the same ```MPVariant``` but they will have different contents within.

**Comment by peymano** [comment]
@ryanseams I set my A/B test to "A" and "B". Started with 100% on "A". Reset the simulator. Installed our app. Created a new account. Here's my [video](https://dl.dropboxusercontent.com/u/939058/mixpanel.mov). I get stuck at "B".

**Comment by ryanseams** [comment]
@peymano Appreciate the video -- I see the same behavior in my test when I try to change back from 10 to 15. I am unable to go back to the prior variant due to the way the variants in the response are being parsed. Another side effect of this issue is that a user does not immediately leave an A/B test once it is turned off through the UI -- you would need to force quit the app to remove the cached test.

I had previously made a fix to this in https://github.com/mixpanel/mixpanel-iphone/pull/442 but it was reverted in recent versions through https://github.com/mixpanel/mixpanel-iphone/commit/89e031f90d8a184c91b8a05f5d27fbf93dd6ef98. When I add this fix back, the above two issues both go away.

@samgreen We may want to consider reworking how the variant response is parsed if we are not going to keep https://github.com/mixpanel/mixpanel-iphone/pull/442. While the case of flipping variants multiple times is unlikely in production, the case of leaving an A/B test is not.

**Comment by peymano** [comment]
@ryanseams Thank you for investigating. I appreciate the quick turn around.

**Comment by ryanseams** [comment]
@peymano If you want to modify the pod to achieve this behavior now as we investigate this further it should not result in any performance issues (beyond the failed unit tests). You can get the desired behavior by making the change in https://github.com/mixpanel/mixpanel-iphone/pull/442 (it's a one word fix).

We will continue looking on our end as to what should be done for this long-term.

**Comment by ryanseams** [comment]
@peymano This should be fixed in version 3.0.0 of the SDK. Mind giving it a try and letting me know if this issue still persists?

**Comment by peymano** [comment]
Will do. Thanks @ryanseams

**Comment by yarneo** [comment]
Closing this issue as we hadn't heard back. Feel free to reach out again if the problem persists.

**Comment by peymano** [comment]
@ryanseams Works. Thank you!
