### ISSUE TITLE
Missing Close-Button in new Light theme

### ISSUE THREAD

**Issue by alkuhnda** [mixpanel/mixpanel-iphone#480]
We recognized an issue with the new Light theme and Mixpanel iOS SDK 2.9.7, that has been introduced one or two weeks ago.

The Close button in the upper right corner is missing. The zone in the upper right corner does not show any reaction, when pressing into the white space where the button should be.

Editor:
![bildschirmfoto_2016-05-02_um_10_35_34](https://cloud.githubusercontent.com/assets/289491/14950411/ba8c6582-1051-11e6-82d0-92203ade1646.png)

App:
![img_0793](https://cloud.githubusercontent.com/assets/289491/14950468/175f5b3e-1052-11e6-8331-5451011eaf43.jpg)

**Comment by samgreen** [comment]
Hi @alkuhnda thanks for the bug report!

How are you integrating?
* Cocoapods
* Carthage
* Manual

What platforms do you see this issue?
* iPhone
* iPad
* Apple Watch
* All Platforms

**Comment by alkuhnda** [comment]
Hi @samgreen, integrated Mixpanel via Cocoapods.
The screenshot is from an iPhone 6S running at iOS 9.3.1. We also recognized the problem with an iPhone 6 and iOS 9.3.1.

**Comment by samgreen** [comment]
@alkuhnda Confirmed there is an issue. We have a fix in progress at #481

**Comment by yas375** [comment]
What versions of Mixpanel SDK are affected by the issue? Was it first time introduced in `2.9.7`?

**Comment by samgreen** [comment]
@yas375 This will be affected in versions 2.9.7 and 2.9.8, #481 has been merged, so expect a follow on release.

Apologies for the inconvenience!

**Comment by yas375** [comment]
@samgreen thanks for the quick reply. We are still on 2.9.6 :)

**Comment by samgreen** [comment]
We have [released a fix](https://github.com/mixpanel/mixpanel-iphone/releases/tag/v2.9.9) for this

**Comment by alkuhnda** [comment]
@samgreen Thx for the quick bugfix and release!
