### ISSUE TITLE
The value for the key MinimumOSVersion is invalid

### ISSUE THREAD

**Issue by z4r** [mixpanel/mixpanel-iphone#483]
Hi,
today submitting my app (with MP 2.9.9) through itunesconnect i got this error:

![schermata 2016-05-03 alle 11 50 48](https://cloud.githubusercontent.com/assets/639459/14979876/65f5f446-1125-11e6-947f-075b9f189971.png)

I check in the `project.pbxproj` and in the target Mixpanel for the 2.9.8 the `IPHONEOS_DEPLOYMENT_TARGET` value is `8.0` while for the new one is `7.1`.
But the IPHONEOS_DEPLOYMENT_TARGET for project is `8.0` for both tags.

**Comment by samgreen** [comment]
What integration method is this? 

Cocoapods, Carthage, or Manual?

**Comment by z4r** [comment]
Carthage

**Comment by jdauphant** [comment]
Same problem, I have revert to version 2.9.8

**Comment by JagCesar** [comment]
Same issue here, running v2.9.9

**Comment by damirstuhec** [comment]
Same here.

**Comment by patedit** [comment]
Sorry for the inconvenience guys. I have updated a new tag `v2.9.9.001` that fixes this issue. You should only have to run `carthage update` and it will grab the latest framework. Let me know if it worked!

**Comment by suspiration** [comment]
Having the same issue, can you create Mixpanel.framework with the fix?

**Comment by patedit** [comment]
Can you paste your 'Carthage.resolved' file?

**Comment by suspiration** [comment]
I am not using Carthage, but simply embedding Mixpanel.framework into my project for use.  Builds and works fine in simulator, but getting the error when trying to submit build.

**Comment by patedit** [comment]
@suspiration I have attached a zip file containing the framework fixing this issue. You can find it here: https://github.com/mixpanel/mixpanel-iphone/releases/tag/v2.9.9.001

Let me know if it worked!

**Comment by suspiration** [comment]
@patedit It worked, thanks!

**Comment by patedit** [comment]
Great! Glad it worked :)
