### ISSUE TITLE
timeEvent() question

### ISSUE THREAD

**Issue by goktugyil** [mixpanel/mixpanel-iphone#488]
So timeEvent() works as expected. I want to do other stuff with this time. Is there a way to extract that duration mixpanel stored for the event?
So essentially is there a way to access an event and its properties in someway inside the code?

**Comment by Coeur** [comment]
Two answers:

a) yes, you can unofficially hack into a given version of Mixpanel to get the value

    @interface Mixpanel ()
    - (NSMutableDictionary<NSString *, NSNumber *> *)timedEvents;
    @end
    @implementation Mixpanel (hack)
    - (nullable NSNumber *)hack_timedEvent:(NSString *)event {
        return self.timedEvents[event];
    }
    @end

Then you can use the `.doubleValue` of it and compare it with `[NSDate date].timeIntervalSince1970`.

b) timeEvent() is a poor implementation for some usages, as it uses [NSDate date] which is the clock of the device:
* it means it is sensible to leap seconds sent by NTP protocol (1 second can be added)
* it means it is sensible to daylight saving time (1 hour can be added or subtracted)
* it means it is sensible to NTP protocol attacks (46+ years can be subtracted, [and such attacks do exist](http://krebsonsecurity.com/2016/04/new-threat-can-auto-brick-apple-devices/))

If you want to time precise events without being affected by system clock, do it yourself simply using `CACurrentMediaTime()` from QuartzCore. Or if you want to avoid QuartzCore, use `mach_absolute_time()`:

    @interface CoeurTimer
    @property (nonatomic, strong) NSMutableDictionary<id<NSCopying>, NSNumber *> *accurateTimedValues;
    @property (nonatomic, assign) NSTimeInterval mach_timebase_in_seconds;
    @end
    @implementation CoeurTimer
    - (instancetype)init {
        self = [super init];
        _accurateTimedValues = [NSMutableDictionary dictionary];
        mach_timebase_info_data_t kTimebase;
        kern_return_t kError = mach_timebase_info(&kTimebase);
        if (kError == 0) {
            _mach_timebase_in_seconds = 1e-9 * (NSTimeInterval) kTimebase.numer / (NSTimeInterval) kTimebase.denom;
        }
        return self;
    }
    - (void)timeAbsoluteDurationStartWithKey:(id<NSCopying>)key {
        self.accurateTimedValues[key] = @(mach_absolute_time());
    }
    - (NSTimeInterval)timeAbsoluteDurationEndForKey:(id<NSCopying>)key {
        NSTimeInterval duration = _mach_timebase_in_seconds * (mach_absolute_time() - self.accurateTimedValues[key].unsignedLongLongValue);
        self.accurateTimedValues[key] = nil;
        return duration;
    }
    @end

But note that `CACurrentMediaTime()` and `mach_absolute_time()` are sensible to device sleep or device reboot, so if you need to support either case, you'll need to go back to `NSDate` solution and register to `NSSystemClockDidChangeNotification` and cross fingers that the system clock didn't change between the time the device did boot and the time your app did start.

**Comment by goktugyil** [comment]
Thanks!

**Comment by patedit** [comment]
Thanks @Coeur!
