### ISSUE TITLE
Survey prompt shows inconsistently and cannot be modified

### ISSUE THREAD

**Issue by ryanseams** [mixpanel/mixpanel-iphone#492]
Currently the prompt in the SDK to take a survey is being controlled by [this line](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L1229). Since this is based off of timestamps, the showing of this prompt is inconsistent and often times never shows.

We should modify this prompt to be configurable based on a config option so a user can choose if they want this prompt or not. In addition, it would be nice if the user could customize the text of this prompt without having to fork the library.

While https://github.com/mixpanel/mixpanel-iphone/issues/202 would be nice for default localization, it would make sense to allow for an end developer to choose if they want to prompt their users or not before a survey, as well as set the text they wish to use for that prompt.

**Comment by yarneo** [comment]
Survey has been deprecated, thanks for opening this issue but we are no longer supporting the Surveys feature.
