### ISSUE TITLE
Collection <CALayerArray: 0x15cfa88f0> was mutated while being enumerated.

### ISSUE THREAD

**Issue by Artelas** [mixpanel/mixpanel-iphone#494]
The crash was caught by Crashlytics, here is the screenshot:
![mixpanel crash](https://cloud.githubusercontent.com/assets/13298675/15358628/ec285fd8-1d0d-11e6-98fd-e44bd21cd88f.jpg)

**Comment by yarneo** [comment]
We have fixed this bug in https://github.com/mixpanel/mixpanel-iphone/commit/dde2ca69918ef0364eae7d247d93e9d52c464c11
This will be included in the next release

**Comment by yarneo** [comment]
New release out with the fix!
