### ISSUE TITLE
Crash when using NewRelic and Mixpanel at the same time

### ISSUE THREAD

**Issue by jblorenzo** [mixpanel/mixpanel-iphone#495]
Hello Mixpanel,

We got a lot of crash a few days after releasing a new build. It has been acting normally until the morning today:

```
Details
EXCEPTION NRInvalidArgumentException
LOCATION NRMAMethodProfiler.m line 984 in NRMA__beginMethod
TIME Today, 6:36
MESSAGE New Relic detected an unrecognized selector, 'mp_viewDidAppear:', sent to 'UIViewController'. It's possible _cmd was renamed by an unsafe method_exchangeImplementations().
Thread 0
CoreFoundation	Show CPU registers __exceptionPreprocess
libobjc.A.dylib	objc_exception_throw
OLX PH	NRMAMethodProfiler.m line 984 in NRMA__beginMethod
OLX PH	NRMAMethodProfiler.m line 921 in NRMA__boolParamHandler
UIKit	[UINavigationController viewDidAppear:]
OLX PH	NRMAMethodProfiler.m line 925 in NRMA__boolParamHandler
OLX PH	ABTWYSIWYGViewControllerSwizzling.xm line 371 in _logos_method$VCModCore$__ABT$viewDidAppear$
UIKit	[UIViewController _setViewAppearState:isAnimating:]
UIKit	[UIViewController _endAppearanceTransition:]
UIKit	[UITabBarController transitionFromViewController:toViewController:transition:shouldSetSelected:]_block_invoke945]
UIKit	[UIViewController _executeAfterAppearanceBlock]
UIKit	_runAfterCACommitDeferredBlocks
UIKit	_cleanUpAfterCAFlushAndRunDeferredBlocks
UIKit	_afterCACommitHandler
CoreFoundation	__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
CoreFoundation	__CFRunLoopDoObservers
CoreFoundation	__CFRunLoopRun
CoreFoundation	CFRunLoopRunSpecific
GraphicsServices	GSEventRunModal
UIKit	UIApplicationMain
OLX PH	main.m line 25 in main
0x18225e8b8 0 + 6478489784 See all threads
```

Let me know what we can do to fix this. We are removing Mixpanel from our app until this has been resolved.

**Comment by patedit** [comment]
Hello @jblorenzo ! New Relic relies on `_cmd` system method to be the same as the original method. Most of swizzling implementations change that value and New Relic is pushing for a different approach stating that everyone is not doing it correctly. ReactiveCocoa, Aspect, Instabug, any swizzling library (e.g. JRSwizzle), etc... will have the same _issue_ if you use New Relic. There are pros and cons with their approach and I think its worth to investigate for a third party framework like us but I don't see this happening in the coming release. 
New Relic has proposed to other customers to initialize their SDK after the conflicting library or disable interaction tracing:

```
[NewRelicAgent disableFeatures:NRFeatureFlag_InteractionTracing];
[NewRelic startWithApplicationToken:<appToken>];
``` 

Let me know what you think and thanks a lot for the report!

**Comment by jblorenzo** [comment]
We'll try that and get back to you. Thanks!
