### ISSUE TITLE
iOS app submission 

### ISSUE THREAD

**Issue by neerajgoyal12** [mixpanel/mixpanel-iphone#497]
"Your app is using the Advertising Identifier (IDFA). You must either provide details about the IDFA usage or remove it from the app and submit your binary again."

Getting this message from apple when submitting app for review. 
Using Mixpanel/Mixpanel (2.9.9)
No other 3rd party include this framework.
Also no AdSupport.framework is added to build settings Linked Frameworks and Libraries.
Please advice.

**Comment by neerajgoyal12** [comment]
Using Cocoa Pods

**Comment by patedit** [comment]
Hi @neerajgoyal12 ! If you are not using AdSupport.framework at all, then you need to include `MIXPANEL_NO_IFA` preprocessor macro in your build settings. You can see https://github.com/mixpanel/mixpanel-iphone/blob/v2.9.9/Mixpanel/Mixpanel.h#L373 for more details. 

Let me know if you are not able to do it and I'll walk you through the steps! 

Related: https://github.com/mixpanel/mixpanel-iphone/issues/112 https://github.com/mixpanel/mixpanel-iphone/issues/109

**Comment by neerajgoyal12** [comment]
Hi @patedit I did submit without setting it in build settings to the app store and said yes to using adFramework, the app might get rejected and will post it here for an update. 
Thanks was able to set it, though confused to set it at the app target level or pod target level, please clarify, am doing it at both the places for now, and submit a new binary if the earlier one gets rejected, so please suggest urgently.

**Comment by patedit** [comment]
@neerajgoyal12 Setting the preprocessor macro at Pods-Mixpanel target level should be enough. If you want to test it, you could run the app on release mode and check if https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L1012 is executed. It should not 👍

**Comment by neerajgoyal12** [comment]
@patedit will submit with just the pod level preprocessor and let you know about the rejection, if not will close the issue ... 
Thanks for your help and quick reply

**Comment by neerajgoyal12** [comment]
@patedit  Even after adding the macro at Mixpanel level both at debug and release getting the same message 
"Your app is using the Advertising Identifier (IDFA). You must either provide details about the IDFA usage or remove it from the app and submit your binary again." on app submission. 

Please advice

**Comment by neerajgoyal12** [comment]
![screen shot 2016-05-27 at 5 29 32 pm](https://cloud.githubusercontent.com/assets/182018/15607499/dbf8e45a-2430-11e6-837f-38ee2c555f66.png)

**Comment by neerajgoyal12** [comment]
@patedit sending you the screen shot for running in release mode on a 4s simulator 
the ifa is not nil, in fact it is nil for debug mode, though setting the same preprocessor macro for both debug and release setting at Mixpanel pod target 

![screen shot 2016-05-27 at 6 13 59 pm](https://cloud.githubusercontent.com/assets/182018/15608360/1934a83a-2437-11e6-92a2-1b1770165f85.png)

**Comment by patedit** [comment]
Make sure you don't have `AdSupport.framework` linked in your project and not other library is linking to that framework. If `ifa` is not `nil` it means that AdSupport was linked somehow. Also, for both debug and release preprocessor macros check that your Resolved column contains `MIXPANEL_NO_IFA`.

**Comment by neerajgoyal12** [comment]
hi @patedit This time I just updated cocapods to version 1 and did pod update, set the preprocessor macro MIXPANEL_NO_IFA at pod mixpanel level only for release and didn't get the message 
"Your app is using the Advertising Identifier (IDFA). .... "

Also using 
```
[Mixpanel sharedInstanceWithToken:kMixpanelToken launchOptions:launchOptions];
```
instead of 
```
[Mixpanel sharedInstanceWithToken:] 
```
in 
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions 
```
i don't know if that changed the things, also preprocessed Mixpanel.m and made sure IFA returns nil always. I think, I will close the issue, described it here in full for further assistance to anyone else facing a similar problem. 

Thanks

**Comment by patedit** [comment]
Thanks @neerajgoyal12 ! Happy it worked.
