### ISSUE TITLE
Disabling AB test designer with Carthage

### ISSUE THREAD

**Issue by mdiep** [mixpanel/mixpanel-iphone#502]
I'd like to use Mixpanel with Carthage, but disable the `ABTestDesigner`. At present, you can only disable it through the use of the `DISABLE_MIXPANEL_AB_DESIGNER` build setting, and Carthage doesn't support adding build settings.

Would it be possible to add a method to `Mixpanel` that disables the AB test designer?

**Comment by patedit** [comment]
Hi @mdiep - You can't add preprocessor macros on Carthage but we are planning to let devs customize the SDK programmatically without using build settings so people that use Carthage can benefit from all the SDK can do. Stay tuned and we will update this ticket as soon as we support this feature. In the meanwhile the only thing I can suggest is to integrate Mixpanel using Cocoapods. Thanks for your feedback!

**Comment by mdiep** [comment]
> we are planning to let devs customize the SDK programmatically without using build settings so people that use Carthage can benefit from all the SDK can do.

That's great news! Thank you!

**Comment by samgreen** [comment]
Resolved in #504 which is on master.

This change will be packaged with the next official release.

**Comment by samgreen** [comment]
This is now released with v3.0.0.
