### ISSUE TITLE
how to find session length using mixpanel?

### ISSUE THREAD

**Issue by pradeepb28** [mixpanel/mixpanel-iphone#513]
how to find session length using mixpanel?

**Comment by patedit** [comment]
Hi @pradeepb28 ! The best way to achieve this using Mixpanel SDK is to use `timeEvent`. 
I'd start a time event on `applicationDidBecomeActive` and then track the event (which will act as a stop timer) when the app is no longer visible.
Example:
```
- (void)applicationDidBecomeActive:(UIApplication *)application {
    [[Mixpanel sharedInstance] timeEvent:@"Session"];
}

- (void)applicationWillResignActive:(UIApplication *)application {
    [[Mixpanel sharedInstance] track:@"Session"];
}
```

**Comment by pradeepb28** [comment]
I am looking of start and end time from mixpanel.

**Comment by cassiegamm** [comment]
Hi @pradeepb28, 

If you track session length using the timeEvent method as @patedit recommended you'll be able to easily query session durations within your Mixpanel project. Examples of this can be found in this community tip under "Visualizing session length in your Mixpanel project" : https://blog.mixpanel.com/2015/06/22/community-tip-session-length-tracking/

**Comment by pradeepb28** [comment]
@cassiegamm so if i use timeEvent, then I don't need to implement start and end time specifically ?

**Comment by cassiegamm** [comment]
Correct @pradeepb28. If you implement timeEvent as @patedit recommended your app will fire a "Session" event at app close that contains a property named "duration" that tracks the number of seconds between applicationDidBecomeActive and applicationWillResignActive.

**Comment by pradeepb28** [comment]
So in  mix panel portal, can I filter out with custom dates and find out how much duration user has spent on that particular day just by doing with timeEvent ?

**Comment by cassiegamm** [comment]
Yes, you could quantify the total amount of time that a specific user spent on a specific day using the segmentation report (provided you tracked the duration of each session and a unique user identifier as properties of the session event). If you email support@mixpanel.com and explain your analytics goals they can provide further examples.

**Comment by pradeepb28** [comment]
1+

**Comment by pradeepb28** [comment]
+1
