### ISSUE TITLE
Background flushing doesn't work

### ISSUE THREAD

**Issue by simonmitchell** [mixpanel/mixpanel-iphone#519]
**Integration Method:** Manual
**Xcode Version:** 7.3.1
**Library Version:** Latest commit on Master (Guys, you should really be developing on develop)
**Platform:** iOS
**Device:** Simulator

[x] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER)

**Description:** App doesn't flush events upon entering background with default configuration
**Expected Behavior:** App will flush events upon entering background with default configuration

Seems like on line 971 of Mixpanel.m you're switching off networking upon receiving the NSNotification that the app is about to resign active:
```
- (void)applicationWillResignActive:(NSNotification *)notification
{
    MixpanelDebug(@"%@ application will resign active", self);
    self.network.enabled = NO;
}
```
When flush is then called from `- (void)applicationDidEnterBackground:(NSNotification *)notification
`
The networker has already been set to disabled, meaning a flush to the API never occurs:
```
- (void)flushQueue:(NSMutableArray *)queue endpoint:(NSString *)endpoint {
    if ([[NSDate date] timeIntervalSince1970] < self.requestsDisabledUntilTime) {
        MixpanelDebug(@"Attempted to flush to %@, when we still have a timeout. Ignoring flush.", endpoint);
        return;
    }
    
    if (!self.enabled) return;
```

**Comment by patedit** [comment]
Hey @simonmitchell - the issue has been fixed. So sorry for the inconvenience.

**Comment by simonmitchell** [comment]
No problems at all, just happy to help! :)
