### ISSUE TITLE
Flush timer doesn't start

### ISSUE THREAD

**Issue by simonmitchell** [mixpanel/mixpanel-iphone#520]
**Integration Method:** Manual
**Xcode Version:** Latest commit to Master
**Library Version:** 7.3.1
**Platform:** iOS
**Device:** Simulator

[x] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER)

**Description:** On the latest commit to master the flush timer's are never initialised and never start running, also flush on backgrounding of the app is also broken, meaning no events are flushed at all
**Expected Behavior:** The flush timer should be started and flushing events periodically.

As far as I can see the only time the flush timers are set up is in the setter method of `flushInterval` however the init method sets this using the `_flushInterval` ivar meaning the setter isn't called. This means that unless I'm manually setting the flushInterval in my code I won't receive any events.

**Comment by patedit** [comment]
@simonmitchell You are totally right and thanks a lot for pointing it out! Fixed on latest commit in master.

**Comment by simonmitchell** [comment]
No worries, happy to help!
