### ISSUE TITLE
Crash from MPNotification.m line 100. [MPNotification notificationWithJSONObject:]

### ISSUE THREAD

**Issue by jaimz** [mixpanel/mixpanel-iphone#530]
We're suddenly getting a *lot* of crashes from this method (starting ~ 2 hours ago). The actual problem seems to be:

Fatal Exception: NSInvalidArgumentException
*** -[NSURL initWithScheme:host:path:]: path 1466675944031.684919.uwp5@2x.png is not absolute.

The Crashlytics output:

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x180a5edb0 __exceptionPreprocess
1  libobjc.A.dylib                0x1800c3f80 objc_exception_throw
2  CoreFoundation                 0x180a5ecf8 -[NSException initWithCoder:]
3  Foundation                     0x181444568 -[NSURL(NSURL) initWithScheme:host:path:]
4  Mixpanel                       0x100a9b5a0 +[MPNotification notificationWithJSONObject:] (MPNotification.m:100)
5  Mixpanel                       0x100a8ba74 __58-[Mixpanel checkForDecideResponseWithCompletion:useCache:]_block_invoke (Mixpanel.m:1424)
6  libdispatch.dylib              0x1804a94bc _dispatch_call_block_and_release
7  libdispatch.dylib              0x1804a947c _dispatch_client_callout
8  libdispatch.dylib              0x1804b54c0 _dispatch_queue_drain
9  libdispatch.dylib              0x1804acf80 _dispatch_queue_invoke
10 libdispatch.dylib              0x1804a947c _dispatch_client_callout
11 libdispatch.dylib              0x1804b7914 _dispatch_root_queue_drain
12 libdispatch.dylib              0x1804b70b0 _dispatch_worker_thread3
13 libsystem_pthread.dylib        0x1806c1470 _pthread_wqthread
14 libsystem_pthread.dylib        0x1806c1020 start_wqthread

**Integration Method:** Cocoapods
**Xcode Version:** 7.3.1
**Library Version:** 2.9.9
**Platform:** iOS
**Device:** iPhone

**Comment by yarneo** [comment]
Hey jaimz, thanks for letting us know. This will be fixed in the upcoming release (3.0.0)
