### ISSUE TITLE
Crashes on iOS10 / Xcode 8

### ISSUE THREAD

**Issue by leogdion** [mixpanel/mixpanel-iphone#539]
**Integration Method:** Cocoapods
**Xcode Version: 8.0 beta 1 8S128d
**Library Version: 3.0.0
**Platform:** iOS 10 beta 1
**Device:** Simulator
**Language:** Swift

[ X] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER)
Preprocessor Macros Set DISABLE_MIXPANEL_AB_DESIGNER=1

**Description:** #1	
Crash At
0x000000010ae618e9 in -[MPWebSocket _performDelegateBlock:] at ...MPWebSocket.m:424
Happens after Mixpanel is initialzed:
self.mixpanel = Mixpanel.sharedInstance(withToken: token)

**Expected Behavior:** 
Event Sent

<img width="960" alt="screen shot 2016-07-01 at 10 09 49 pm" src="https://cloud.githubusercontent.com/assets/1036388/16537747/7b4ca4ba-3fd9-11e6-8568-a11c18aca680.png">

**Comment by samgreen** [comment]
Hi @leogdion, while we don't have the resources to officially support any beta products (neither Xcode nor iOS), you did manage to pique our curiosity.

We are unable to reproduce the issue internally, by starting with a clean project. It's worth noting that we added run time disabling of the A/B test design interface with v3.0.0, can you try disabling this at runtime?

I believe the Swift would be something like:

`Mixpanel.sharedInstance().enableABTestDesigner = false`

Again, we don't have the resources to support a beta product, but hopefully we can get you on the right track.

**Comment by leogdion** [comment]
That worked! Thanks. Is there a difference between using the macro vs. doing it in code?

**Comment by samgreen** [comment]
If you use the macro then the A/B code will be completely *removed* at compile time. If instead, you use the setter, you can decide the logic for enabling the test designer. For instance, it maybe useful to only enable A/B test designing for users with the correct email address.

Glad your issue was resolved!

**Comment by vivek1608** [comment]
In ios10/xcode8 when i run application on iphone 4s(8.4 version ) then application crass.Please tell solution.
![screen shot 2016-09-29 at 5 01 23 pm](https://cloud.githubusercontent.com/assets/12947838/18952482/6b591bfe-8667-11e6-813d-7a004cd851d1.png)

**Comment by yarneo** [comment]
@vivek1608 i don't see this being related to Mixpanel.

**Comment by vivek1608** [comment]
@yarneo it crass in every class where nsurl image is
