### ISSUE TITLE
One deprecated NSURLConnection call remains

### ISSUE THREAD

**Issue by richardbuckle** [mixpanel/mixpanel-iphone#542]
**Integration Method:** CocoaPods
**Xcode Version:** 7.3.1
**Library Version:** 3.0.0
**Platform:** iOS 
**Device:** Simulator and iPhone (all models)
**Language:** Swift and Objective-C

[ ] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER) No

**Description:** The release notes for 3.0.0 say that all deprecated APIs and all NSURLConnection usage has been removed, but one remains at `Mixpanel.m` line 1109:

    NSData *data = [NSURLConnection sendSynchronousRequest:request returningResponse:&urlResponse error:&error];

This is preventing a clean build with warnings for deprecated API turned on.

**Expected Behavior:** a clean build with warnings for deprecated API turned on.

**Comment by samgreen** [comment]
Hey @richardbuckle thanks for calling this out, we will be sure to patch this in v3.0.1

**Comment by richardbuckle** [comment]
Thank you @samgreen and I look forward to 3.0.1. 
I love having clean builds with zero warnings and am very glad that you care about that too.

**Comment by yarneo** [comment]
Has been resolved in v3.0.1!
