### ISSUE TITLE
Creating a Mixpanel instance leads to constant unnecessary CPU usage

### ISSUE THREAD

**Issue by anlaital** [mixpanel/mixpanel-iphone#543]
**Integration Method:** CocoaPods
**Xcode Version:** 7.3.1
**Library Version:** 3.0.0
**Platform:** iOS
**Device:** iPad
**Language:** Swift

[ ] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER)

**Description:** 

Simply calling `Mixpanel.sharedInstanceWithToken("some_token")` leads to constant 3% CPU utilisation for the application.

<img width="418" alt="screen shot 2016-07-14 at 13 46 04" src="https://cloud.githubusercontent.com/assets/2168023/16837027/876e95b0-49c9-11e6-8472-1c09cf756a8c.png">
<img width="1024" alt="screen shot 2016-07-14 at 13 47 12" src="https://cloud.githubusercontent.com/assets/2168023/16837028/876febfe-49c9-11e6-839a-95e737b77386.png">

**Expected Behavior:** 

CPU utilisation when the app is idle should be 0%.

**Comment by samgreen** [comment]
Hi @anlaital can you share what your `flushInterval` is set to? I have a theory you are flushing every second, I'm showing 0% CPU when profiled, and a jump to 3% on flush in the simulator. 

Does that look like what you're seeing?

**Comment by anlaital** [comment]
Our `flushInterval` is the default value which does seem to be set to `1`. Is it expected behaviour that there is disk access and CPU usage even though no events have been written?

**Comment by samgreen** [comment]
You can see [here](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L30), that the default is a much more sane sixty seconds in production. I would expect disk access when the app first loads, and defaults are restored from disk.

I'm not seeing consistent and / or pegged disk access when running a test app locally here. Can you confirm this behavior in a release build, or by adjusting the `flushInterval` to something closer to what you plan to use in production?

**Comment by anlaital** [comment]
This is indeed fixed by setting a bit more sane `flushInterval` in debug builds. It might be helpful to document the default `flushInterval` values in the header.

Thank you for the comments, closing this issue now.
