### ISSUE TITLE
Feature request - Block called for in-app notifications.

### ISSUE THREAD

**Issue by CarbonComputed** [mixpanel/mixpanel-iphone#546]
Optional block that gets called when a user dismisses a notification.  
When `wasDismissedWithStatus`, is called, an optional block property would be called.  This would be really useful for tracking analytics on the number of users that either hit the dismiss button or the the "Submit" button for in-app takeovers.  Currently we have a blind spot on the number of users that hit dismiss.

**Comment by CarbonComputed** [comment]
Submitted a PR, not too familiar with Mixpanel style: https://github.com/mixpanel/mixpanel-iphone/pull/547

**Comment by yarneo** [comment]
Hey @CarbonComputed , may I ask in what case would you want to differentiate between pressing the X button or the Submit button? I think your PR looks sound but I am a bit reluctant to add another outwards facing property unless it is a necessary thing
