### ISSUE TITLE
MPNetwork doesn't obey showNetworkActivityIndicator

### ISSUE THREAD

**Issue by simonmitchell** [mixpanel/mixpanel-iphone#549]
**Integration Method:** Manual
**Xcode Version:** 7.3.1
**Library Version:** 3.0.0
**Platform:** iOS
**Device:** All
**Language:** Swift

**Description:** 

the showNetworkActivityIndicator property on Mixpanel.h doesn't actually do anything

**Expected Behavior:** 

The showNetworkActivityIndicator property should correctly enable/disable Mixpanel's control over the application network activity indicator

**Comment by emitelma** [comment]
+1

**Comment by samgreen** [comment]
Confirmed, this is an issue. We'll get a fix out with next release!

**Comment by yarneo** [comment]
Has been resolved in v3.0.1!
