### ISSUE TITLE
Xcode 8 Beta 2 has warnings for SecRandomCopyBytes (warn_unused_result)

### ISSUE THREAD

**Issue by welshm** [mixpanel/mixpanel-iphone#551]
**Integration Method:** Manual
**Xcode Version:** 8 beta 2
**Library Version:** 3.0.0
**Platform:** iOS
**Device:** Simulator
**Language:** Objective-C

[ ] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER)

**Description:** With warnings as errors, warn_unused_result from SecRandomCopyBytes in MPWebSocket creates errors.
**Expected Behavior:** Result can be logged and warning created

**Comment by samgreen** [comment]
It appears we've had a regression, as this was resolved with #507, investigating now.

**Comment by yarneo** [comment]
Has been resolved in v3.0.1!
