### ISSUE TITLE
Crash SIGSEGV MPSwizzler.m line 44 in mp_swizzledMethod_2

### ISSUE THREAD

**Issue by jack3010** [mixpanel/mixpanel-iphone#555]
**Integration Method: Manual** 
**Xcode Version:7.3.1** 
**Library Version:3.0.0** 
**Platform:iOS** 
**Device: user devices** 
**Language:Objective-C**

[ ] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER)

Use command `[Mixpanel sharedInstance].enableABTestDesigner = NO;` in func `(BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions` 

**Description:** 
My project  continuously getting a crash related to MPSwizzler.m line 44 mp_swizzledMethod_2.
Also, I've added mixpanel v.3.0.0 on my project then i release to app store.
Today, I checking on new relic, it still show crash many time with `SIGSEGV
MPSwizzler.m line 44 in mp_swizzledMethod_2`. Please help me to check it. 

`Details
EXCEPTION SIGSEGV
LOCATION MPSwizzler.m line 44 in mp_swizzledMethod_2
TIME 06/27, 1:23
Thread 0
libobjc.A.dylib	Show CPU registers objc_release
app9to5	MPSwizzler.m line 44 in mp_swizzledMethod_2
UIKit	[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke]
UIKit	[UIView(Hierarchy) _postMovedFromSuperview:]
UIKit	[UIView(Internal) _addSubview:positioned:relativeTo:]
UIKit	[UIView initWithCoder:]
UIKit	[UIClassSwapper initWithCoder:]
UIKit	UINibDecoderDecodeObjectForValue
UIKit	[UINibDecoder decodeObjectForKey:]
UIKit	[UIRuntimeConnection initWithCoder:]
UIKit	UINibDecoderDecodeObjectForValue
UIKit	UINibDecoderDecodeObjectForValue
UIKit	[UINibDecoder decodeObjectForKey:]
UIKit	[UINib instantiateWithOwner:options:]
UIKit	[UIViewController _loadViewFromNibNamed:bundle:]
UIKit	[UIViewController loadView]
UIKit	[UIViewController loadViewIfRequired]
UIKit	[UINavigationController _layoutViewController:]
UIKit	[UINavigationController _updateScrollViewFromViewController:toViewController:]
UIKit	[UINavigationController _startTransition:fromViewController:toViewController:]
UIKit	[UINavigationController _startDeferredTransitionIfNeeded:]
UIKit	[UINavigationController __viewWillLayoutSubviews]
UIKit	[UILayoutContainerView layoutSubviews]
UIKit	[UIView(CALayerDelegate) layoutSublayersOfLayer:]
QuartzCore	[CALayer layoutSublayers]
QuartzCore	CA::Layer::layout_if_needed(CA::Transaction*
QuartzCore	CA::Layer::layout_and_display_if_needed(CA::Transaction*
QuartzCore	CA::Context::commit_transaction(CA::Transaction*
QuartzCore	CA::Transaction::commit(
QuartzCore	0x1887454bc 0x188744000 + 5308
CoreFoundation	__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
CoreFoundation	__CFRunLoopDoObservers
CoreFoundation	CFRunLoopRunSpecific
UIKit	[UIApplication _run]
UIKit	UIApplicationMain
app9to5	main.m line 15 in main
libdyld.dylib	start`

Here is the timeline of crash: 

![screen shot 2016-08-01 at 2 33 32 pm](https://cloud.githubusercontent.com/assets/9066873/17286669/27814118-57f5-11e6-9e70-6e310a85fac2.png)

**Expected Behavior:**

**Comment by yarneo** [comment]
Hi @jack3010, by looking at your project, it seems like v4.1.3 is using Mixpanel's 2.9.9 SDK version rather than 3.0.0. Feel free to contact us at support@mixpanel.com if you want to discuss this more. Thanks!
