### ISSUE TITLE
Crash SIGSEGV MPUIControlBinding.m Mixpanel v3.0.0

### ISSUE THREAD

**Issue by jack3010** [mixpanel/mixpanel-iphone#556]
**Integration Method:** Manual
**Xcode Version:** 7.3.1 
**Library Version:** v.3.0.0
**Platform:** iOS
**Device:** user devices
**Language:** Objective-C

[ ] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER)

**Description:** 

Crash log: 

`EXCEPTION SIGSEGV
LOCATION MPUIControlBinding.m line 136 in [MPUIControlBinding execute]_block_invoke]
TIME 07/10, 9:32
Thread 0
libobjc.A.dylib	Show CPU registers objc_retain
UIKit	[UIControl addTarget:action:forControlEvents:]
app9to5	MPUIControlBinding.m line 136 in [MPUIControlBinding execute]_block_invoke]
app9to5	MPSwizzler.m line 44 in mp_swizzledMethod_2
UIKit	[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke]
UIKit	[UIView(Hierarchy) _postMovedFromSuperview:]
UIKit	[UIView(Internal) _addSubview:positioned:relativeTo:]
UIKit	[UITabBar setItems:animated:]
UIKit	[UITabBarController _rebuildTabBarItemsAnimated:]
UIKit	[UITabBarController _setViewControllers:animated:]
UIKit	[UITabBarController setViewControllers:animated:]
app9to5	MainViewController.m line 933 in [MainViewController checkUseSheduleOrCalendar]
app9to5	MainViewController.m line 193 in [MainViewController loginDoneCallBack]
CoreFoundation	__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
CoreFoundation	_CFXRegistrationPost
CoreFoundation	___CFXNotificationPost_block_invoke
CoreFoundation	[_CFXNotificationRegistrar find:object:observer:enumerator:]
CoreFoundation	_CFXNotificationPost
Foundation	[NSNotificationCenter postNotificationName:object:userInfo:]
app9to5	NotificationUtils.m line 30 in [NotificationUtils postNotification:]
Foundation	[NSObject(NSThreadPerformAdditions) performSelector:onThread:withObject:waitUntilDone:modes:]
Foundation	[NSObject(NSThreadPerformAdditions) performSelectorOnMainThread:withObject:waitUntilDone:]
app9to5	NRGCDOverride.m line 88 in __NR__dispatch_async_block_invoke
libdispatch.dylib	_dispatch_call_block_and_release
libdispatch.dylib	_dispatch_client_callout
libdispatch.dylib	_dispatch_main_queue_callback_4CF
CoreFoundation	__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
CoreFoundation	__CFRunLoopRun
CoreFoundation	CFRunLoopRunSpecific
GraphicsServices	GSEventRunModal
UIKit	UIApplicationMain
app9to5	main.m line 15 in main
0x1804d68b8 0 + 6447524024`

Here is image timeline of crash 

![screen shot 2016-08-01 at 3 34 23 pm](https://cloud.githubusercontent.com/assets/9066873/17288133/96f4a5d2-57fd-11e6-9c2b-43032e600d4c.png)

**Expected Behavior:**

**Comment by yarneo** [comment]
Hi @jack3010, by looking at your project, it seems like v4.1.3 is using Mixpanel's 2.9.9 SDK version rather than 3.0.0. Feel free to contact us at support@mixpanel.com if you want to discuss this more. Thanks!

**Comment by jack3010** [comment]
Hi @yarneo 
The error about
[MPUIControlBinding execute]_block_invoke effect to many user in my app. They always claim my team about quality of app. Please support me to resolve it asap! Thanks guy!

**Comment by cassiegamm** [comment]
Hi @jack3010,

As @yarneo mentioned, we investigated this issue and found that version 4.1.3 of the Planday app is using version 2.9.9 of mixpanel's iOS sdk (https://cloud.githubusercontent.com/assets/9066873/17286669/27814118-57f5-11e6-9e70-6e310a85fac2.png). Unfortunately, this version of the SDK causes the crash outlined above. 

The newest version of your app appears to be running version 3.0.0. As user's apps update to the newest version of Planday's iOS app (4.2.0) you should see these crashes disappear. 

If you receive any crash reports from an app version that is running version 3.0.0+ please let us know. We really do appreciate feedback from community members like you that let us catch issues like this early on  as it allows us to push a fix as soon as possible. 

If you'd like to discuss this matter in more detail, please email me directly at cassie@mixpanel.com

thanks!
