### ISSUE TITLE
Cannot build Mixpanel as Pod since ASL migration (3.0.1)

### ISSUE THREAD

**Issue by ldiqual** [mixpanel/mixpanel-iphone#559]
**Integration Method:** CocoaPods
**Xcode Version:** 7.3.1
**Library Version:** 3.0.1
**Platform:** iOS
**Device:** Simulator
**Language:** Swift

[ ] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER)

**Description:** 

Compiler errors out when compiling Mixpanel as a pod since the ASL migration:

![image](https://cloud.githubusercontent.com/assets/941453/17384686/aaa5c23c-5992-11e6-828c-e68c4e44eba2.png)

 > /Users/ldiqual/App/app/Pods/Mixpanel/Mixpanel/MPLogger.h:10:9: Include of non-modular header inside framework module 'Mixpanel.MPLogger'

Last commit on this line: https://github.com/mixpanel/mixpanel-iphone/commit/f19f41419c9855cbc9cb124c405603f30801742c

**Expected Behavior:** 

Should compile properly.

**Comment by yarneo** [comment]
Thank you @ldiqual for letting us know and sorry for the inconvenience. We will push out an update immediately to resolve this issue for Swift users.

**Comment by yarneo** [comment]
We pushed out a new release v3.0.2 to resolve this issue. Please let us know if you encounter any other issues. Thanks and apologies.
