### ISSUE TITLE
Typo in v3.0.2 release notes: it should say CocoaPods

### ISSUE THREAD

**Issue by yas375** [mixpanel/mixpanel-iphone#560]
![2016-08-04_1026](https://cloud.githubusercontent.com/assets/217368/17411682/1f5ab380-5a2e-11e6-88b2-add96d0cb71b.png)

Thanks in advance :)

**Comment by yarneo** [comment]
You love that capital P :) Thanks!

**Comment by yas375** [comment]
It's a [name](https://twitter.com/alloy/status/449144567259234304) ¯\_(ツ)_/¯

Thanks for fixing it 👍
