### ISSUE TITLE
Files are included in iTunes/iCloud backup

### ISSUE THREAD

**Issue by vgurinovich** [mixpanel/mixpanel-iphone#565]
Hi,

We found out that some files are saved in the Library folder (event_bindings, variants, properties, people, events). Files in this folder are included in the iTunes/iCloud backup, unless marked as 'exclude from backup'.

This can be a reason for rejection by Apple, so I hope you can change this.

There are two solutions:

1. Mark folder and files with NSURLIsExcludedFromBackupKey. I.e. use this: BOOL success = [URL setResourceValue: [NSNumber numberWithBool: YES] forKey: NSURLIsExcludedFromBackupKey error: &error];
2. Store all files in Library/Caches.
More info: https://developer.apple.com/library/ios/qa/qa1719/_index.html

Cheers,
Valeria

**Comment by yarneo** [comment]
Thank you Valeria for letting us know! We will look into this and update accordingly for our next release.

**Comment by yarneo** [comment]
Issue is fixed in new release
