### ISSUE TITLE
Duplicate interface definition for class Mixpanel

### ISSUE THREAD

**Issue by serluca** [mixpanel/mixpanel-iphone#566]
**Integration Method:** CocoaPods 
**Xcode Version:** 7.3
**Library Version:** 3.0.2
**Platform:** iOS 
**Device:** All
**Language:** Swift and Objective-C

**Description:** 
The build fail when importing Mixpanel whit the error `Duplicate interface definition for class Mixpanel`.
It was working with the Mixpanel version 2.9.9

**Comment by yarneo** [comment]
Hey @serluca. Can you please make sure that you haven't got in your project perhaps the Mixpanel framework twice? It could be that another one was added manually and therefore there is a duplicate definition. As a test, you could remove the pod 'Mixpanel' from the podfile and issue another pod install. Then you can see if your project still has any Mixpanel Libraries there and if so remove them. Then you can add back the pod 'Mixpanel' in the Podfile and do another pod install.

**Comment by serluca** [comment]
HI @yarneo 

I deleted the derived data and cleaned the build folder and it worked, sorry about that.

**Comment by yarneo** [comment]
Glad it's working now! Closing the issue
