### ISSUE TITLE
Could not build module 'Mixpanel' && Include of non-modular header inside framework module 'Mixpanel'

### ISSUE THREAD

**Issue by taruntyagi946** [mixpanel/mixpanel-iphone#569]
**Integration Method:** CocoaPods
**Xcode Version:** Xcode 8 beta 4 and beta 6
**Library Version:** 3.0.2
**Platform:** iOS
**Device:** iPad 4G & iPhone 6 & Simulator
**Language:** Objective-C

[ ] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER)
Not sure it's related. NO.

**Description:**  
**Could not build module 'Mixpanel'**
**Include of non-modular header inside framework module 'Mixpanel'**

**Expected Behavior:** 
Should build normally like it does in Xcode 7.3 with iOS 9.

**Comment by yarneo** [comment]
Hey @taruntyagi946 thanks for reaching out. I have tried using Cocoapods with Objective-C for Xcode 8beta6 and am not seeing this issue.
May I ask if you are including Mixpanel like so in your appdelegate: #import "Mixpanel/Mixpanel.h"
If the problem still persists, try going to the Mixpanel framework in the Pods project and setting: Allow Non-modular includes in the Build Settings to yes.

Let me know if this helps

**Comment by marsepu** [comment]
@yarneo I'm seeing this because of MixpanelPrivate.h line 17
```#import <CommonCrypto/CommonDigest.h>```

Could this be because the `CommonCrypto` library isn't included in the Mixpanel pod spec file's list of dependency frameworks ??

**Comment by yarneo** [comment]
I've looked into this some more.
These are things I recommend doing:
1. Make sure you have latest CocoaPods installed (post v1.0)
2. Make sure if using a Swift project to add the use_frameworks! keyword in your Podfile
3. Use the latest Xcode or if you are using Xcode 8, use Xcode GM which was released today
4. Use the latest Mixpanel SDK version (3.0.3)
5. If problem persists, delete your DerivedData, Build folder, and clean project. 

We haven't encountered these issues, but we have heard that any of the above could possible cause this. Happy to know what you guys find, or if the problem still persists.

**Comment by marsepu** [comment]
@yarneo I'm using the Xcode 8 GM, CocoaPods 0.39, Mixpanel 3.0.3 and was able to build by setting the `Allow Non-modular` setting in my target to `YES`

**Comment by yarneo** [comment]
Thanks for the update 👍

**Comment by taruntyagi946** [comment]
`Allow Non-modular Includes In Framework Modules = YES`

does the trick for me. Thanks @yarneo

**Comment by yeftaandrea** [comment]
Hi @yarneo is the last version Mixpanel SDK version (3.0.3) only for Xcode 8 ? I have similar issue when i do upgrade to the last version using Xcode 7.3.1 .

**Comment by yarneo** [comment]
Hey @yeftaandrea , I don't think there should be any issues with Xcode 7.3.1. But at this point i strongly recommend to update to Xcode8 as Xcode 7.X is now outdated software.

**Comment by InteractiveLogic** [comment]
The important factor for resolving this for me was setting **Allow Non-modular Includes in Framework Modules** to "Yes" _in my app project target_, not in the Pods or Mixpanel targets. After I made that change, it started building successfully again. 

Hope this helps others with this issue!

**Comment by yeftaandrea** [comment]
Hi @yarneo @InteractiveLogic , i was setting **Allow Non-modular Includes in Framework Modules** to "Yes" in my app project target. But still have some issue like : 
1. Include of non-modular header inside framework module 'Mixpanel.Mixpanel'
2. Duplicate interface definition for class 'MixpanelPeople'
3. Property has a previous declaration
4. Couldn't build Objective-C module 'Mixpanel'

I was tried to @yarneo suggestion before, but still doesn't work. Previously, i'm uses 2.9.9 version. Always got these issues when i tried to update to the next version until the last version. It work as well when i tried to setup back to current version. Any solution guys? Thank you so much.

Note: I was tried many ways like do `pod deintegrate' , remove current version then setup with last version, remove codes in bridging headers too. Still doesn't work.

**Comment by yarneo** [comment]
Hey @yeftaandrea , it sounds like you might have multiple integrations of Mixpanel in your project (due to issues 2,3).
I would try to delete the build folder and derived data initially, after you do pod deintegrate make sure the Pods folder and the xcworkspace are removed. Then go into your workspace and search for Mixpanel in the build settings, if it shows somewhere, remove it. After that go into the General tab in your workspace and make sure you don't have Mixpanel in your linked frameworks or embedded frameworks. After you have removed all of Mixpanel in your project, then do pod install.

Let me know if that helps

**Comment by yeftaandrea** [comment]
Still doesn't work @yarneo

**Comment by yarneo** [comment]
@yeftaandrea thanks for trying the steps. At this point it would be hard for me to continue debugging this issue without seeing the problem 1st hand. If you wish me to help you further, please send your project and an explanation of the problem to support@mixpanel.com and then either me or my colleague can have a look and find the underlying problem. Thanks!

**Comment by yarneo** [comment]
@marsepu @taruntyagi946 I tried to look further into this issue, and it seems to occur if you have a Cocoapods version below 1.0.0 (like 0.39.0) and use the #use_frameworks! in your podfile.

After finding the cause, I put out a fix to remove the problematic include and from the next update to the SDK you should be able to build properly without having to set the Allow Non-Module incudes to YES.

**Comment by meekapps** [comment]
I am seeing the same issue using Cocoapods 1.0.0 with use_frameworks!
