### ISSUE TITLE
[3.0.3 Manual] Cannot build on Xcode 8.0

### ISSUE THREAD

**Issue by fdematraz** [mixpanel/mixpanel-iphone#574]
**Integration Method:** Manual
**Xcode Version:** 8.0
**Library Version:** 3.0.3
**Platform:** iOS
**Device:**  iPhone 5s
**Language:** Objective-C

**Description:** thrown error: Mixpanel/MixpanelPeople.m:15:1: Cannot synthesize weak property in file using manual reference counting

**Comment by yarneo** [comment]
Hey @fdematraz are you using Manual Retain-Release rather than Automatic Reference Counting in your project?

**Comment by yarneo** [comment]
Let me know if this helps: Set Build Settings -> Apple LLVM 7.1 - Language - Objective C -> Weak References in Manual Retain Release to YES

**Comment by fdematraz** [comment]
Thank you for answer @yarneo. Enabling " Weak References in Manual Retain Release" did the trick. I also had to add the WatchKit framework and change this line on **UIImage+MPAverageColor.m**:

_char colorIndices[kNumberOfHexColors] = {{0}};_
to
_char colorIndices[kNumberOfHexColors];
memset( colorIndices, 0, kNumberOfHexColors*sizeof(char) );_

**Comment by yarneo** [comment]
Thank you for the update @fdematraz, glad it helped ! I will look into changing that fix for the next release

**Comment by samzilverberg** [comment]
>char colorIndices[kNumberOfHexColors] = {0};
to
char colorIndices[kNumberOfHexColors];
memset( colorIndices, 0, kNumberOfHexColors*sizeof(char) );

@yarneo any chance this kind of change will be introduced soon?

the xcodebuild fails on platforms that cannot use the C99 c dialect for any reason (examples: remote platforms where build settings cannot be specified, or collides locally with some other code) 

toda merosh

**Comment by nicobytes** [comment]
I have the same error =>

![screen shot 2017-03-15 at 10 29 20 am](https://cloud.githubusercontent.com/assets/7611944/23956328/5d72f484-096a-11e7-8ac9-dc7c361bcbf3.png)

my config in xcode =>

![screen shot 2017-03-15 at 10 29 49 am](https://cloud.githubusercontent.com/assets/7611944/23956348/6982058a-096a-11e7-8a4d-83ca882a0fa1.png)

why?

**Comment by samzilverberg** [comment]
submitted https://github.com/mixpanel/mixpanel-iphone/issues/666
will wait a week or two to see if they will take care of this on their side, if not will change it in this plugin code
