### ISSUE TITLE
Add A/B Testing Ability to App Extensions

### ISSUE THREAD

**Issue by KiranPanesar** [mixpanel/mixpanel-iphone#575]
**Integration Method:** CocoaPods
**Xcode Version:** 8.0
**Library Version:** 3.0.3
**Platform:** iOS (iMessage App)
**Device:** Simulator
**Language:** Objective-C

**Description:** Holding down option + click does not show the app in the the Mixpanel A/B Testing dashboard.
**Expected Behavior:** The app extension should show up in the Mixpanel A/B Testing dashboard.

Looks like the code responsible for this behaviour is found here, [`Mixpanel.m:107`](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L107). I understand why we don't want to set up the `NSNotification` observers for the app lifecycle, but that method is also responsible for calling `-initializeGestureRecognizer` to configure the A/B testing gesture recogniser.

Is it desired behaviour to disable A/B testing on extensions?

**Comment by KiranPanesar** [comment]
Ah, the gesture recogniser is being added to the `[[UIApplication sharedApplication] keyWindow]`, which doesn't exist on an extension ([see here](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L930)).

**Comment by yarneo** [comment]
Hey @KiranPanesar, hope you are having a good day. I'm afraid we currently don't support A/B testing for App Extensions, but only tracking and people API calls. To implement such a thing we would probably need to understand the limitations that app extensions have on the way we implement the feature. As a first example,  [UIApplication sharedApplication] is unsupported in App Extension targets.

**Comment by KiranPanesar** [comment]
By manually calling `[[Mixpanel sharedInstance] performSelector:@selector(connectToABTestDesigner)]` in my extension, I was able to get the app to show up in the dashboard, [like so](https://cloud.githubusercontent.com/assets/1433713/18724116/daed93cc-8000-11e6-9378-a604ce718515.png). This gives me access to the "Developer Tweaks" which is all I needed.

I can now remove the hacky `-performSelector` and the A/B test is going to work just as I need.

So it seems that the only reason this feature is not available via an extension is because users can't use the basic A/B testing where you visually change elements on the screen.

**Comment by yarneo** [comment]
Even though you were able to set the Developer Tweaks in the editor, you still won't be able to fetch them through the app extension when you run the extension. The reason being is that app extensions don't support the Decide API call, which is what sends you over the tweaks, notifications, codeless bindings and more. So I wouldn't advise to do it that way because it isn't supposed to work

**Comment by KiranPanesar** [comment]
@yarneo Got it. Thanks for the info. Is there a way for me to submit a feature request for this? I'm sure many more developers will be needing this in the future.

**Comment by KiranPanesar** [comment]
Side note, I _was_ actually able to load the A/B tests on my device as a normal user would. But I'll put that aside for now as I don't want to ship something _that_ hacky to our users.

**Comment by yarneo** [comment]
You could open a new issue with the feature request and I can create a "feature request" tag to it, and we can see if more people reply to this thread and we can elevate the priority for this. I know iMessage apps are becoming hot right now, so I'll be happy to see if this becomes a highly requested thing. How does that sound?

**Comment by KiranPanesar** [comment]
@yarneo Sounds good. Can we just update this issue to be a "feature request"? Let me know if there is a structure I should follow for this.

**Comment by yarneo** [comment]
Sure, why don't u rename this issue to sound more like a feature request like: "Adding A/B Testing Capabilities for App Extensions" or something similar and we can work on that. There isn't any specific structure, that is up to you

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features, please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation and get the issue addressed. Sorry for the inconvenience.
