### ISSUE TITLE
Accessing mainScreen as class method vs. class property

### ISSUE THREAD

**Issue by meekapps** [mixpanel/mixpanel-iphone#576]
**Integration Method:** CocoaPods
**Xcode Version:** 8.0 (8A218a)
**Library Version:** 2.9.4 (can't update to 3.0.3)
**Platform:** iOS
**Device:** Simulator
**Language:** Objective-C

**Description:** 
I was just rejected for using mainScreen with the error that it is a non-public API. Xcode 8 introduced class properties as an Objective-C language feature, so I suspect that adopting the new class property accessor syntax (i.e. UIScreen.mainScreen) will solve the rejection. I'm using Mixpanel 2.9.4 (I can't seem to build 3.0.3 yet, different issue), but noticed that even in 3.0.3, class method access to mainScreen is still being used (i.e. [UIScreen mainScreen]). I'm unsure if using the old style in frameworks will lead to rejection, but either way, it wouldn't hurt to adopt the new syntax.

**Comment by yarneo** [comment]
Hey @meekapps, I wouldn't mind changing it in future to be a class property accessor, but by reading about it, it seems that is an Apple submission bug. Apple usually goes through a deprecation period with Objective-C syntax changes and not remove things in an instant. 

I am more concerned about why you cannot integrate the newest version, could you elaborate on that so I can help you with that? 
We noticed some people were able to solve this issue with changing Allow Non-modular Includes in Framework Modules to "Yes" in the build settings

**Comment by meekapps** [comment]
Fair enough, I filed a radar with Apple as well. My problem updating to 3.0.3 sounds similar to the one described in https://github.com/mixpanel/mixpanel-iphone/issues/569, which I see is closed. What was the resolution there? I do have "Allow Non-modular Includes..." set to YES on my main app target but was getting the same 3 errors described in in issue 569 so I rolled back to 2.9.4.

**Comment by yarneo** [comment]
Thanks for the quick reply @meekapps ! I have just recently sent out a possible fix for that: https://github.com/mixpanel/mixpanel-iphone/commit/f09863850ab6534b40c0384c65f0084795fd8be1
If it would be possible on your end, could you try integrating Mixpanel like so in your podfile, and let me know if it resolves your problem:
pod 'Mixpanel', :git => 'https://github.com/mixpanel/mixpanel-iphone.git'

If so, I'll be sure to push a new release either today or tomorrow

**Comment by yarneo** [comment]
Also, if you use use_frameworks! try to import Mixpanel as a framework, like so: @import Mixpanel; rather than #import <Mixpanel/Mixpanel.h>

**Comment by meekapps** [comment]
thanks a lot! looks like my problem is fixed when pod installing from master as you suggested. didn't have to change my imports to module-style, but that doesn't hurt either. cheers!

**Comment by yarneo** [comment]
Yay!! That's great to hear! I'll be sure to push a release ASAP. Thanks so much for helping with this.

**Comment by yarneo** [comment]
New release out with the fix!
