### ISSUE TITLE
iMessages App Extension Integration

### ISSUE THREAD

**Issue by mseijas** [mixpanel/mixpanel-iphone#578]
**Integration Method:** CocoaPods
**Xcode Version:** 8
**Library Version:** 3.0.4
**Platform:** iOS
**Device:** N/A
**Language:** Swift

**Description:** Unable to build when using `Mixpanel/AppExtension` pod for iMessages App Extension due to the following error `'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.`

Using the following as my Podfile:
```
target 'MyApp' do
  use_frameworks!
  pod 'Mixpanel'
end

target 'MessagesExtension' do
  use_frameworks!
  pod 'Mixpanel/AppExtension'
end
```

There are 11 build errors all referencing the same issue (`'sharedApplication' is unavailable`), however I see that this is only checked when the `MIXPANEL_APP_EXTENSION` preprocessor macro is undefined. What's interesting is that both the `Mixpanel-AppExtension` pod target and my project's `MessagesExtension` target both include this macro.

Any ideas?

**Comment by yarneo** [comment]
Hey @mseijas, as it seems I'm afraid, Cocoapods doesn't allow 2 different variants of the same framework, see: https://github.com/CocoaPods/CocoaPods/issues/5643#issuecomment-249175326

It seems to be an Apple submission bug with a radar open.
What I would suggest at this time is just have the pod 'Mixpanel/AppExtension' in both targets and let me know how that works for you.

The limitation of that is that if your main app uses our In-App Notifications, Surveys, Codeless Bindings, or A/B Testing, that will no longer be available.

Let me know how that goes.

**Comment by mseijas** [comment]
Sounds good - thanks for your help @yarneo !
