### ISSUE TITLE
Could not build Objective-C module after updating to Swift 3.0

### ISSUE THREAD

**Issue by wattson12** [mixpanel/mixpanel-iphone#584]
**Integration Method:** CocoaPods (via Segment-Mixpanel pod) v0.39.0
**Xcode Version:** 8.0
**Library Version:** 3.0.4
**Platform:** iOS 
**Device:** Simulator / iPad 
**Language:** Swift 

**Description:**
After updating my swift app to swift 3.0 / Xcode 8 I have been unable to import Mixpanel. The pod is integrated, and seems to be built as a framework but when I import mixpanel I have 2 errors:
- `Mixpanel.h file not found` (in MixpanelPrivate.h)
- `Could not build Objective-C module 'Mixpanel'` (shown wherever import is in my code)

This looks identical to this closed issue: https://github.com/mixpanel/mixpanel-iphone/issues/577 but the fix mentioned there was to change to the swift library. I am using mixpanel via a Segment integration (https://github.com/segment-integrations/analytics-ios-integration-mixpanel) so that isn't an option (I'll raise this issue there as well)

**Expected Behavior:** 
Mixpanel should be able to be imported in a swift 3 code base and used as it was from the swift 2.2 app

**Comment by yarneo** [comment]
hey @wattson12 , please update your cocoapods version at least to v1.0.0 (preferably v1.1.0 if using swift3 and xcode8), otherwise you will keep encountering this issue. Thanks!

**Comment by wattson12** [comment]
Thanks @yarneo, updating to cocoapods 1.1.0 worked 🎉
