### ISSUE TITLE
Callback in `joinExperimentsWithCallback` is called multiple times

### ISSUE THREAD

**Issue by rpranata** [mixpanel/mixpanel-iphone#585]
**Integration Method:** Manual
**Xcode Version:** Version 8.0 (8A218a)
**Library Version:** 3.0.3
**Platform:** iOS
**Device:** All
**Language:** Swift and Objective-C

[] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER)

**Description:** 

Call to [joinExperimentsWithCallback](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.h#L791) with bad network condition (or no network) results in callback called more than once

Is this an intended behaviour? I looked at [the method](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L1113) looks like the completion handler block is called at least once when error happens and then called again just before the method exits at the bottom.

**Expected Behavior:** 

I would expect the callback to only be called once in all situations

**Comment by pchien** [comment]
Thanks for pointing that out! It was a bug where the completion handler would be called an additional time with old information in the case of an error. It's been fixed in https://github.com/mixpanel/mixpanel-iphone/pull/587, and should come out in the next release.
