### ISSUE TITLE
Crash On -[Mixpanel archiveObject:withFilePath:]

### ISSUE THREAD

**Issue by JunjianHu** [mixpanel/mixpanel-iphone#594]
Use Mixpanel 3.0.3, I got this crash log : http://crashes.to/s/55c3a678378, How to fix it ?

**Comment by JunjianHu** [comment]
I add check data type function like this, but i still have the crash : http://crashes.to/s/d4bf3b8d706
`- (BOOL)checkDataType:(id)data{
    if (![data respondsToSelector:@selector(encodeWithCoder:)]) {
        return NO;
    }
    if ([data isKindOfClass:[NSArray class]]) {
        NSArray *array = data;
        for (id item in array) {
            if (![self checkDataType:item]) {
                return NO;
            }
        }
    }
    if ([data isKindOfClass:[NSDictionary class]]) {
        NSArray *array = [data allValues];
        for (id item in array) {
            if (![self checkDataType:item]) {
                return NO;
            }
        }
    }
    return YES;
}
`

**Comment by yarneo** [comment]
Hey @JunjianHu , thank you for doing that. we will spend some time trying to help you resolve this issue. Let me know if there is any more info you can provide us with. (I noticed you closed the crash, but i'm guessing it's still a problem?) Thanks

**Comment by yarneo** [comment]
Another question we have that could help us understand more. Are you inserting into the properties of your events you are tracking possibly custom classes that you implemented? Or is it only basic data types (NSString, NSNumber, etc.)? If it is in fact a custom class, i wonder if it might be related to the way you implemented the hashing for it or the way you encode it.

**Comment by JunjianHu** [comment]
No custom classes, last version I insert check selector: encodeWithCoder, but it still crash. To make crash rate down, I checked type(NSString, NSNumber, NSNull, NSArray, NSDictionary, NSDate, NSURL) before send it track, close it to see whether it happens in next version

**Comment by yarneo** [comment]
Thank you for doing all of this. We really appreciate the help! Let us know if the type check solves it for you. Looking forward to hearing if this was resolved when doing the check.

**Comment by yarneo** [comment]
Hey @JunjianHu , hopefully #601 can help with this issue as well.
