### ISSUE TITLE
Move AppExtension to its own pod

### ISSUE THREAD

**Issue by chillpop** [mixpanel/mixpanel-iphone#596]
**Integration Method:** CocoaPods / Carthage / Manual
**Xcode Version:** 8
**Library Version:** 3.0.4
**Platform:** iOS
**Device:** All
**Language:** Swift & Objective-C

[ ] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER)

**Description:** Unable to use AppExtension subspec and main Mixpanel spec side by side.  Due to the issue with Cocoapods not allowing multiple pods with the same name, it is not possible to add both the limited AppExtension version of the SDK and the full version of the SDK (as discussed in #578).

**Expected Behavior:** Some way to use the full version of the SDK in a primary app and the limited version of the SDK in an app extension.

**Feature Request:** Move the AppExtension spec to a new podspec file with a different name from the full SDK.  This would allow users to install both without conflicting framework names.

**Comment by pchien** [comment]
Hi @chillpop. Have you tried the steps @yarneo put in https://github.com/mixpanel/mixpanel-iphone/issues/572#issuecomment-249020192? Hopefully that works for you and also hopefully Cocoapods fixes the issue soon. Let me know if you still have issues with his version of Cocoapods.

**Comment by chillpop** [comment]
Running a custom fork of Cocopods is not an option I would want to pursue.  Based on this: https://github.com/CocoaPods/CocoaPods/issues/5643#issuecomment-249175326 it seems that Cocoapods does not believe this to be a bug on their side.

**Comment by ChristianAtEmoJam** [comment]
Same here, can't get Mixpanel to work in an app and a Message Extension at the same time. It does not seem like a Cocoapods bug, and I much prefer sticking to official Cocoapods releases.

**Comment by nickvelloff** [comment]
Has not worked since CocoaPods `1.0.1` ... you can `pod _1.0.1_ install` but we can't stick there forever. @chillpop is correct Cocopods does not see this as their issue.

**Comment by nickvelloff** [comment]
@pchien - If Mixpanel officially supports CocoaPods, and since **any** version past CocoaPods `1.0.1` which is **painfully** old (see June 2nd release) won't install this with an extension target, it would seem this is a **bug** and not feature request and should be given a bit more priority.

We are all either stuck on CocoaPods `1.0.1` _forever_ seemingly, or just give up on the extension all together which completely screws up our analytics. 

And CocoaPods has made it clear this is not their issue:

cc/ @neonichu states:

> In 1.0.1, pods declared for app extensions were never embedded in the host app, so essentially the pods you declared for the "ShareExtension" target didn't really matter.

and

> It is and has been for a long time impossible to have two different variants of the same framework for your app and your extension, because embedding frameworks into an extension will be rejected by iTunes Connect. The issue is solely about the error message, not about the error itself. If your goal is to have two different copies of the same framework, please file radars.

cc @eke @hannesstruss

**Comment by pchien** [comment]
Oh sorry about the lack of response. I've made a pull request for this https://github.com/mixpanel/mixpanel-iphone/pull/628. If all goes well it should be in the next version.
