### ISSUE TITLE
there is a logical error in file MPUIControlBinding.m

### ISSUE THREAD

**Issue by shiflymoon** [mixpanel/mixpanel-iphone#603]
in MPUIControlBinding.m the method of initWithEventName:onPath:andVerifyEvent: has a logic error.the code is the following below:
 if (_controlEvent & UIControlEventAllTouchEvents_) {
                verifyEvent = UIControlEventTouchDown;
            } else if (_controlEvent & UIControlEventAllTouchEvents_) {
                verifyEvent = UIControlEventEditingDidBegin;
         }
the logic of "if" statement is the same as the "else if",both of them are "controlEvent & UIControlEventAllTouchEvents"

**Comment by yarneo** [comment]
I'm so happy you found this! We will merge a fix ASAP. Thanks!

**Comment by yarneo** [comment]
Fixed in #604!
