### ISSUE TITLE
logging is always enabled

### ISSUE THREAD

**Issue by masawo** [mixpanel/mixpanel-iphone#608]
**Integration Method:** CocoaPods
**Xcode Version:** 8.1
**Library Version:** 3.0.6 
**Platform:** iOS
**Device:** Simulator / iPhone 6s
**Language:** Objective-C

**Description:** 
It seems that logging is enabled, in our every biuld scheme.

I think that there is a cause : https://github.com/mixpanel/mixpanel-iphone/pull/607

**Expected Behavior:** 
logging will turn on with Build Settings to `MIXPANEL_DEBUG=1`

**Comment by pchien** [comment]
@masawo thanks for letting us know. We'll put out a fix with the next release but for now `[[Mixpanel sharedInstance] setEnableLogging:NO]` should turn it off.
