### ISSUE TITLE
Umbrella header does not include 'Mixpanel+HostWatchOS.h'

### ISSUE THREAD

**Issue by kylejm** [mixpanel/mixpanel-iphone#611]
**Integration Method:** Carthage 
**Xcode Version:** 8.1
**Library Version:** v3.0.6
**Platform:** iOS 
**Device:** All
**Language:** Swift 

[x] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER)

**Description:** 
Getting the following warning when archiving our app
```
Umbrella header for module 'Mixpanel' does not include header 'Mixpanel+HostWatchOS.h'
```

**Expected Behavior:** 
No warning

**Comment by pchien** [comment]
Hi @kylejm. We deleted that header in a recent version. It looks like this is an issue with either XCode or Carthage caching. Deleting DerivedData and Carthage's cache folder and then rebuilding with Carthage worked for me. See https://github.com/Carthage/Carthage/issues/463#issuecomment-102524543. I've also reuploaded the framework.zip that Carthage produces in case that doesn't work for you. Let me know if this is still an issue!
