### ISSUE TITLE
Encoding "+" in query string (distinct_id parameter for decide endpoint)

### ISSUE THREAD

**Issue by bejar37** [mixpanel/mixpanel-iphone#618]
**Integration Method:** CocoaPods
**Xcode Version:**  8.1
**Library Version:** 3.0.5
**Platform:** iOS
**Device:** Simulator / iPad / iPhone 6s
**Language:**  Objective-C

[ NO] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER)

**Description:**
Decide does not correctly encode `distinct_id`s that contain `+`
A `distinct_id` like `"123+4"`, because of `NSURL`, is encoded in the query string without encoding `"+"` to `"%2B"`. Mixpanel interprets the `"+"` as `" "`, which is not what we want.
**Expected Behavior:** 
Either the mixpanel SDK should make sure to encode the `"+"` as `"%2B"` for the tracking ID when it's used as a query parameter, or the mixpanel backend should  ignore whitespace inside tracking ids.

**Comment by pchien** [comment]
@bejar37 thanks for pointing that out. We should have a fix in the next release.
