### ISSUE TITLE
Umbrella header for module 'Mixpanel' does not include header 'Mixpanel+HostWatchOS.h'

### ISSUE THREAD

**Issue by Timac** [mixpanel/mixpanel-iphone#619]
**Integration Method:** Manual
**Xcode Version:** 8.2 beta (8C30a)
**Library Version:** 3.0.7
**Platform:** iOS
**Device:** iPad / iPhone
**Language:** Objective-C

**Description:** 
When you compile an app with -Wincomplete-umbrella and link to Mixpanel 3.0.7, you will see the warning:
<module-includes>:1:1: warning: umbrella header for module 'Mixpanel' does not include header 'Mixpanel+HostWatchOS.h' [-Wincomplete-umbrella]

**Expected Behavior:** No warning

**Comment by pchien** [comment]
Hi @Timac. This seems really similar to https://github.com/mixpanel/mixpanel-iphone/issues/611. We deleted `Mixpanel+HostWatchOS.h` in a recent version, and it seems like Xcode may be caching it. Deleting DerivedData fixed the issue last time. Let me know if it doesn't work.

**Comment by Timac** [comment]
The problem is that the header file Mixpanel+HostWatchOS.h is still in Mixpanel.framework/Headers/ folder but is not referenced in the module.modulemap:

framework module Mixpanel {
    umbrella header "Mixpanel.h"
    export *
    module * { export * }
    
    module MPTweak {
        header "MPTweak.h"
        header "MPTweakInline.h"
        header "MPTweakInlineInternal.h"
        header "_MPTweakBindObserver.h"
        header "MPTweakStore.h"
        export *
    }
}

If Mixpanel+HostWatchOS.h has really been deleted, you should remove the header from the Headers folder.

**Comment by pchien** [comment]
As far as I can tell `Mixpanel+HostWatchOS.h` no longer exists in the repository and also is not referenced in any files. Are you sure deleting DerivedData, cleaning, etc didn't help? I suspect Xcode is caching something in your build process.

**Comment by Timac** [comment]
It is not a caching problem on my side.
Here are the steps to reproduce:

1- Download the precompiled Mixpanel.framework 3.0.7:
https://github.com/mixpanel/mixpanel-iphone/releases/download/v3.0.7/Mixpanel.framework.zip

2- Unzip and open the folder Carthage/Build/iOS/Mixpanel.framework/Headers/

Result: Note the presence of the file Mixpanel+HostWatchOS.h

Expected result: Mixpanel+HostWatchOS.h should be in the Headers folder.

Workaround: Manually delete this file as it is not necessary.

**Comment by pchien** [comment]
Ah sorry the caching issue was on my end. I'll try to be more careful about that in the future. I've reuploaded 3.0.7's framework.zip so it should no longer have the issue. Thanks for letting me know!

**Comment by fanglinliu** [comment]
This issue is still exist in MixPanel.framework 3.1.2
https://github.com/mixpanel/mixpanel-iphone/releases/download/v3.1.2/Mixpanel.framework.zip
The file file Mixpanel+HostWatchOS.h still exist in v3.1.3
