### ISSUE TITLE
Xcode 8.2 error Multiple methods named "initWithType" found with mismatched result

### ISSUE THREAD

**Issue by burakketen** [mixpanel/mixpanel-iphone#624]
When we try to compile this library with the default settings for iOS 10 or iOS 9 (Xcode 8.2.1), the following error is generated in **MPABTestDesignerSnapshotRequestMessage**, **MPDesignerEventBindingMessage** and a lot of class.

`
MPABTestDesignerSnapshotRequestMessage..m:20: Multiple methods named 'initWithType:' found with mismatched result, parameter type or attributes`

`MPDesignerEventBindingMessage.m:60: Multiple methods named 'initWithType:' found with mismatched result, parameter type or attributes`

Do you have any thing what caused this problem ?

**Comment by pchien** [comment]
@burakketen what version of the library are you on? I tried on both master and 3.0.7 which is the latest and didn't get any errors compiling on Xcode 8.2.1.

**Comment by pchien** [comment]
We just released 3.0.8 with a potential fix (https://github.com/mixpanel/mixpanel-iphone/commit/f1e37f27d743ce299b9ae63e8c3b719d3b0d654b). Let me know if that helps or not!

**Comment by burakketen** [comment]
We are using the v2.9.9.001 branch for iOS 7 support. Thanks, the problem is solved.
