### ISSUE TITLE
warning issues 

### ISSUE THREAD

**Issue by fysteven** [mixpanel/mixpanel-iphone#630]
**Integration Method:** CocoaPods 
**Xcode Version:** 8.2.1
**Library Version:** 3.0.8
**Platform:** iOS 
**Device:** Simulator / iPhones
**Language:** Objective-C

[ ] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER)

**Description:** /Pods/Mixpanel/Mixpanel/MPSurveyNavigationController.h:20:27: 'MPSurveyNavigationController' is deprecated: Mixpanel surveys are deprecated as of release 3.0.8
**Expected Behavior:** 
No Warning issues

**Comment by pchien** [comment]
closing as this is already tracked by https://github.com/mixpanel/mixpanel-iphone/issues/629
