### ISSUE TITLE
Turn OFF Logging

### ISSUE THREAD

**Issue by Streebor** [mixpanel/mixpanel-iphone#633]
How can we disable logging? I had to go to the source code and disable it by changing MPSetLoggingEnabled(YES); to  MPSetLoggingEnabled(NO);

**Comment by pchien** [comment]
@Streebor which version of the library are you on? I think we got rid of that line entirely in a recent version of the library. Anyway, `[Mixpanel sharedInstance]. enableLogging = NO` is probably what you want.

**Comment by Streebor** [comment]
@pchien Thank you. I was looking for a preprocessor flag but this will do!
