### ISSUE TITLE
Runtime duplicate class warnings

### ISSUE THREAD

**Issue by nickvelloff** [mixpanel/mixpanel-iphone#635]
**Integration Method:** CocoaPods
**Xcode Version:** Version 8.2.1 (8C1002)
**Library Version:** Mixpanel (3.0.9) Mixpanel-AppExtension (3.0.9)
**Platform:** iOS
**Device:** Simulator + iPhone 6s+
**Language:** Swift

[ ] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER)

**Description:** 
Using `Mixpanel-AppExtension` in iOS share extension.
Warnings logged at runtime.
```
objc[12145]: Class Mixpanel is implemented in both /private/var/containers/Bundle/Application/E93F93BA-CE5F-4C3D-AEA5-E755BB2A8FE7/The Grid.app/Frameworks/Mixpanel_AppExtension.framework/Mixpanel_AppExtension (0x101bc4928) and /private/var/containers/Bundle/Application/E93F93BA-CE5F-4C3D-AEA5-E755BB2A8FE7/The Grid.app/Frameworks/Mixpanel.framework/Mixpanel (0x101b2db48). One of the two will be used. Which one is undefined.
objc[12145]: Class MixpanelPeople is implemented in both /private/var/containers/Bundle/Application/E93F93BA-CE5F-4C3D-AEA5-E755BB2A8FE7/The Grid.app/Frameworks/Mixpanel_AppExtension.framework/Mixpanel_AppExtension (0x101bc4978) and /private/var/containers/Bundle/Application/E93F93BA-CE5F-4C3D-AEA5-E755BB2A8FE7/The Grid.app/Frameworks/Mixpanel.framework/Mixpanel (0x101b2dbe8). One of the two will be used. Which one is undefined.
objc[12145]: Class MPNetwork is implemented in both /private/var/containers/Bundle/Application/E93F93BA-CE5F-4C3D-AEA5-E755BB2A8FE7/The Grid.app/Frameworks/Mixpanel_AppExtension.framework/Mixpanel_AppExtension (0x101bc49c8) and /private/var/containers/Bundle/Application/E93F93BA-CE5F-4C3D-AEA5-E755BB2A8FE7/The Grid.app/Frameworks/Mixpanel.framework/Mixpanel (0x101b2e548). One of the two will be used. Which one is undefined.
```

**Expected Behavior:** 
No duplicate class warnings when used in main app and extension.

**Comment by pchien** [comment]
Hey @nickvelloff we're really busy with other stuff right now so we probably won't get to this for a couple weeks. Just for clarification, is it just the warning that shows up or does it fail to track/does other functionality fail on the app extension or the main app? Sorry for the delay.

**Comment by nickvelloff** [comment]
@pchien It is just that there are warnings. Thanks for the heads up.

**Comment by caitlin615** [comment]
I'm having this issue as well when I use the Mixpanel pod in the main app and Mixpanel-AppExtension in an embedded extension. This seems to have a bigger impact than just logging a warning. Since it says `One of the two will be used. Which one is undefined.`, the OS is just going to pick one of the classes to use (either from Mixpanel or Mixpanel-AppExtension) and I have no control over which one it uses. This leads to, potentially, not being able to access functionality that are excluded from Mixpanel-AppExtension from within the main app, if the OS chooses the wrong class to use. For example, sometimes I can't access the `showNotification()` function.

**Comment by nickvelloff** [comment]
@caitlin615 good point. 😨

**Comment by caitlin615** [comment]
I'm not sure if this is a cocoapod issue or can be handled by Mixpanel, but when I used a very simple Podfile that adds the Mixpanel pod to the main app and Mixpanel-AppExtension to the Today extension, I can see why the main app gets these errors and why it would be confused about which library to use:

```
platform :ios, '9.0'

target 'JackCo' do
  use_frameworks!
  pod 'Mixpanel'
end

target 'Today' do
  use_frameworks!
  pod 'Mixpanel-AppExtension'
end
```

When I looked at the generated `.xcconfig` file for the main app, it includes the `MIXPANEL_APP_EXTENSION` macro and other Mixpanel-AppExtension flags. It seems like it shouldn't be this way since the Mixpanel-AppExtension pod is only specified in the Today target.

```
FRAMEWORK_SEARCH_PATHS = $(inherited) "$PODS_CONFIGURATION_BUILD_DIR/Mixpanel" "$PODS_CONFIGURATION_BUILD_DIR/Mixpanel-AppExtension"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1 $(inherited) MIXPANEL_APP_EXTENSION
OTHER_CFLAGS = $(inherited) -iquote "$PODS_CONFIGURATION_BUILD_DIR/Mixpanel-AppExtension/Mixpanel_AppExtension.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/Mixpanel/Mixpanel.framework/Headers"
OTHER_LDFLAGS = $(inherited) -framework "Mixpanel" -framework "Mixpanel_AppExtension"
```

Again, not sure if this is a Cocoapod issue or if Mixpanel could resolve it

**Comment by caitlin615** [comment]
Also, here's my workaround for the time being in my Podfile:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'Pods-MyApp'
        puts "Removing Mixpanel macro MIXPANEL_APP_EXTENSION from #{target}"
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        new_xcconfig = xcconfig.sub(
          'MIXPANEL_APP_EXTENSION', '').sub(
          '"$PODS_CONFIGURATION_BUILD_DIR/Mixpanel-AppExtension"','').sub(
          '-framework "Mixpanel_AppExtension"','').sub(
          '-iquote "$PODS_CONFIGURATION_BUILD_DIR/Mixpanel-AppExtension/Mixpanel_AppExtension.framework/Headers"', '')

        File.open(xcconfig_path, "w") { |file| file << new_xcconfig }
      end
    end
  end
end
```

**Comment by pchien** [comment]
@caitlin615 does this fix the duplicate class warnings as well?

**Comment by caitlin615** [comment]
With that addition to my Podfile, the warnings no longer occur. I wouldn't say it's a fix though, more of workaround.

**Comment by pchien** [comment]
Oh interesting. The flags being put in both `xcconfig`s seems like a Cocoapods issue. The "Extensions" section on http://blog.cocoapods.org/CocoaPods-1.1.0/ suggests that we might have to have different naming for classes in the base framework and the app extension anyways, though if it's working for you so far maybe that info is out of date.

**Comment by yarneo** [comment]
Hey @nickvelloff @caitlin615 can you please try using `pod 'Mixpanel'` in your app target and `pod 'Mixpanel/AppExtension'` (not Mixpanel-AppExtension) in your app extension target in your Podfile. It should work when using Cocoapods 1.1.0+.

**Comment by nickvelloff** [comment]
@yarneo Hi.
Trying that I got back to this error:
`[!] The 'Pods-The Grid' target has frameworks with conflicting names: mixpanel.`

Cocoapods `1.2.0`
App: pod 'Mixpanel', '3.1.1'
Extension: pod 'Mixpanel/AppExtension', '3.1.1'

Should I point to a particular branch perhaps?

**Comment by yarneo** [comment]
Hey @nickvelloff could you please share the podfile with us? I am also curious to know what kind of app extension is this so I can re-test on our end; I was testing this with an iMessage extension. Also make sure you do a pod update :)

**Comment by yarneo** [comment]
Hey @nickvelloff , if you are using Swift in your project, I also suggest having a look at our Swift implementation, which now also supports app extensions: https://github.com/mixpanel/mixpanel-swift Thanks!

**Comment by nickvelloff** [comment]
@yarneo yes the project is Swift. That's awesome as last time I looked they were not supported. This will be much better! Thanks for the heads up!

**Comment by pchien** [comment]
Closing this since the Swift library has reached parity and it looks like this was specific to projects in Swift using the Objective C library.
