### ISSUE TITLE
Too many symbol files - These symbols have no corresponding slice in any binary

### ISSUE THREAD

**Issue by evgeniyd** [mixpanel/mixpanel-iphone#637]
**Integration Method:** CocoaPods
**Xcode Version:** 8.2.1 (8C1002)
**Library Version:** 3.0.6
**Platform:** iOS
**Device:** iPhone 6 Plus
**Language:** Swift
**CocoaPods Version:** 1.0.1

[ ] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER) - NO

**Description:** 

While submitting the app to iTunesConnect, we encountered the issue: 

> Too many symbol files - These symbols have no corresponding slice in any binary [6CC7C205-D2BB-374B-B35C-8610F13F1C6B.symbols, D606A810-1E50-32FC-9B04-BC4AC9668CAF.symbols]

A [quick check](http://stackoverflow.com/a/38461479/1492173) for `.dSYM`, yielded that the Mixpanel produces that `.symbols`

```
UUID: 34D88E0F-CD2D-3E38-A848-AA543964ABCF (armv7) Mixpanel.framework 1.dSYM/Contents/Resources/DWARF/Mixpanel
UUID: 7FB18318-F0D7-36DE-B576-EC31FCE2B677 (arm64) Mixpanel.framework 1.dSYM/Contents/Resources/DWARF/Mixpanel
UUID: D606A810-1E50-32FC-9B04-BC4AC9668CAF (armv7) Mixpanel.framework.dSYM/Contents/Resources/DWARF/Mixpanel
UUID: 6CC7C205-D2BB-374B-B35C-8610F13F1C6B (arm64) Mixpanel.framework.dSYM/Contents/Resources/DWARF/Mixpanel
```

I assume, that the CocoaPods configuration is wrong here.

The project has two targets: the app and the appex. The Podfile configuration is this:

```
target 'App' do
    use_frameworks!
# ...
    pod 'Mixpanel/Mixpanel'
    pod 'Mixpanel/AppExtension'
# ...
end

target 'Appex' do
    use_frameworks!
# ...
    pod 'Mixpanel/AppExtension'
# ...
end
```

The README suggests to use `pod 'Mixpanel'` for iOS and `pod 'Mixpanel-AppExtension'` for an appex, so I've changed the Podfile to the following and hit `pod install`:

```
target 'App' do
    use_frameworks!
# ...
    pod 'Mixpanel'
# ...
end

target 'Appex' do
    use_frameworks!
# ...
    pod 'Mixpanel-AppExtension'
# ...
end
```

Is this correct? 
Will there be any functionality missed due to this setup?
Could you please suggest the correct setup in this case? 

**Expected Behavior:** 

Mixpanel does not produce "too many symbols"

**Comment by pchien** [comment]
Your setup with Mixpanel-AppExtension looks correct to me. You haven't version locked Mixpanel-AppExtension, right? It only exists as of 3.0.9 - just double checking since you said you're using 3.0.6. Otherwise perhaps CocoaPods needs to be updated? I'm really not sure but I know it's in the CocoaPods specs repo [`here`](https://github.com/CocoaPods/Specs/tree/master/Specs/4/4/e/Mixpanel-AppExtension/3.0.9).

**Comment by evgeniyd** [comment]
Hi @pchien 

Thank you very much for assistance.
Knowing the CocoaPods version in README would be a huge help, BTW. I am on v1.0.1 right now.

Upon first build, after updating Mixpanel to 3.0.9, with the configuration above, I've got this:

    import Mixpanel /// <=== No such module 'Mixpanel'

After doing the conditional import 

    #if EXTENSION_TARGET
    import Mixpanel_AppExtension
    #else
    import Mixpanel
    #endif

...the issue seems to go away.

And, finally, the initial issue with "too many symbols" is gone.

**Comment by evgeniyd** [comment]
I am reopening it, because, while "too many symbols" is gone, upon launching the app on the device, I got:

    dyld: Library not loaded: @rpath/Mixpanel_AppExtension.framework/Mixpanel_AppExtension
      Referenced from: /private/var/containers/Bundle/Application/18566837-6060-48D1-9774-B7D0B3CC2C7C/SKB.app/PlugIns/SKB.appex/SKB
      Reason: image not found

So, it seems now to me, that we still have to add `pod 'Mixpanel-AppExtension'` to the `App` target:

```
target 'App' do
    use_frameworks!
# ...
    pod 'Mixpanel'
    pod 'Mixpanel-AppExtension'
# ...
end

target 'Appex' do
    use_frameworks!
# ...
    pod 'Mixpanel-AppExtension'
# ...
end
```

Note, that I have a "Remove Framework folder" Run Script build stage as suggested by [this CocoaPods issue](https://github.com/CocoaPods/CocoaPods/issues/4203).

Also, note that [Instructions](https://github.com/ephread/Instructions) works when the `Podfile` has this config:

```
target 'App' do
    use_frameworks!
# ...
    pod 'Instructions', :git => 'https://github.com/ephread/Instructions.git', :branch => 'master'
# ...
end

target 'Appex' do
    use_frameworks!
# ...
    pod 'Instructions/AppExtensions', :git => 'https://github.com/ephread/Instructions.git', :branch => 'master'
# ...
end
```

**Comment by benasher44** [comment]
Hi @evgeniyd! I happened to see this issue linked to a CocoaPods issue, and I noticed you're using CocoaPods 1.0.1. You'll need to upgrade to at least 1.1.0 to get your pods working with app extensions. Have a great day!

**Comment by evgeniyd** [comment]
Hi @benasher44 

Do you happen to know what's changed since then in CocoaPods, that might help to resolve the issue?

**Comment by benasher44** [comment]
It properly ensures extension pods are in the right place to be loaded by dyld at launch time.

**Comment by benasher44** [comment]
The blog post mentions some of the details around updates to framework handling: http://blog.cocoapods.org/CocoaPods-1.1.0/

**Comment by yarneo** [comment]
Hey @evgeniyd let us know if it works to use `pod 'Mixpanel'` in your app target and `pod 'Mixpanel/AppExtension'` in your app extension target in your Podfile. It should work.

**Comment by yarneo** [comment]
Hey @evgeniyd , if you are using Swift in your project, I also suggest having a look at our Swift implementation, which now also supports app extensions: https://github.com/mixpanel/mixpanel-swift Thanks!

**Comment by evgeniyd** [comment]
Hi @yarneo 

First of all, we have migrated to CocoaPods 1.1.0 and applied the suggested separation of podspecs for the app and the appex. It works great!

Regarding the Mixpanel migration to Mixpanel Swift - we have already considered this option and will do the migration soon.

Thank @yarneo @benasher44
