### ISSUE TITLE
Crash on iOS 9 app start - MPTweakInLine

### ISSUE THREAD

**Issue by jblorenzo** [mixpanel/mixpanel-iphone#639]
**Integration Method:** CocoaPods
**Xcode Version:** 7.3.1
**Library Version:** 3.0.7
**Platform:** iOS 9
**Device:** Simulator and iPhone 6
**Language:** Objective-C and Swift

[YES] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER)

**Description:** App crashes on startup with EXC_BAD_ACCESS
**Expected Behavior:** 
App doesn't crash

When debugging and address sanitizer is enabled, it breaks at:
MPTweakLine.m line 134:
            NSString *name = [NSString stringWithString:*entry->name];
I printed the value for entry:
(lldb) p *entry
(mp_tweak_entry) $14 = {
  name = 0x0000000000000000
  value = 0x0000000000000000
  min = 0x0000000000000000
  max = 0x0000000000000000
  encoding = 0x0000000000000000
}

It seems that the loop count is very large compared to how many tweaks there actually are.

**Comment by yarneo** [comment]
Thanks for the report and info @jblorenzo ! The Tweaks part in our library is actually taken from https://github.com/facebook/Tweaks . It is unfortunate that you are seeing this crash. What we intend to do is to update the entire codebase for our Tweaks implementation eventually so we are in sync with their repo's latest updates. What I suggest for now is to remove the tweaks if they are causing you crashes (from code and project), and we will work on getting to the source of this problem as soon as possible. Thanks!

**Comment by jblorenzo** [comment]
Hey Yarden, thanks for the response. Will try to remove just the tweaks
files on our next release.

**Comment by markhim** [comment]
Hey, we experience this as well...

Any updates on that?

**Comment by jblorenzo** [comment]
What I did was to remove the MPTweaks related files since we are not using
tweaks anymore. Other than that, no updates from Mixpanel yet

On Fri, Jun 30, 2017 at 11:43 PM, Mark Himmelsbach <notifications@github.com

**Comment by markhim** [comment]
Thanks @jblorenzo 

@yarneo this affects 50% of the iOS9 population therefore is highly critical for us! And it is open since February... Can I expect a release this week?

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features, please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation. Sorry for the inconvenience.
