### ISSUE TITLE
[3.0.9] Mystery EXC_BAD_ACCESS memory crash 

### ISSUE THREAD

**Issue by adomanico** [mixpanel/mixpanel-iphone#640]
**Integration Method:** CocoaPods
**Xcode Version:**  8.2
**Library Version:** 3.0.9
**Platform:** iOS 
**Device:** iPhone 6 iOS 10.2.1
**Language:** Swift

**Description:** 

We are seeing a memory related crash. We do not have any specific reproduction steps and nothing in our stack. Sorry for the limited info. 

```
Crashed: com.mixpanel.2694d4410c3ec576cd5860eecb79338a.0x103526600
EXC_BAD_ACCESS 0x0075746928285e32
0  libcoretls_cfhelpers.dylib     0x75746928285e30 (Missing)
1  libdispatch.dylib              0x1833661fc _dispatch_call_block_and_release + 24
2  libdispatch.dylib              0x1833661bc _dispatch_client_callout + 16
3  libdispatch.dylib              0x1833743dc _dispatch_queue_serial_drain + 928
4  libdispatch.dylib              0x1833699a4 _dispatch_queue_invoke + 652
5  libdispatch.dylib              0x1833748d8 _dispatch_queue_override_invoke + 360
6  libdispatch.dylib              0x18337634c _dispatch_root_queue_drain + 572
7  libdispatch.dylib              0x1833760ac _dispatch_worker_thread3 + 124
8  libsystem_pthread.dylib        0x18356f2a0 _pthread_wqthread + 1288
9  libsystem_pthread.dylib        0x18356ed8c start_wqthread + 4
```

**Expected Behavior:** No crash

**Comment by pchien** [comment]
@adomanico do you have any symbolicated versions of this stack trace? How prevalent is this crash?

**Comment by adomanico** [comment]
This is actually from our symbolicated version from Fabric. On the crashed mixpanel thread this is all there was

**Comment by adomanico** [comment]
This crash was caught by our QA for an upcoming release.

**Comment by pchien** [comment]
Closing this because there isn't enough information for us to fix it. Feel free to reopen if this happens again.
