### ISSUE TITLE
I can not find MPTagNibs.rb script

### ISSUE THREAD

**Issue by ganvinalix** [mixpanel/mixpanel-iphone#643]

**Comment by pchien** [comment]
@ganvinalix I can't find that file in git history at all. What do you need it for? I only see it referenced at https://github.com/mixpanel/mixpanel-iphone/blob/42e5b1f8565e0b7616920c813158d6b08d26c2ad/Mixpanel/UIView%2BMPHelpers.m#L65. What's the use case you're trying to solve?

**Comment by ganvinalix** [comment]
@pchien  how to use mp_viewId  setting fixed custom viewid ,  https://github.com/mixpanel/mixpanel-iphone/blob/42e5b1f8565e0b7616920c813158d6b08d26c2ad/Mixpanel/UIView%2BMPHelpers.m#L65.

**Comment by pchien** [comment]
I'm honestly not sure what that comment is referencing, but it looks like in our demo project we set it as a "user defined runtime attribute" in the storyboard. If this works for you, go ahead and close this issue. Let me know if you have further questions!

![screen shot 2017-02-15 at 11 17 17 am](https://cloud.githubusercontent.com/assets/1988432/22991284/9d2c42de-f370-11e6-9cfe-bdc20ed0d672.png)

**Comment by ganvinalix** [comment]
@pchien NO，THX！
