### ISSUE TITLE
HOW DO I TRACK PAGE VIEWS WITH AUTOTRACK?

### ISSUE THREAD

**Issue by ganvinalix** [mixpanel/mixpanel-iphone#645]
I have  tryed this https://mixpanel.com/help/questions/articles/how-do-i-track-page-views-with-autotrack ,not work for me. I found the code "checkForDecideResponseWithCompletion" at mixpanel.m.
`NSDictionary *config = object[@"config"];
                if (config && [config isKindOfClass:NSDictionary.class]) {
                    NSDictionary *validationConfig = config[@"ce"];
                    if (validationConfig && [validationConfig isKindOfClass:NSDictionary.class]) {
                        self.validationEnabled = [validationConfig[@"enabled"] boolValue];
                        NSString *method = validationConfig[@"method"];
                        if (method && [method isKindOfClass:NSString.class]) {
                            if ([method isEqualToString:@"count"]) {
                                self.validationMode = AutomaticEventModeCount;
                            }
                        }
                    }
                }`
NSDictionary *config = object[@"config"]; 
config is null. How can i get the object config infomation ?

**Comment by ganvinalix** [comment]
My project setting
![image](https://cloud.githubusercontent.com/assets/2315308/23090341/38a26d52-f5d7-11e6-8e29-2b2d21e01bb5.png)

**Comment by yinfeiru** [comment]
`Autotrack` is a feature for websites not for mobile.

**Comment by yinfeiru** [comment]
Instead, you might want to try Codeless. You can find it by clicking on your account name on the top right and hit `set up tracking`. If you have your ios sdk properly integrated, you can then hit `ios` and follow the instructions to connect.

Please email support@mixpanel.com if you need more help.
