### ISSUE TITLE
How to generate path to give back client of iOS device

### ISSUE THREAD

**Issue by ganvinalix** [mixpanel/mixpanel-iphone#648]
When one btn is auto tracked, our sever will give back info
 {    
    path = "/ViewController/UIView/UIButton[(mp_fingerprintVersion >= 1 AND mp_varE ==  \"9731162c868f510cc2a7af5a0fdc062d5a38b641\")]";
}
I want know how to generate the path with client gived back json info?  Can some one help me? The path is simple and clear,just like the demo,UIButton->UIView->ViewController, I checked the json config info which I  sended to sever,I guess may be use "super view"  key ,btn when view to ViewController the link chain is missing. is it our server  used xpath to process the json config.
json config --> xml --> xpath ?

**Comment by 19kka** [comment]
I think "/ViewController/UIView/UIButton" is from snapshotMessage.serializedObjects what you send to server.

mp_varE is for some elements that have text .

Call  `mp_encryptHelper([self mp_text]) // do SALT-SHA256`

ref: #646 

Let's discuss
