### ISSUE TITLE
Update Your Readme

### ISSUE THREAD

**Issue by jose920405** [mixpanel/mixpanel-iphone#649]
For `App Extension` is `Mixpanel/AppExtension` not `Mixpanel-AppExtension`

**Comment by yarneo** [comment]
hi @jose920405 , did you find out that `Mixpanel/AppExtension` works for you well with your app extension?

**Comment by jose920405** [comment]
@yarneo yes it did

**Comment by yarneo** [comment]
We actually found out that `Mixpanel-AppExtension` is the better way if one is to use also `Mixpanel` in his app target along with the app extension. Closing this, thanks!
