### ISSUE TITLE
The file Mixpanel+HostWatchOS.h still exist in MixPanel.framework 3.1.2

### ISSUE THREAD

**Issue by fanglinliu** [mixpanel/mixpanel-iphone#657]
**Integration Method:** CocoaPods / Carthage / Manual
**Xcode Version:*8.2* 
**Library Version:*3.1.2* 
**Platform:** iOS 10 / App Extension / watchOS / tvOS
**Language:** Swift / Objective-C
**Description:** 
There is a warning to link to this framework
https://github.com/mixpanel/mixpanel-iphone/releases/download/v3.1.2/Mixpanel.framework.zip. 
**Expected Behavior:** 
No warning
**Root Cause**
The file Mixpanel+HostWatchOS.h is not deleted in the HEADER folder.

Steps to reproduce this issue.
1- Download the precompiled Mixpanel.framework 3.1.2:
https://github.com/mixpanel/mixpanel-iphone/releases/download/v3.1.2/Mixpanel.framework.zip
2- Unzip and open the folder Carthage/Build/iOS/Mixpanel.framework/Headers/

Result: Note the presence of the file Mixpanel+HostWatchOS.h

Expected result: The file Mixpanel+HostWatchOS.h shouldn't exist.

Workaround: Manually delete this file as it is not necessary.

**Comment by pchien** [comment]
Hi @fanglinliu. Sorry that happened. There's an issue with Carthage caching on our end that we haven't figured out the best solution for yet. I've rebuild it and reuploaded the zip to 3.1.2 so it should work for you now.
