### ISSUE TITLE
MixPanel on Xcode 7 - doesn't work - any workaround?

### ISSUE THREAD

**Issue by LtrDan** [mixpanel/mixpanel-iphone#661]
**Integration Method:** CocoaPods
**Xcode Version:7.3.1
**Library Version: Latest
**Platform:** iOS 
**Language:** Objective-C
**Description:** 
**Expected Behavior:** 

Installed Pod and getting: 

Pods/Mixpanel/Mixpanel/MPTakeoverNotificationViewController~ipad.xib: error: The document “(null)” requires Xcode 8.0 or later.
    Recovery Suggestion: This version does not support documents saved in the Xcode 8 format. Open this document with Xcode 8.0 or later.
Command /bin/sh failed with exit code 1

Thanks:)

**Comment by pchien** [comment]
@LtrDan were you trying to open the file or just to build? I think you should be able to build your project fine with Xcode 7 without opening the file. Otherwise, do any workarounds work for you? For example, have you tried http://stackoverflow.com/questions/37851459/the-document-main-storyboard-requires-xcode-8-0-or-later ?

**Comment by LtrDan** [comment]
Yea tried only to build..
Solved -> opened all XIB files and deleted "<capability name="documents saved in the Xcode 8 format" minToolsVersion="8.0"/>"

**Comment by pchien** [comment]
Sounds good. Let me know if you run into any more issues!

**Comment by efalkenberg** [comment]
We ran into the same issue today and of course deleting the files helper but it will appear again on next pod update. Can you please make this available for Xcode7? The required steps are explained here: http://stackoverflow.com/questions/37851459/the-document-main-storyboard-requires-xcode-8-0-or-later
