### ISSUE TITLE
About the cache EventBindings

### ISSUE THREAD

**Issue by XL-Andrew** [mixpanel/mixpanel-iphone#663]
**Integration Method:cocoapods
**Xcode Version:8.3.1
**Library Version:2.9.9
**Platform:iOS
**Language:Objective-C
**Description:about the cache EventBindings

I use a week later, inadvertently found "cache evenBindings" cache data is not accurate. I just track a event. After numerous tests used, I suddenly found in the cache eventBindings. Count is 12!!!!!!What reason be?
![1f998c54-f2d6-4ddf-a12c-0ad9b577d1d9](https://cloud.githubusercontent.com/assets/17964664/24987863/c80acb24-2034-11e7-97ab-384f61d53d36.png)

**Comment by cassiegamm** [comment]
Hi @XL-Andrew,

I believe this bug should have been fixed in [v3.0.0](https://github.com/mixpanel/mixpanel-iphone/releases/tag/v3.0.0). Are you able to upgrade to a v3.0 or higher?

**Comment by pchien** [comment]
Closing due to no response. Hopefully upgrading fixed the issue.
