### ISSUE TITLE
Xcode thread sanitizer warning

### ISSUE THREAD

**Issue by DarkoDamjanovic** [mixpanel/mixpanel-iphone#664]
**Integration Method:** CocoaPods
**Xcode Version: 8.3 
**Library Version: 3.1.2
**Platform:** iOS 
**Language:** Swift with Objective-C Mixpanel SDK
**Description: The Xcode thread sanitizer reports a problem regarding a race condition in Mixpanel.m file (iOS SDK). Please see the attached screenshots. It seems that the logging macro is reading self" at the same time self" is changed by setEnableLogging.
**Expected Behavior: No warnings from the Xcode thread sanitizer.

[Screenshots.zip](https://github.com/mixpanel/mixpanel-iphone/files/934373/Screenshots.zip)

**Comment by pchien** [comment]
v3.1.6 was just released with the fix for this.
