### ISSUE TITLE
MPAverageColor C99 dialect probs

### ISSUE THREAD

**Issue by samzilverberg** [mixpanel/mixpanel-iphone#666]
Hi there, maintainer of [cordova-mixpanel-plugin](https://github.com/samzilverberg/cordova-mixpanel-plugin) here.
Some users are experiencing issues with building their code which boils down to usage of C99 dialect at the following point in code:
```
UIImage+MPAverageColor.m:
char colorIndices[kNumberOfHexColors] = {0};
```

Some of them are able to change it manually from xcode itself but some have no solution as they are building using a cloud platform or are just having a dialect collision with another lib they are using.

Are you using C99 intensively? 
if not, would you consider changing to something like this:
```
char colorIndices[kNumberOfHexColors];
memset( colorIndices, 0, kNumberOfHexColors*sizeof(char) ); //or colorIndices[0] = 0;
```

it should still work but would make the code more "vanilla" i.e. more compatible with other libs code.

**Comment by pchien** [comment]
Hi @samzilverberg. I'd be happy to make that change. Do you know if that's the only place C99 is causing issues for you? I don't know off the top of my head where we're using C99 and would like to fix the issue for you in one release.

**Comment by samzilverberg** [comment]
as of a couple of months ago, this was the only place which was using C99 syntax.
some users have manually changed the code back then for their own projects and got it to compile.

nowadays i'm not sure.

you could just give it a try i guess, something like:
- compile/build the lib with a xcode build flag to use a stricter dialect
- see it fail because of the current code
- change and compile again
- success = no more usage, fail = you'll see the other C99 usages

would you mind trying that? i'm pretty sure it will succeed on the first try :)

**Comment by pchien** [comment]
Ah thanks. Looked like it was using GNU syntax which caused an error when compiling on C99. I wasn't able to test what happened with C89 because a lot of stuff like NSAssert couldn't compile. Anyway, I opened a PR which should fix it.

**Comment by pchien** [comment]
Hey @samzilverberg just merged the fix into master. If you can't wait, I'd suggest pointing to that for now. Otherwise, we'll probably release a new version of the sdk in a few weeks that will include the fix.

**Comment by samzilverberg** [comment]
ty. I'll wait for the official release.

**Comment by pchien** [comment]
Fixed in the latest release.
