### ISSUE TITLE
Impossible to identify events and people separately

### ISSUE THREAD

**Issue by idpaterson** [mixpanel/mixpanel-iphone#67]
While I agree that it was confusing to have to identify events and people separately (#43), the fix (6194f18a3d04e732d62cd93b73e2a569017e759f) seems to eliminate the ability to give a separate identifier for events and people. A simple use case for a separate identifier is:

1. User installs the app
    * event identifier is tied to the device
    * people identifier is `nil` because they are not logged in
2. User logs in
    * event identifier is still tied to the device
    * people identifier corresponds to a different user id

In Mixpanel, we have to be able to make a funnel to track conversion from installation to log in to activity within an app. Requiring the event identifier to change when the user logs in is unacceptable because it will make this type of funnel impossible. Furthermore, the Mixpanel People interface shows events based on an identifier that can be distinct from the people identifier. While that unfortunately does not support multiple devices per user it at least allows us to see the activity of the user from their most recent device, with combined people statistics from all their devices.

It does not seem to be possible to set `$distinct_id` as a property on People because it will be overwritten by the value of the `distinctId` property. I apologize if I did not notice a way that the current approach accounts for this.

**Comment by samgreen** [comment]
This should be resolved with the `alias` and `identify:` methods that we provide with the SDK. You can review the documentation for these methods here: https://mixpanel.com/help/reference/ios#user-identity
