### ISSUE TITLE
In App Notification text content not being displayed.

### ISSUE THREAD

**Issue by mnmaraes** [mixpanel/mixpanel-iphone#670]
**Integration Method:** Manual
**Xcode Version:** 8.3.2
**Library Version:** 3.1.2 & 3.1.3 (Haven't tested version 3.1.1)
**Platform:** iOS
**Language:** Objective-C
**Description:** In App Notification text content not displaying at all. Changing the SDK to version 3.1.0 fixes the issue.
**Expected Behavior:** In App Notification text content should display.

**Comment by pchien** [comment]
Hi @mnmaraes I just tested it and it worked for me on the latest version. Could you give me more info on what's going wrong? Is the notification using custom, dark, or light? Did you choose the "hide text" option if it's custom? A link to your project/notification could also help (people who aren't Mixpanel employees would not be able to use the link).

**Comment by mnmaraes** [comment]
So, it seems that the full-screen IAN works just fine. 

The mini notification is the one that fails to show the text in the mentioned versions. I tested with every type of theme (light, dark and custom) and they all fail to show the text. The same notification will display correctly on version 3.1.0.

Also, this shouldn't really matter, but the project is a React Native project.

If you need me to, I can try to put together an example project to showcase the issue.

**Comment by pchien** [comment]
Thanks @mnmaraes. I've opened a pr with the fix https://github.com/mixpanel/mixpanel-iphone/pull/671. It should be out in the next version which should be within a week or two.

**Comment by Bjornftw** [comment]
Same problem here. 

https://twitter.com/Bjornftw/status/860162688688820227

**Comment by pchien** [comment]
Fixed in the latest release.
