### ISSUE TITLE
CRASH - in [SRWebSocket stream:handleEvent:]

### ISSUE THREAD

**Issue by sivanmoshe** [mixpanel/mixpanel-iphone#674]
The crash occurs many times when the application is entering foreground

Attached is a stack trace file

[com.shutterfly.shutterflyuploader_issue_14290_crash_aa310dbb6ab9468f9fa0b32323c3abf4_0e7b1764414b11e79dfa56847afe9799_0_v2.txt](https://github.com/mixpanel/mixpanel-iphone/files/1029406/com.shutterfly.shutterflyuploader_issue_14290_crash_aa310dbb6ab9468f9fa0b32323c3abf4_0e7b1764414b11e79dfa56847afe9799_0_v2.txt)

**Comment by pchien** [comment]
@sivanmoshe what version of the library are you using?

**Comment by sivanmoshe** [comment]
we are using now 2.9.9.   :(

our mistake merging the pod file

I have updated to latest mix panel version, and we'll take it from there

**Comment by pchien** [comment]
OK good to know. Let me know if you have any other issues!
