### ISSUE TITLE
MPLogger.h

### ISSUE THREAD

**Issue by BaiCan** [mixpanel/mixpanel-iphone#679]
**Integration Method:** CocoaPods
**Xcode Version:8.0
**Library Version:** 
**Platform:** iOS
**Language:** Swift
**Description:** MPLogger.h in Swift, 'asl_add_log_file'is deprecated:first dprecated in iOS 10.0

**Comment by pchien** [comment]
Oh good to know. @BaiCan what settings did you have to see this warning? I don't see it normally in Xcode.

**Comment by BaiCan** [comment]
You can see this warning in the swift project

**Comment by BaiCan** [comment]
![image](https://user-images.githubusercontent.com/8268339/27016618-992b7cc2-4ee7-11e7-9dc8-ebe68845b78d.png)

**Comment by BaiCan** [comment]
![image](https://user-images.githubusercontent.com/8268339/27016656-05a22a54-4ee8-11e7-8ed9-36c03da04f29.png)

This is image

**Comment by pchien** [comment]
Oh okay. Interesting that it shows up in Swift but not Objective C afaik. In case you didn't know, we also have a swift library which has reached full parity which we recommend for swift projects. https://github.com/mixpanel/mixpanel-swift

**Comment by BaiCan** [comment]
Thank you

**Comment by jinghu-okta** [comment]
As an additional data point, I have an Obj-C project and I'm getting the same warnings
