### ISSUE TITLE
Bring over Mixpanel-swift extension solution to Mixpanel-iPhone

### ISSUE THREAD

**Issue by cerupcat** [mixpanel/mixpanel-iphone#688]
The swift library has replaced references of UIApplication with its own implementation in order to have single podspec/API that will work for both extensions and the main app (required for cocoapods use_frameworks!). It'd be nice to bring over this solution to the mixpanel-iPhone project. https://github.com/mixpanel/mixpanel-swift/commit/8552970e10d992b34665ae004669e3dd66366d20

**Comment by pchien** [comment]
@cerupcat we'll definitely do this at some point.

**Comment by cerupcat** [comment]
@pchien great! Just wanted to make sure it was on the radar. :)

**Comment by yagudaev** [comment]
Any news there? Would really like to track extension events using mixpanel :).

**Comment by yagudaev** [comment]
Update: I was able to get things working using an app extension using

```
pod 'Mixpanel/AppExtension'
```

I had to comment out `pod 'Mixpanel'` on the main app target before I ran `pod install`, but after that, I was able to uncomment it and install again using `pod install` and all worked well.

**Comment by pchien** [comment]
@yagudaev there's a PR for it https://github.com/mixpanel/mixpanel-iphone/pull/715. It'll go into the next release.

**Comment by emes** [comment]
yay!

**Comment by pchien** [comment]
This has been released.
