### ISSUE TITLE
duplicate symbol _SignalHandler

### ISSUE THREAD

**Issue by hatebyte** [mixpanel/mixpanel-iphone#692]
**Integration Method:** CocoaPods
**Xcode Version:** 8.3
**Library Version:** Mixpanel (3.1.5)
**Platform:** iOS 
**Language:** Swift / Objective-C
**Description:** 
There is a c function, `SignalHandler`, that is conflicting with a c function of the same name in the MParticle SDK.
We use both and it makes using the Cocoapod unavailable. Please name space your functions so they do not conflict.
SignalHandler
**Expected Behavior:** 
The pod compiles in the xcode project.

**Comment by pchien** [comment]
@hatebyte just released a fix!
