### ISSUE TITLE
Multiple crashes on ios after building from source

### ISSUE THREAD

**Issue by galnanonmc** [mixpanel/mixpanel-iphone#695]
**Integration Method:** Manual
**Xcode Version:** 8.3.3
**Library Version:** 3.1.17
**Platform:** iOS 
**Language:** Objective-C
**Description:** downloaded the latest source and replaced an older source code version . Built, while running I experience multiple crashes from random locations inside the MP code. Tried with Arc and without, similar behavior. I assume this is build/compilation issue.
Any idea what might gone wrong?
**Expected Behavior:** compiling the source and not having crashes

**Comment by pchien** [comment]
@galnanonmc could I get some crash logs or anything? I'm not sure why the new version would cause crashes if it compiles properly (which accounts for method signature changes).

**Comment by gal1234** [comment]
found the issue. 
Seems that I had to compile all the code with ARC enabled.
This is not expected since the only file that actually requires ARC is the MPWebSocket, all other files do not mention this. Make sense?

from MPWebSocket:
#if !__has_feature(objc_arc)
#error MPWebSocket must be compiled with ARC enabled
#endif

**Comment by galnanonmc** [comment]
@pchien I believe I found the issue.
Seems that I had to compile all the code with ARC enabled.
This is not expected since the only file that actually requires ARC is the MPWebSocket, all other files do not mention this. Make sense?

from MPWebSocket:
#if !__has_feature(objc_arc)
#error MPWebSocket must be compiled with ARC enabled
#endif

**Comment by pchien** [comment]
Oh yeah @galnanonmc our entire library requires ARC now. I guess that error is misleading - will move it to `Mixpanel` instead.
