### ISSUE TITLE
MPTweakInline.h unavailable to tvOS

### ISSUE THREAD

**Issue by makangus** [mixpanel/mixpanel-iphone#696]
**Integration Method:** Carthage
**Xcode Version:** 8.3.2
**Library Version:** 3.1.8
**Platform:**  tvOS
**Language:** Swift / Objective-C
**Description:** 
`MPTweakInline.h` is unavailable to tvOS, so I am unable to create a `MPTweakValue` for A/B testing on tvOS. I noticed the Target Membership for the file is not enabled for tvOS. Is this intentional? 
**Expected Behavior:** 
`MPTweakInline.h` together with a list of other headers should be available to the tvOS target. 

For reference:
Headers under tvOS
![mixpanel h_2017-06-26_12-21-27](https://user-images.githubusercontent.com/448830/27549446-fc88ea56-5a69-11e7-8e10-63a1976260a6.jpg)

Headers under iOS
![mixpanel h_2017-06-26_12-21-47](https://user-images.githubusercontent.com/448830/27549469-08fc738e-5a6a-11e7-9e1e-630ea3b75274.jpg)

**Comment by pchien** [comment]
Hi @makangus, we actually don't have A/B testing support on tvOS, so there would be no way for tweaks to be used.
