### ISSUE TITLE
Can't identify people even after setting people properties (No people to flush)

### ISSUE THREAD

**Issue by rrecio** [mixpanel/mixpanel-iphone#70]
Is this supposed to happen?

![screen shot 2013-08-01 at 7 44 20 pm](https://f.cloud.github.com/assets/52694/897907/bb5ecf8a-fafc-11e2-8303-da5364c57ad7.png)

This is the code I'm calling just after user signs in:
https://gist.github.com/rrecio/6136058

**Comment by malectro** [comment]
As of the current release (2.7.1) Mixpanel should automatically identify.
