### ISSUE TITLE
People properties discarded if immediately called after identify method is called

### ISSUE THREAD

**Issue by marcmatta** [mixpanel/mixpanel-iphone#700]
**Integration Method:** CocoaPods 
**Xcode Version:** 8.2
**Library Version:** 3.1.5
**Platform:** iOS
**Language:** Objective-C
**Description:** After calling [mixpanel identify:<identifie>] following a sign in or sign up event, we immediately register some super properties like $first_name, $last_name, $email and few other non reserved custom properties and we set immediately after using the people.set() method the same values as people properties. The problem is that the people properties are discarded while the super properties are not.
**Expected Behavior:** People properties should be filled with values of the dictionary provided to  [mixpanel.people set:<dictionary>].

**Comment by pchien** [comment]
Hi @marcmatta I tried to do what you said in the HelloMixpanel demo project but I didn't run into the same issues you did - my people profile had all the properties that I'd set. In fact, it shouldn't matter if you set the people properties before or after you call `identify` as either way it should set them properly after `identify` is called. Do you have any more information you could give me? If you still have the issue, could you set up a small test project that reproduces the problem?

**Comment by marcmatta** [comment]
Hi @pchien ,

The problem is I cannot give you the code to reproduce the issue. From my reports it looks like almost half of the profiles are missing. So the same code works at times and at other times doesn't.

This baffled me and I can't figure out what the problem is. 

I know that it should be set even if filled before the `identify` is called but this is not happening.

**Comment by pchien** [comment]
@marcmatta are you using Segment for identity management? I've been told that this can happen if you use Segment and Mixpanel together. Otherwise, I wonder if there's a possibility that you identify twice or use both alias and identify or something, so that the properties would be associated with only one of the two profiles? Could you send me some logs of it happening? Use `[Mixpanel sharedInstance].enableLogging = YES` to turn logging on.

**Comment by marcmatta** [comment]
@pchien sorry for the late response. 

No I am not familiar with Segment nor am I using it. 

It took me a while to figure this out using report filters I found that people who have signed up are having this issue while others who just sign in don't have any missing profile issue.

The only difference is that I alias before i identify on Signup as recommended [here](https://mixpanel.com/help/questions/articles/how-should-i-handle-my-user-identity-with-the-mixpanel-javascript-library) like such:

```
- (void)didSignUp:(NSString*)user_id{
  [mixpanel createAlias:user_id forDistinctId: mixpanel.distinctId];
  [mixpanel identify:user_id];

  [UserAPI loggedInUser:^(NSDictionary* profile) {
      [mixpanel.people set:profile];
  }];
}

```
After debugging the code I found the cause of the issue and it is as follows:

- `[mixpanel createAlias:user_id forDistinctId: mixpanel.distinct_id]` is called which sets the alias to user_id.
- `[mixpanel identify:user_id]` is called afterwards and here lies the problem. The following Mixpanel code is self explanatory:

```
        // identify only changes the distinct id if it doesn't match either the existing or the alias;
        // if it's new, blow away the alias as well.
        if (![distinctId isEqualToString:self.alias]) {
            if (![distinctId isEqualToString:self.distinctId]) {
                self.alias = nil;
                self.distinctId = distinctId;
            }
            
            self.people.distinctId = distinctId;
        }
        
        if (self.people.unidentifiedQueue.count > 0) {
            for (NSMutableDictionary *r in self.people.unidentifiedQueue) {
                r[@"$distinct_id"] = self.distinctId;
                @synchronized (self) {
                    [self.peopleQueue addObject:r];
                }
            }
            [self.people.unidentifiedQueue removeAllObjects];
            [self archivePeople];
        }
        [self archiveProperties];
```

Which gets me to my problem where `self.people.distinctId` is not being set to the new distinctId because alias is equal to the new distinctId being set. Thus subsequent calls to `[mixpanel.people set:profile]` are treated similarly as for unidentified people instances and they're not being sent since I am not calling `[mixpanel identify:user_id]` anymore in my code.

My temporary fix is to call identify after each time I call `[mixpanel.people set:profile]` but I would recommend fixing the mixpanel code by moving out the self.people.distinctId = distinctId to outside of the first condition check like such:

```
```
      if (![distinctId isEqualToString:self.alias]) {
          if (![distinctId isEqualToString:self.distinctId]) {
              self.alias = nil;
              self.distinctId = distinctId;
          }      
      }
      self.people.distinctId = distinctId;

I would appreciate your opinion. Thank you for your time!

**Comment by pchien** [comment]
@marcmatta thanks for finding that out! That definitely looks like an issue, and we'll release a fix for it this week.

**Comment by pchien** [comment]
@marcmatta sorry my last message was wrong. It looks like our current behavior expects you to call `identify:` when you call `createAlias: forDistinctId:`. You're almost doing it right, but what we want is for you to call `[mixpanel identify:mixpanel.distinctId]` rather than `[mixpanel identify:user_id]`. For an example, see the "Combining anonymous and identifiable user data" section [here](https://mixpanel.com/help/reference/ios#user-identity). The check in `identify` to see if it's being called with the alias is there to stop us from creating duplicate people profiles for the same user. This should work for you. Let me know if it doesn't or if you have any more questions!

**Comment by marcmatta** [comment]
Hi @pchien ,

Thank you for the explanation! That worked perfectly fine.

I'd suggest you also update the sample app to include an aliasing example. 

I'm closing this issue as it has been resolved.
