### ISSUE TITLE
Main thread violation in -markVariantRun:

### ISSUE THREAD

**Issue by olarivain** [mixpanel/mixpanel-iphone#702]
**Integration Method:** Manual
**Xcode Version:** 9 beta 2
**Library Version:** 3.1.8
**Platform:** iOS
**Language:** doesn't matter
**Description:** -markVariantRun: performs a UIKit call on a background thread, cf https://github.com/mixpanel/mixpanel-iphone/blob/2f50572e15ee5257820cf704e14b2a72c2bc90d0/Mixpanel/Mixpanel.m#L1846
More specifically, ```[UIApplication sharedApplication].applicationState``` is being called run on ```self.serialQueue```
**Expected Behavior:** UIKit APIs shouldn't be called from a background thread.

This is a pretty annoying issue, due to an issue in xcodebuild test-without-building in Xcode 9 (which ignores the main thread sanitizer), we had to completely disable mix panel tracking in order for our test suite to even run.

**Comment by pchien** [comment]
Thanks @olarivain. I'll try to fix all the Xcode 9 issues within the next week or two.

**Comment by pchien** [comment]
@olarivain sorry about the delay. The Xcode 9 issues have been fixed in the latest release.
