### ISSUE TITLE
Can't associate an event tracked with a person before identifying it

### ISSUE THREAD

**Issue by rrecio** [mixpanel/mixpanel-iphone#71]
Like:
// Event A can't be seen in Rodrigo's activity feed
[mixpanel track:@"A"]
[mixpanel identify:@"Rodrigo"] // Perhaps, this should call people.identify, right? Yeah but it's making people to flush.
[mixpanel.people identify:@"Rodrigo"] // So I have to put this line to work. I refered to this in #70 
// Only event B can be seen, probably because it's being called after
[mixpanel track:@"B"]

**Comment by malectro** [comment]
sorry we let this get stale.

this is a good candidate for ```createAlias:forDistinctID``` which will link the default distinct id to the one you identify later.
