### ISSUE TITLE
Mixpanel calls UIKit APIs on a background thread

### ISSUE THREAD

**Issue by irace** [mixpanel/mixpanel-iphone#710]
**Integration Method:** CocoaPods
**Xcode Version:** 9 beta 5
**Library Version:** 3.1.9
**Platform:** iOS
**Language:** Objective-C
**Description:** Mixpanel calls UIKit on a background thread
**Expected Behavior:** Mixpanel only calls UIKit on the main thread

![screen shot 2017-08-10 at 8 38 29 am](https://user-images.githubusercontent.com/399560/29170602-7313b7d6-7da7-11e7-9b9a-c16725b41948.png)

**Comment by pchien** [comment]
Ah good catch @irace. I guess we didn't try initializing Mixpanel from a background thread. I'll fix it and add a test for that.

**Comment by pchien** [comment]
This is fixed in the latest release.
