### ISSUE TITLE
Feature: Ability to import tracked events older than five days

### ISSUE THREAD

**Issue by idStar** [mixpanel/mixpanel-iphone#712]
### Current State

While the library will flush all available events to the server, I understand from Mixpanel support that only events from the last 5 days will be accepted. Older events are dropped.

Older events can be imported, however, using the `/import` web service endpoint.

The Mixpanel library has no facility to query and optionally submit older events via this import.

### Use Case

One of my clients, who currently uses Mixpanel, noticed that in hospital settings, where our app doesn't need Internet connectivity to function, and where it is not even available in some cases where radio transmitting devices are not allowed, event data can accumulate on the device for months.

Every so often, these devices are connected to wifi (think, dedicated iPads). At that point, if only the last five days of event data makes it into the Mixpanel cloud, we've lost a lot of tracked events.

### Request

A method on the Mixpanel singleton, such as `-(void)importOldEvents` that will flush old event data from the device, into the cloud. This will abstract users of this library from having to assemble a low-level network call that requires querying the stored events to find out which ones need to be imported.

**Comment by zihejia** [comment]
Unfortunately, the[ Import API](https://developer.mixpanel.com/reference/import-events) is better used on the server-side. We currently don't have any plan to support it, we will revisit it in the future if there are more similar requests. Thanks @idStar !
