### ISSUE TITLE
Mixpanel 

### ISSUE THREAD

**Issue by toppole69** [mixpanel/mixpanel-iphone#716]
**Integration Method:** CocoaPods / Carthage / Manual
**Xcode Version:** 
**Library Version:** 
**Platform:** iOS / App Extension / watchOS / tvOS
**Language:** Swift / Objective-C
**Description:** 
**Expected Behavior:**

**Comment by pchien** [comment]
Hey @toppole69 did you open this by accident? I'm closing this - feel free to reopen if you have an issue and provide some details.
