### ISSUE TITLE
Method `appliesTo` making major impact on CPU

### ISSUE THREAD

**Issue by batkov** [mixpanel/mixpanel-iphone#719]
**Integration Method:** CocoaPods 
**Xcode Version:** 9
**Library Version:** 3.1.9
**Platform:** iOS 
**Language:**  Objective-C
**Description:** 
Method `appliesTo` making major impact on CPU
especially this line `([self.name isEqualToString:@"*"] || [view isKindOfClass:NSClassFromString(self.name)])`

- (BOOL)appliesTo:(NSObject *)view
{
    return (([self.name isEqualToString:@"*"] || [view isKindOfClass:NSClassFromString(self.name)])
            && (self.nameOnly || (
                (!self.predicate || [_predicate evaluateWithObject:view])
                && (!self.index || [self isView:view siblingNumber:_index.integerValue])
                && (!(self.unique) || [self isView:view oneOfNSiblings:1])))
            );
}

**Expected Behavior:** Work not without CPU overload

**Comment by george-luofz** [comment]
@batkov  hi,you should decribe your problem in detail.the call stack symbols are expected sincerely.

**Comment by zihejia** [comment]
Hi @batkov, this is for A/B testing, how complicated is your view structure for A/B testing?

**Comment by zihejia** [comment]
hi @batkov , I'm closing this one now due to the lack of information but please feel free to reopen it if the problem still exist in the latest version.
