### ISSUE TITLE
Warnings on builds and failure on tests due to access of [UIApplication applicationState] and [UIApplication statusBarOrientation] from a thread other than the main thread

### ISSUE THREAD

**Issue by MattSich** [mixpanel/mixpanel-iphone#720]
**Integration Method:** CocoaPods
**Xcode Version: 9.0
**Library Version:** v3.2.0
**Platform:** iOS
**Language:** Objective-C
**Description:**  Warnings on builds and failure on tests due to access of [UIApplication applicationState] and [UIApplication statusBarOrientation] from a thread other than the main thread. 
xCode is showing the following errors on build: 
<img width="1191" alt="screen shot 2017-09-22 at 8 54 51 am" src="https://user-images.githubusercontent.com/6378097/30746000-313d9ea8-9f76-11e7-91f7-040e089d5e41.png">
but it doesn't look like it's having a hard time pinpointing the location of the causes for the warnings because those marked location don't look like they have anything to do with it.

There's a note on the v3.2.0 release that made me thing this was addressed but it doesn't look like that's the case. 

**Expected Behavior:** Would be nice if it didn't break the tests =)

**Comment by MattSich** [comment]
<img width="579" alt="screen shot 2017-09-22 at 9 26 21 am" src="https://user-images.githubusercontent.com/6378097/30746562-2314bc56-9f78-11e7-975e-d99a2e3cd421.png">

**Comment by MattSich** [comment]
Never mind. For whatever reason, I had to restart xCode for it to start working. Probably some caching issue...

**Comment by gustavengvallthomascook** [comment]
I just got crash on what seems to be just that. Mixpanel (~> 2.9.9) is used by static framework I use.

**Comment by pchien** [comment]
Hey @gustavengvallthomascook all the UI main thread issues that we know about have been fixed in later versions of the library.

**Comment by gustavengvallthomascook** [comment]
Yes thanks. Saw now that v3.2.0 had this fix.
