### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by gsinghs** [mixpanel/mixpanel-iphone#722]
**Integration Method:**  I have installed using : pod "Segment-Mixpanel"
**Xcode Version: Version 8.3.2 (8E2002)
**Library Version:** latest as of today
**Platform:** happening on iOS 10 (seems to work on ios9)
**Language:** Objective-C
**Description:** 

 I have installed using : pod "Segment-Mixpanel"

And I am tracking events using:
[[SEGAnalytics sharedAnalytics] track:@"EVENT_NAME"];

**Now my app crashes in Mixpanel lbrary (IN CLASS: Mixpanel.m on line number 482) :**

                         0x0000000100208e24 __38-[Mixpanel setupAutomaticPushTracking]_block_invoke_2 (Mixpanel.m:482) 

                      0x000000010022de74 mp_swizzledMethod_4 (MPSwizzler.m:75)

The reason for crash it gives is:
**-[__NSDictionaryI notification]: unrecognized selector sent to instance 0x174e73ec0**

Please fix this asap. The crash is appearing in iOS 10 only and not iOS 9

Thanks!

**Comment by breferrari** [comment]
It's also happening at my end using iOS 11. Wasn't happening before the update.

**Comment by gsinghs** [comment]
Just curious is there an easy way to make mixpanel tracking calls in separate thread, so that mixpanel crash don't crashes our app/main thread, and app stays working.. Any suggestions?

**Comment by breferrari** [comment]
I have returned Mixpanel to version 3.1.9 and it seems to have solved my problem. No crash happened.
It seems to be a problem created in the newer release.

**Comment by gsinghs** [comment]
Actually I haven't installed Mixpanel directly, but through: pod "Segment-Mixpanel"
So the mixpanel's latest version gets installed through it automatically as pod's further dependency.

 Let's see if they are able to push a quick fix. It's in CLASS: Mixpanel.m on line number 482), where it is trying to access .notification, and it crashes with:  -[__NSDictionaryI notification]: unrecognized selector sent to instance 0x174e73ec0

**Comment by pchien** [comment]
@gsinghs @breferrari this should be fixed in the latest release.
