### ISSUE TITLE
Inconsistency with alias during identify methods

### ISSUE THREAD

**Issue by pixelmatrix** [mixpanel/mixpanel-iphone#724]
**Integration Method:** CocoaPods
**Xcode Version:** 9
**Library Version:** 3.2.0
**Platform:** iOS
**Language:** Objective-C
**Description:** 

Our goal is to link up anonymous events with authenticated events using alias, ideally creating the people profile with the distinctID of our internal userID. 

However, when calling alias(newUserID) and identify(newUserID) + setting some people properties, no People profile is created at all. It looks like the root cause of this is that in Mixpanel.m, the identify method skips everything including the usePeople check if the distinctID is equal to the alias. I noticed this is inconsistent from the Swift library.

Compare:

https://github.com/mixpanel/mixpanel-swift/blob/402cd52aa8fbe85df4a06a08d52fd76659dc8aab/Mixpanel/MixpanelInstance.swift#L625

https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L335

This is problematic for us because we use Segment to proxy identity and events to other services, so when we call identify for other services we really need that ID to be consistent across sessions and devices since they don't have a concept of alias. Using Segment ties us to the Objective-C library, despite our app being in Swift. We found a workaround by calling identify immediately after the alias with the original distinctID via the Mixpanel library directly, but it doesn't seem like this should be necessary at all.

Is there a good reason for this behavior? If so, why is it inconsistent in the Swift library? Really hoping we can find a solution here where we don't have to resort to workarounds.

**Expected Behavior:** 

When calling alias(newUserID) and subsequently identify(newUserID) + people.set(properties), a People profile should be created.

**Comment by pchien** [comment]
Hi @pixelmatrix. Thanks for pointing out the inconsistency between objc and swift, we'll resolve it. In the meantime, I think when calling alias + identify, you're supposed to alias with your new id and then identify with the default Mixpanel one. We added the code that checks if identify is being called with the same id as the alias because calling alias and then identify both with the new id could create duplicate people profiles. We suggest calling alias with the new id and identify with the original one for both [swift](https://mixpanel.com/help/reference/swift#user-identity) and [objective c](https://mixpanel.com/help/reference/ios#user-identity).

**Comment by pixelmatrix** [comment]
@pchien thanks for the clarification. For a traditional Mixpanel setup your suggestion works fine, but since we use Segment to identify across all sorts of services, we need this to be an ID that we can rely on every time to not create duplicate profiles for other devices. We'd prefer identify to work with either the alias id or the distinct id if possible. It feels like a bug that calling identify completely ignores creating the profile in the objc library.

**Comment by pchien** [comment]
Can you clarify what you mean with "We'd prefer identify to work with either the alias id or the distinct id if possible."? What's the distinct id you're referring to there? The way the library works calling identify with the distinct id should work.

**Comment by pixelmatrix** [comment]
Sure thing. In our setup we have a uuid for each user account (userID), which we use to identify the user across all services with Segment. Mixpanel itself also has a default distinctID which is generally the IDFA of the device.

We'd prefer to be able to call identify with the userID instead of the original distinctID since other services (via Segment) rely on the ids matching up across sessions and devices. Intercom for example doesn't have a concept of alias, so if we call it with Mixpanel's distinctID it will see it as a new user.

Our code basically looks like this on sign up:

segment.alias(userID)
segment.identify(userID, traits: properties)

Which internally calls:

mixpanel.alias(userID, distinctID: mixpanel.distinctID)
mixpanel.identify(userID)
mixpanel.people.set(properties)

… along with identify calls for other libraries.

As a hack, we currently have to do this to get People profiles to show up:

segment.alias(userID)
mixpanel.identify(mixpanel.distinctID)
segment.identify(userID, properties)

**Comment by pchien** [comment]
Thanks for the detailed response. We'll give it some thought and hopefully come up with a good solution soon.

**Comment by pixelmatrix** [comment]
Sounds great. I understand there are a lot of use cases to consider :)

**Comment by pixelmatrix** [comment]
Looks like the JS library also creates the people profile if you pass the alias in identify: https://github.com/mixpanel/mixpanel-js/blob/797e5e5467f15bd0d06650a64f26e8217ea6b301/src/mixpanel-core.js#L1344

**Comment by pchien** [comment]
Hey @pixelmatrix we made it so calling `alias` implicitly calls `identify` in the latest release. Now it should work if you just do `segment.alias` (and the subsequent `segment.identify` will be handled properly in both sign up and sign in cases).

**Comment by pixelmatrix** [comment]
Thanks @pchien, we'll give this a look
