### ISSUE TITLE
Release framework contains LLVM instrumentation and results in App Store rejections

### ISSUE THREAD

**Issue by dgladkov** [mixpanel/mixpanel-iphone#726]
**Integration Method:** Manual
**Xcode Version:**  9.0 (9A235)
**Library Version:** v3.2.1
**Platform:** iOS
**Language:** Objective-C
**Description:**
More details:
https://developer.apple.com/library/content/qa/qa1964/_index.html

Steps to verify:

1. Download v3.2.1 Release from GitHub (https://github.com/mixpanel/mixpanel-iphone/releases/download/v3.2.1/Mixpanel.framework.zip)
2. Extract Mixpanel.framework.zip
2. Run `$ otool -l -arch all ~/Downloads/Carthage/Build/iOS/Mixpanel.framework/Mixpanel  | grep __llvm_prf`
3. Output:
```
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds
```

Embedded frameworks containing `__llvm_prf*` sections result in automatic rejections after uploading to App Store.
**Expected Behavior:** Successful App Store upload.

**Comment by pchien** [comment]
Hi @dgladkov I just released 3.2.2 which should fix your problem (made a new release in case it affects other methods of integration as well). Let me know if you have any other issues!
