### ISSUE TITLE
Warning: This block declaration is not a prototype

### ISSUE THREAD

**Issue by DrBeak1** [mixpanel/mixpanel-iphone#735]
With release of Xcode 9, there are warnings when blocks do not specify arguments. Will this be corrected any time soon, or will we have to live on with the warnings?

**Comment by yas375** [comment]
@DrBeak1 are you sure you are using the latest version? They seem to address some warnings in #687 . Maybe submit a PR for remaining?

**Comment by DrBeak1** [comment]
@yas375 ty - somehow I ended up on 3.2.2. **3.2.3** fixes warnings.
