### ISSUE TITLE
Race Condition w/ People Properties and A/B Tests?

### ISSUE THREAD

**Issue by mamaral** [mixpanel/mixpanel-iphone#736]
**Integration Method:** Carthage
**Xcode Version:** Xcode 9
**Library Version:** v3.2.2
**Platform:** iOS
**Language:** Objective-C
**Description:** If I were to set a people property that would qualify a new user for an outstanding A/B test and then immediately call `joinExperiments`, is there a potential race condition that exists there between the queuing up of sending the people property data to the server and getting applicable variants for that user? Is there some sort of queue that prevents this race condition?

I observed that my device gets the appropriate A/B test experience intermittently, although I noticed in some of the failure cases there was an error logged something along the lines of `decide check api error: api unavailable`. I'm wondering if there's a potential race condition here that could result in intermittent failures, or perhaps all the failures I was seeing was the result of the "api unavailable" error and I just missed that in some of the cases?

**Comment by wgins** [comment]
Hi @mamaral,

You're 100% correct that you need to flush the profile update from the device as soon as possible if you're using that property to qualify the user for the A/B test. You can do this with the [flush method](https://mixpanel.github.io/mixpanel-iphone/Classes/Mixpanel.html#//api/name/flush). This [article](https://mixpanel.com/help/questions/articles/how-can-i-effectively-ab-test-the-very-first-screen-or-sign_up-flow-of-my-app) is also quite helpful.

In terms of the API failures, can you write into support@mixpanel.com with the frequency at which you're seeing these failures as well as the project and distinct_id of the user you're testing with? The failures you're seeing should not be related to property you're setting in any way. 

Thanks!

**Comment by mamaral** [comment]
Great, thanks for the info! Wouldn't this solve the race condition issue:

```
[Mixpanel sharedInstance] flushWithCompletion:^{
    [[Mixpanel sharedInstance] joinExperiments];
};
```

Seems like a slightly better solution than what was referenced in the article (i.e. waiting an arbitrary 500ms after calling identify).

**Comment by wgins** [comment]
Good question, `flushWithCompletion` _might_ work, but `flushWithCompletion` only implies that we've received the updates that were flushed, not that we've processed and successfully updated our API endpoints based on the updates. This is why we've erred on the side of recommending the 500ms "timeout" -- to provide enough time to process the updates after receiving them.

Let me know if this helps!

**Comment by mamaral** [comment]
Ok cool, perhaps there's an API we could add that encompasses this entire process async with a handler called when its done - equivalent to "flush all my data, refresh ab tests, tell me when I'm done"?

**Comment by wgins** [comment]
As of right now, there is not. If you write into support@mixpanel.com a member of our Support Engineering team would be happy to submit a feature request on your behalf :)

**Comment by mamaral** [comment]
Sounds good, thanks a bunch for your help!
