### ISSUE TITLE
Address Sanitizer issue in _MPTweakInlineLoader

### ISSUE THREAD

**Issue by szigetics** [mixpanel/mixpanel-iphone#739]
**Integration Method:** CocoaPods
**Xcode Version:** 9.0
**Library Version:** 3.2.3
**Platform:** iOS
**Language:** Objective-C
**Description:** When address sanitizer is enabled I run into this issue at app startup : 
<img width="1110" alt="screen shot 2017-10-27 at 12 57 30" src="https://user-images.githubusercontent.com/7099208/32101501-b9f790b0-bb18-11e7-9406-15a5e36774fd.png">

**Expected Behavior:** Mixpanel shouldn't generate any address sanitizer issues.

**Comment by george-luofz** [comment]
hi,this answer will help you too.[https://github.com/mixpanel/mixpanel-iphone/issues/734](url)

**Comment by pchien** [comment]
Closing this one as it's a duplicate.
