### ISSUE TITLE
duplicate symbols UncaughtExceptionHandlerAddressesKey

### ISSUE THREAD

**Issue by luna-moonfang** [mixpanel/mixpanel-iphone#744]
There are duplicate symbols in both Mixpanel 3.2.3 and another static library in my project, which are:
UncaughtExceptionHandlerAddressesKey
UncaughtExceptionHandlerSignalKey
UncaughtExceptionHandlerReportAddressCount
UncaughtExceptionHandlerSkipAddressCount
UncaughtExceptionHandlerSignalExceptionName

But Mixpanel 3.1.4 works fine.

Please add prefix to these constants to fix this issue. Thx!

**Comment by brynjar** [comment]
I just created a ticket for a similar issue: https://github.com/mixpanel/mixpanel-iphone/issues/750

Your ticket is now 22 days old and no responses which is not encouraging.

**Comment by pchien** [comment]
This should be fixed in the latest version.
