### ISSUE TITLE
Embed mixpanel into an sdk

### ISSUE THREAD

**Issue by masaldana2** [mixpanel/mixpanel-iphone#745]
**Integration Method:** CocoaPods or Manual
**Xcode Version:**  9.0
**Library Version:**  latest
**Platform:** iOS
**Language:** Swift  or Objective-C
**Description:**  I cant integrate mixpanel into my sdk. when I build it it creates a separate folder for mixpanel. i want it to be embedded 
**Expected Behavior:** demo app should find mixpanel famework

**Comment by pchien** [comment]
@masaldana2 I wonder if there's an Xcode project setting you need to change. Maybe you have to add the Mixpanel library to the "Embedded Binaries" section? As far as I know there's nothing special about the Mixpanel library that forces it to be separate.

**Comment by pchien** [comment]
Closing this. @masaldana2 feel free to reopen or create new issues if you have further questions.
