### ISSUE TITLE
UI API called on a background thread

### ISSUE THREAD

**Issue by nandodelauni** [mixpanel/mixpanel-iphone#746]
**Integration Method:** CocoaPods
**Xcode Version:** Xcode 9.1
**Library Version:** 3.1.1
**Platform:** iOS
**Language:** Objective-C
**Description:** Main Thread Checker: UI API called on a background thread: -[UIApplication setNetworkActivityIndicatorVisible:]. It happens on - (void)updateNetworkActivityIndicator:(BOOL)enabled; in MPNetwork class.
**Expected Behavior:** No UI API must be called on a background thread

**Comment by pchien** [comment]
@nandodelauni this should be fixed in a later version of the library.

**Comment by nandodelauni** [comment]
The pod wasn't being updated because of I was using also the `Mixpanel/AppExtension` subspec and it get stucked at 3.1.1. It would be nice if there was any reference in the README warning you this behaviour. 

Closing this. Thanks!
