### ISSUE TITLE
MixpanelInstance.distinctId return aliased distinctId

### ISSUE THREAD

**Issue by Hanspagh** [mixpanel/mixpanel-iphone#748]
**Integration Method:** Carthage 
**Xcode Version:** 9.1  
**Library Version:** 2.1.8
**Platform:** iOS 
**Language:** Swift 
**Description:** 
When calling MixpanelInstance.distinctId with an alias user, we get the aliased distinctId and not the distinct seen in our mix panel stats
Ex.
Aliasing a user with createAlias(101, MixpanelInstance.distinctId)
MixpanelInsatance.distinctId returns the same distinctId as seen in the mixpanel stats
  
If we later identify a user with identify(101)
MixpanelInsatance.distinctId will now return 101
  
**Expected Behavior:** 
Get the same id as in our mix panel stats

**Comment by pchien** [comment]
@Hanspagh did you mean to create this in the https://github.com/mixpanel/mixpanel-swift repo?

**Comment by Hanspagh** [comment]
Yes, I am sorry

**Comment by Hanspagh** [comment]
Yes, I am sorry
