### ISSUE TITLE
MPSwizzler.h This block declaration is not a prototype

### ISSUE THREAD

**Issue by blloc** [mixpanel/mixpanel-iphone#749]
**Xcode Version:Xcode 9.1
**Platform:** iOS
**Language:** Objective-C
**Description:** MPSwizzler.h This block declaration is not a prototype

image:
![image](https://user-images.githubusercontent.com/8268339/33118017-7408fc28-cfa5-11e7-8d05-3e30eb478ec3.png)

**Comment by blloc** [comment]
use :

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wstrict-prototypes"
typedef void (^swizzleBlock)();
#pragma clang diagnostic pop
Is it correct to remove the warning in this way?

reference：
https://stackoverflow.com/questions/44473146/this-function-declaration-is-not-a-prototype-warning-in-xcode-9

**Comment by yas375** [comment]
@blloc I think `typedef void (^swizzleBlock)(void);` would be a better fix.

**Comment by blloc** [comment]
@yas375 I tried this way, not feasible，look
![image](https://user-images.githubusercontent.com/8268339/33156518-6326d318-d035-11e7-9d6d-e81f80f201f9.png)

**Comment by pchien** [comment]
Sorry @blloc I haven't figured out a good solution to this yet. `void` can't be added because we're using `swizzleBlock` for blocks with different numbers of arguments. I don't think we should just remove the warning - there's probably a better solution to this. I'll think more when I get more time.

**Comment by blloc** [comment]
ths @pchien

**Comment by zihejia** [comment]
We haven't yet prioritized this but will do it in the future release.

**Comment by zihejia** [comment]
Thanks guys. We have released v3.3.4 and it's no longer showing this as a warning.
