### ISSUE TITLE
linker error: duplicate symbol _UncaughtExceptionCount

### ISSUE THREAD

**Issue by brynjar** [mixpanel/mixpanel-iphone#750]
When integrating Mixpanel into an iOS project using cocoapods; when that project is also using the libdtdev.a static library provided by this company: https://ipcmobile.com/products/ios-peripherals/linea-pro-5/ a linker error is produced:

duplicate symbol _UncaughtExceptionCount in:
    /Users/[redacted]/Build/Products/Debug-dev3-iphoneos/Mixpanel/libMixpanel.a(MixpanelExceptionHandler.o)
    /Users/[redacted]/lineapro/libdtdev.a(UncaughtExceptionHandler.o)
ld: 7 duplicate symbols for architecture arm64

=====

UncaughtExceptionCount is defined here: https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/MixpanelExceptionHandler.m and exists in the global namespace, thus it conflicts with the a variable of the same name defined by the lineapro static library.

Either UncaughtExceptionCount (and other) variables should not exist in the global namespace, or should be prefixed at a minimal as MixpanelUncaughtExceptionCount or something.

**Integration Method:** CocoaPods (use_frameworks! not set)
**Xcode Version:** 9.1
**Library Version:** latest - pod 'Mixpanel'
**Platform:** iOS
**Language:** Objective-C
**Description:** Can't build project - linker error
**Expected Behavior:** - Shouldn't conflict with other libraries being used.

**Comment by pchien** [comment]
This should be fixed in the latest version.
