### ISSUE TITLE
MPNotificationTypes should be in a public header

### ISSUE THREAD

**Issue by abotkin-cpi** [mixpanel/mixpanel-iphone#751]
**Integration Method:** CocoaPods
**Xcode Version:** 9B46
**Library Version:** 3.2.3
**Platform:** iOS
**Language:** Objective-C
**Description:** MPNotificationTypeMini & MPNotificationTypeTakeover are currently needed for use with -[Mixpanel showNotificationWithType:] but are hidden in a project header definition of MPNotification.h rather than in a public header like Mixpanel.h or some other public header.  Users of showNotificationWithType have to define the strings given by the param comment themselves.
**Expected Behavior:** I'd expect that the notification types to be declared in a public header rather than having to define my own string of @"mini" or @"takeover".  Ideally, showNotificationWithType should be typed similar to the way Apple defines PKPaymentNetwork in the PassKit frameworks so that the method would be declared -[Mixpanel showNotificationWithType:(MPNotificationType)notificationType] & would have extern definitions for MPNotificationTypeTakeover & MPNotificationTypeMini in a public available header.

**Comment by zihejia** [comment]
Hi @abotkin-cpi, we have released a new version 3.2.8. Now you can use MPNotificationTypeMini and   MPNotificationTypeTakeover directly, like [Mixpanel showNotificationWithType: MPNotificationTypeTakeover].
