### ISSUE TITLE
Fix deprecations and semantic issues for iOS11

### ISSUE THREAD

**Issue by herbertbay** [mixpanel/mixpanel-iphone#753]
Integration Method: Manual
Xcode Version: 9.1 
Library Version: latest pull from master on https://github.com/mixpanel/mixpanel-iphone
Platform: iOS
Language: Objective-C
Description: deprecated functions such as `'asl_log' is deprecated: first deprecated in iOS 10.0 - os_log(3) has replaced asl(3)`
Expected Behavior: no warnings at compilation time

**Comment by herbertbay** [comment]
I still have those deprecation warnings.

<img width="339" alt="screen shot 2018-02-27 at 17 56 14" src="https://user-images.githubusercontent.com/566545/36711313-9653c216-1be7-11e8-889b-ff16918532c7.png">

**Comment by rodmaz** [comment]
This is really shameful. Almost a year since this issue was opened, iOS 12 around the corner and no fix on the *several* warnings and deprecations.

**Comment by zihejia** [comment]
Hi @rodmaz @herbertbay , thanks so much for raising this and I am really really sorry about the delay. We have released v3.3.4 and has a fix for this.
