### ISSUE TITLE
Tiny typo to a macros

### ISSUE THREAD

**Issue by evgeniyd** [mixpanel/mixpanel-iphone#759]
It looks like *Mixpanel.m*'s `-markVariantRun:` method has a typo checking for wrong macros to be defined:

**notice:** 

    #if !MIXPANEL_NO_UI_APPLICATION_ACCESS

**expected:** 

    #if !MIXPANEL_NO_UIAPPLICATION_ACCESS

**Comment by pchien** [comment]
Thanks for pointing this out @evgeniyd! It shouldn't be causing any real issues, and is fixed on master now.
