### ISSUE TITLE
clang macro warnings for Mixpanel.h (undefined behavior)

### ISSUE THREAD

**Issue by iwc** [mixpanel/mixpanel-iphone#773]
**Integration Method:** CocoaPods
**Xcode Version:**  9.3 (9E145)
**Library Version:** 3.2.1
**Platform:** iOS 
**Language:** Objective-C
**Description:** Building with the latest Xcode produces
`Pods/Mixpanel/Mixpanel/Mixpanel.h:182:6: Macro expansion producing 'defined' has undefined behavior`

**Expected Behavior:** No warning.

**Comment by zihejia** [comment]
Hi @iwc, we have fixed this issue in 3.2.9, so close this issue for now. Thanks!
