### ISSUE TITLE
Button to dismiss fullscreen in-app message is too tiny, hard to tap

### ISSUE THREAD

**Issue by yas375** [mixpanel/mixpanel-iphone#774]
**Library Version:** 3.2.9
**Platform:** iOS
**Language:** Objective-C

We are using Mixpanel's fullscreen in-app messages and we are receiving complaints from users that it's too hard to dismiss it by tapping `X` in top right corner.

I looked and it's super tiny, just 16x16:

![2018-04-04_1727](https://user-images.githubusercontent.com/217368/38341466-85bbc5a4-382d-11e8-8b46-737642d5563c.png)

![2018-04-04_1728](https://user-images.githubusercontent.com/217368/38341501-bf3cb414-382d-11e8-8dd6-08bd5ec0b6b1.png)

Also you seem to hardcode it to be 23x23 on iPhone in landscape and 30x30 on iPad. Which still seem to be quite small.

AFAIK Apple used to recommen tap targets to be at least 44x44 and we seem to have plenty of space on these screen. By any chance you might address this issue in a future release by increasing button sizes? Would you be interested in a PR which does it?

Thanks in advance.

**Comment by zihejia** [comment]
Hi @yas375, we will create a PR for this, thanks!

**Comment by zihejia** [comment]
Hi @yas375, thanks! we have released a new version 3.3.1 with a fix to this problem.

**Comment by yas375** [comment]
Thanks!
