### ISSUE TITLE
Watchdog crash

### ISSUE THREAD

**Issue by danielnagyx** [mixpanel/mixpanel-iphone#776]
**Integration Method:** CocoaPods
**Xcode Version:** 9.2
**Library Version:** 3.2.6 
**Platform:** iOS 
**Language:** Objective-C
**Description:** Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d (main-thread watchdog crash [1])

We have observed several instances of our application crashing on older devices due to the main-thread watchdog killing the app. For example: in one instance  `[Mixpanel applicationDidEnterBackground:]` was blocking the main thread with `@synchronized(self)` because on a background thread (`com.mixpanel....`) the Mixpanel SDK was performing I/O operations also within a `@synchronized(self)` block. (`[Mixpanel track:properties:]` --> `[Mixpanel archiveEvents]` --> `[Mixpanel archiveObject:withFilePath:]`).

Running I/O operations within `@synchronized` blocks while synchronizing the main thread on the same object defeats the purpose of deferring I/O to a background thread.

**Expected Behavior:** 
The appropriate way of doing this would be to perform I/O outside of the synchronized block, so that it won't be possible to block the main thread. E.g.:

```
- (void)saveData {
    NSMutableData* dataToSave = [NSMutableData new];
    @synchronized(self) {
        ... // build the data
    }
    [dataToSave writeToFile:...];
}
```

[1] https://developer.apple.com/library/content/qa/qa1693/_index.html

**Comment by tzahola** [comment]
Can confirm, this happened to me as well.

**Comment by zihejia** [comment]
Thanks @danielnagyx and @tzahola, we will investigate on this and might create a PR for this.

**Comment by zihejia** [comment]
hi @danielnagyx @tzahola , we have release v3.3.3 with a fix for this issue, thanks! Feel free to reopen it anytime if still have the problem.
