### ISSUE TITLE
Mixpanel sharedInstanceWithToken:launchOptions:trackCrashes:automaticPushTracking: doesn't use declared boolean arguments

### ISSUE THREAD

**Issue by abotkin-cpi** [mixpanel/mixpanel-iphone#779]
**Integration Method:** CocoaPods
**Xcode Version:** 9.2 (9C40b)
**Library Version:** 3.3.0
**Platform:** iOS
**Language:** Objective-C
**Description:** `-[Mixpanel sharedInstanceWithToken:launchOptions:trackCrashes:automaticPushTracking:]` does not use the declared boolean arguments for trackCrashes & automaticPushTracking but instead uses a hard-coded YES for both arguments (likely due to copy-paste).
**Expected Behavior:** Based off the documentation in Mixpanel.h, I would expect use of `-[Mixpanel sharedInstanceWithToken:launchOptions:trackCrashes:automaticPushTracking:]` with trackCrashes & automaticPushTracking set to NO woud result in both being turned off.

**Comment by zihejia** [comment]
hi @abotkin-cpi, sorry about it, we have released a new version 3.3.1 with a fix to this problem.
