### ISSUE TITLE
Travis CI builds fail on bad decrypt of provisioning profile

### ISSUE THREAD

**Issue by abotkin-cpi** [mixpanel/mixpanel-iphone#781]
**Integration Method:** CocoaPods
**Xcode Version:** 
**Library Version:** 3.3.0 
**Platform:** iOS
**Language:** Objective-C
**Description:** All Travis CI builds fail on a bad decrypt of the provisioning profile.
**Expected Behavior:** I'd expect that Travis CI builds would be able to build Mixpanel.
**Diagnostic Information:**

https://travis-ci.org/mixpanel/mixpanel-iphone/jobs/374617036

Logs:

$ openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/HelloMixpanel_Ad_Hoc.mobileprovision.enc -d -a -out scripts/profile/HelloMixpanel_Ad_Hoc.mobileprovision
bad decrypt
1776:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.60.1/src/crypto/evp/evp_enc.c:330:
The command "openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/HelloMixpanel_Ad_Hoc.mobileprovision.enc -d -a -out scripts/profile/HelloMixpanel_Ad_Hoc.mobileprovision" failed and exited with 1 during .

**Comment by zihejia** [comment]
Hi @abotkin-cpi , we will fix this shortly , thanks for raising it.

**Comment by zihejia** [comment]
Hi @abotkin-cpi, we have released v3.3.2 to a bit cleanup to the build script. Thanks!
