### ISSUE TITLE
Flush with completion does not call completion block if tracking is disabled

### ISSUE THREAD

**Issue by anderscarling** [mixpanel/mixpanel-iphone#786]
It feels like this is an area where bugs could very easily occur as completion blocks are usually expected to be ran no matter the outcome of the operation.

```
- (void)flushWithCompletion:(void (^)(void))handler
{
    if ([self hasOptedOutTracking]) {
        return;
    }
```

https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L922

**Comment by zihejia** [comment]
hi @anderscarling , the if logic is not inside the actual block(hander), so the completion handler block won't be executed if the user has opted out tracking which should be expected behavior.

**Comment by zihejia** [comment]
hi @anderscarling , we have release v3.3.3 with a fix for this, thanks!
