### ISSUE TITLE
Mixpanel-AppExtension podspec appears out of sync from Mixpanel podspec

### ISSUE THREAD

**Issue by abotkin-cpi** [mixpanel/mixpanel-iphone#794]
**Integration Method:** CocoaPods
**Xcode Version:** 10A254a
**Library Version:** 3.3.3
**Platform:** iOS & App Extension
**Language:** Objective-C
**Description:** In looking to integrate the Mixpanel app extension pod into my project, it seems that the Mixpanel-AppExtension podspec is several versions out of sync, stuck on v3.2.2.  This is a bit concerning to me as v3.3.0 was Mixpanel's GDPR support release & so I'm uncertain (as I haven't done an audit) how the app extension would perform when the app uses a GDPR supporting release to opt out but the extension is using 3.2.2.

https://cocoapods.org/pods/Mixpanel-AppExtension

Current Podspec in Cocoapods repo:
https://github.com/CocoaPods/Specs/blob/master/Specs/4/4/e/Mixpanel-AppExtension/3.2.2/Mixpanel-AppExtension.podspec.json

**Expected Behavior:** I'd expect the Mixpanel-AppExtension podspec to have the latest version of Mixpanel and to match the Mixpanel podspec.

**Comment by abotkin-cpi** [comment]
Is there a reason the Mixpanel iOS framework doesn't declare "Require Only App-Extension-Safe API"?  I would've expected this to be set if the framework is safe to use in an app extension.  Found the release notes about the main pod now being extension safe: https://github.com/mixpanel/mixpanel-iphone/pull/715

It would also be nice to have explicit documentation about App Extension support.  Googling "Mixpanel App Extension" leads to the past discussions of using the Mixpanel-AppExtension podspec & the Mixpanel support pages about setting up a project don't seem to have any page about app extensions.

**Comment by zihejia** [comment]
hi @abotkin-cpi , the pod `Mixpanel-AppExtension` is obsolete, we have consolidated it into main `Mixpanel` target since v3.2.3. We can't declare "Require Only App-Extension-Safe API" in the main `Mixpanel` target but it's safe to use in an app extension. Thanks for your suggestion, we can add some documentation about app extensions.

**Comment by zihejia** [comment]
Hi @abotkin-cpi , we have released v3.3.6 which contains the setting "Require Only App-Extension-Safe API" , thanks for raising this! Closing this one for now.
