### ISSUE TITLE
App archive fails on Xcode 10

### ISSUE THREAD

**Issue by AndrewSava** [mixpanel/mixpanel-iphone#797]
**Integration Method:** CocoaPods
**Xcode Version:** 10.0 (10A255)
**Library Version:** 3.1.1
**Platform:** iOS / App Extension
**Language:** Swift and Objective-C mixed
**Description:**  
We use Mixpanel in the app and also in the app extensions, like so:
  pod 'Mixpanel'
and
   pod 'Mixpanel/AppExtension'
which used to always build and archive.
 
Since Xcode 10, which uses the New Build System, build works, but the command Product > Archive fails with this error:
 
Multiple commands produce '/Users/andrei.sava/Library/Developer/Xcode/DerivedData/Blur-cczmimwmnkjulxgkelpxcvzsahow/Build/Intermediates.noindex/ArchiveIntermediates/Avira Password Manager/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Mixpanel.framework':
1) Target 'Mixpanel-AppExtension' has create directory command with output '/Users/andrei.sava/Library/Developer/Xcode/DerivedData/Blur-cczmimwmnkjulxgkelpxcvzsahow/Build/Intermediates.noindex/ArchiveIntermediates/Avira Password Manager/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Mixpanel.framework'
2) Target 'Mixpanel' has create directory command with output '/Users/andrei.sava/Library/Developer/Xcode/DerivedData/Blur-cczmimwmnkjulxgkelpxcvzsahow/Build/Intermediates.noindex/ArchiveIntermediates/Avira Password Manager/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Mixpanel.framework'
 
And multiple warnings of type „unexpected mutating task” and „duplicate output file”.

**Expected Behavior:** Product should build properly, as on previous Xcode versions

**Comment by zihejia** [comment]
Hi @AndrewSava , thanks for raising this, we are working on New Build System support now. In the meantime, as a workaround, you might try to build system to Legacy,
File > Workspace Settings > Build System > Legacy Build System.

**Comment by zihejia** [comment]
Or if you could please use latest version for this issue. After v3.2.3, we consolidated 'Mixpanel-AppExtension' into 'Mixpanel' target, so it should work for the new build system for app archive.

**Comment by AndrewSava** [comment]
Hi @zihejia, thanks for your reply, the key statement here is " we consolidated 'Mixpanel-AppExtension' into 'Mixpanel' target ".  
We replaced our Mixpanel-AppExtension with Mixpanel in the Podfile and then we could successfully upgrade to v3.3.3. Because keeping both targets made the pod update impossible. 
With 3.3.3 the Archive builds fine.

**Comment by zihejia** [comment]
Thanks @AndrewSava , closing this one for now.
