### ISSUE TITLE
Capitalization issue with macOS Target

### ISSUE THREAD

**Issue by githubparlajoie** [mixpanel/mixpanel-iphone#815]
**Integration Method:** Manual
**Xcode Version:** -
**Library Version:** -
**Platform:** macOS
**Language:** Objective-C
**Description:** The project does not build because there is a capitalization issue for the Mixpanel-macOS-info.plist file. On disk, it's "Mixpanel-macOS-Info.plist", in the macOS Target Build Settings > Packages, it's "Mixpanel-macOS-Info.plist" 
**Expected Behavior:**  It builds.

**Comment by zihejia** [comment]
Hi @githubparlajoie , we have released v3.3.9 and has a fix for it. Thanks again!
https://github.com/mixpanel/mixpanel-iphone/releases/tag/v3.3.9
