### ISSUE TITLE
User Id not attached to events after createAlias call

### ISSUE THREAD

**Issue by lordcodes** [mixpanel/mixpanel-iphone#824]
**Integration Method:** CocoaPods
**Xcode Version:** 10.1
**Library Version:** 3.3.8
**Platform:** iOS
**Language:** Swift

**Description:** 
We are using the MixPanel-iPhone dependency (as opposed to Swift one), as it is being used via Segment.

After creating an account in our app `createAlias` is being called, passing in our user GUID. The MixPanel iPhone SDK makes the `identity` call for us and then later on we use it again to register some super/people properties.

We have noticed an issue, in that after `createAlias` is called, all events that come in during that session do not have a 'User Id' attached to them (which would equal our user GUID that is passed to our own identify call). Whereas in our webapp which uses the MixPanel JS dependency this was all working correctly.

From comparing your JS framework and your iPhone framework, I noticed an inconsistency in that in the JS one the user ID is attached **before** the check for the alias but the iPhone one attaches this **after**.

JS: https://github.com/mixpanel/mixpanel-js/blob/master/src/mixpanel-core.js#L1541
iPhone: https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L447

I believe where it is set in the iPhone SDK is a bug, as it means that if you call `createAlias`, your user ID won't be attached to events and won't appear in the MixPanel dashboard at all. Then, on the next session when you only call `identify` User Id will be attached and will now show in dashboard on those events.

For the time being I have create a workaround to the issue:

- Call `createAlias`
- Call `reset` - to clear the locally cached alias
- Call `identify` - providing own our user Guid

After these steps everything works as expected.

**Expected Behavior:** 

User Id is correctly attached to events in the MixPanel dashboard, whether `createAlias` is called or not.

**Comment by lordcodes** [comment]
I have updated the issue description and title, after more investigating discovering what the real issue was.

**Comment by ozgur** [comment]
Any update on this? It seems to be a really nasty bug.

**Comment by zkhalapyan** [comment]
Yep, seeing something similar as well. After calling createAlias, the subsequent events, for a short period of time, are completely ignored! Events just silently dropped.

**Comment by zkhalapyan** [comment]
@lordcodes in my case following your workaround actually lead to significant event loss. The first twenty or so events got discarded and the alias was also not registered at all as distinct ID was switch to email (it's supposed to remain to the random assigned UUID if createAlias works).

**Comment by zkhalapyan** [comment]
@zihejia @dneralla any updates on this? Seems like a sever error and events are going to be missing without your customers knowing 😢

**Comment by zihejia** [comment]
hi @zkhalapyan , which version are you using? We will have a look.

**Comment by zihejia** [comment]
Please try the latest v4.0.0. It has a lot of improvement to the core tracking and flushing. If anyone still experience any similar issue, please feel free to reopen.
