### ISSUE TITLE
Carrier event property is not the active carrier

### ISSUE THREAD

**Issue by aldukeman** [mixpanel/mixpanel-iphone#825]
**Integration Method:** CocoaPods
**Xcode Version:** 10.1
**Library Version:** 3.3.9
**Platform:** iOS
**Language:** Swift / Objective-C
**Description:** 

iPhone Xr on iOS 12.1.2 with physical SIM from vodafone IE and eSIM from AT&T installed. The physical SIM is turned off and the eSIM is turned on in the OS settings. The carrier value reported for all events is vodafone IE, when I would expect it to be the carrier for the active SIM, AT&T.

**Comment by zihejia** [comment]
HI @aldukeman ,  we released a new version [v3.6.1]( https://github.com/mixpanel/mixpanel-iphone/releases/tag/v3.6.1) which contains a fix for this issue. I'm closing this issue for now, please feel free to to reopen it if the problem still exists.
