### ISSUE TITLE
Comparison of integers of different signs: 'int' and 'NSUInteger' (aka 'unsigned long')

### ISSUE THREAD

**Issue by piaojin** [mixpanel/mixpanel-iphone#838]
**Integration Method:** CocoaPods / Carthage / Manual
`The source code`

**Xcode Version:** 
`10.1`

**Library Version:** 

**Platform:** iOS / App Extension / watchOS / tvOS
`iOS`

*Language:** Swift / Objective-C
`Objective-C`

**Description:** 
I encountered this error when I compiled the mixpanel source code in my project. (in `MPValue.m`, `MixpanelExceptionHandler.m`, `Mixpanel.m`)

**Error:**

`Comparison of integers of different signs: 'int' and 'NSUInteger' (aka 'unsigned long')`
![CD139EC1-8F08-479B-AD9C-ACA8225195FE](https://user-images.githubusercontent.com/10163672/54976276-d2372080-4fd4-11e9-8800-1b5e28128464.png)

**Solution:**
Replace int with NSUInteger fix this issue.

**Expected Behavior:** 
It is better to fix the issue through the authorities.

**Comment by zihejia** [comment]
Hi @piaojin , we have released v3.4.5 that fixed the issue. Thanks! https://github.com/mixpanel/mixpanel-iphone/releases/tag/v3.4.5
Closing this one out, please let me know if you're still experiencing

**Comment by piaojin** [comment]
> Hi @piaojin , we have released v3.4.5 that fixed the issue. Thanks! https://github.com/mixpanel/mixpanel-iphone/releases/tag/v3.4.5
> Closing this one out, please let me know if you're still experiencing

The issue has been fixed. Thank you. @zihejia
