### ISSUE TITLE
unused variable `success` in release version.

### ISSUE THREAD

**Issue by piaojin** [mixpanel/mixpanel-iphone#842]
**Integration Method:** CocoaPods / Carthage / Manual
`The source code`

**XcodeBuild:** 
`10.2`

**Library Version:** 

**Platform:** iOS / App Extension / watchOS / tvOS
`iOS`

*Language:** Swift / Objective-C
`Objective-C`

**Description:** 
The `xcodebuild` cannot build the mixpanel source in the release version. But works fine in debug version. The root cause is 
```
BOOL success = [reason getBytes:(char *)mutablePayload.mutableBytes + sizeof(uint16_t) maxLength:payload.length - sizeof(uint16_t) usedLength:&usedLength encoding:NSUTF8StringEncoding options:NSStringEncodingConversionExternalRepresentation range:NSMakeRange(0, reason.length) remainingRange:&remainingRange];
            assert(success);
``` 
the variable `success` in file `MPWebSocket.m` function `- (void)closeWithCode:(NSInteger)code reason:(NSString *)reason` is unused in release version. The assert only works in debug version. It means that the variable `success` only be used in debug version and is unused in the release version.

**Solution:**
Adding 
```
MPLogDebug(@"%d", success);
```
So that the variable `success` can be used in the release version.

**Expected Behavior:** 
It is better to fix the issue through the authorities.

**Comment by zihejia** [comment]
Hi @piaojin , the issue has been fixed in https://github.com/mixpanel/mixpanel-iphone/releases/tag/v3.4.8

**Comment by piaojin** [comment]
Hi @zihejia, thanks.
