### ISSUE TITLE
Support present an in-app message panel.

### ISSUE THREAD

**Issue by piaojin** [mixpanel/mixpanel-iphone#843]
**Integration Method:** CocoaPods / Carthage / Manual
`The source code`

**Xcode Version:** 
`10.1`

**Library Version:** 

**Platform:** iOS / App Extension / watchOS / tvOS
`iOS`

**Language:** Swift / Objective-C
`Objective-C`

**Description:** 
In-app messages panel show in a new UIWindow and the UIWindow's level is highest. The application default UIWindow will be covered. In our business,  if there is an incoming call and the incoming call screen in the application default UIWindow will be covered as well. In fact, the level of the incoming call screen should be the highest and it cannot be covered.  We recommend displaying in-app messages panel by presenting a new controller in the application default UIWindow rather than adding a new UIWindow.

**Such as:**
```
- (void)show2 {
    [self.modalViewController presentViewController:self animated:YES completion:nil];
}
```

```
@implementation UIViewController (MPNotificationViewController)

- (UIViewController *) rootViewController;
{
    return UIApplication.sharedApplication.keyWindow.rootViewController;
}

- (UIViewController *) modalViewController;
{
    return [[self rootViewController] topModalViewController];
}

- (UIViewController *) topModalViewController;
{
    UIViewController *viewController = self;
    UIViewController *modalViewController = nil;
    
    while ((modalViewController = [viewController presentedViewController]))
    {
        viewController = modalViewController;
    }
    
    return viewController;
}

@end
```

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features, please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation. Sorry for the inconvenience.
