### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by nagendraK6** [mixpanel/mixpanel-iphone#846]
**Integration Method:** CocoaPods 
**Xcode Version:**  Version 10.2 (10E125)
**Library Version:**  Using Mixpanel (3.3.7)
**Platform:** iOS 
**Language:** Objective-C
**Description:** 

used cocoa pod to install Mixpanel.
Build is throwing error 

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Mixpanel", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Expected Behavior:** 
Build should work without error

**Comment by nagendraK6** [comment]
:-1: Undefined symbol: _OBJC_CLASS_$_Mixpanel

**Comment by zihejia** [comment]
hi @nagendraK6 , have you tried a clean build? Also please try 3.4.5 which has official Xcode 10.2 support.

**Comment by zihejia** [comment]
I'm closing this one now, please let me know if the problem still exists on the latest version and I will reopen it.
