### ISSUE TITLE
Why can't tableView cell set click events?

### ISSUE THREAD

**Issue by brave723** [mixpanel/mixpanel-iphone#849]
**Integration Method:** CocoaPods
**Xcode Version:** 10.2
**Library Version:** 3.4.5
**Platform:** iOS
**Language:**  Objective-C
**Description:**  Why can't tableView cell set click events?

![tableView](https://user-images.githubusercontent.com/1267034/58935130-185feb80-879f-11e9-96a6-f97de6d8239c.png)

**Expected Behavior:** Every cell in the row of the tableView can set the click event

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
