### ISSUE TITLE
MixpanelGroupPrivate.h: compiler issue with include using angles instead of quotes

### ISSUE THREAD

**Issue by samzilverberg** [mixpanel/mixpanel-iphone#852]
while compiling the mixpanel code the compiler errors here
https://github.com/mixpanel/mixpanel-iphone/blob/5ddcc639620f296023bed91b11a767ccbda9f3f7/Mixpanel/MixpanelGroupPrivate.h#L8
 with:
```
error: 'MixpanelType.h' file not found with
      <angled> include; use "quotes" instead
#import <MixpanelType.h>
        ^~~~~~~~~~~~~~~~
        "MixpanelType.h"
```
i can probably set some compiler flags or some local setting to ignore this, but googling directly pointed out that `<>` usage is reserved for frameworks, and a file import should be done with double quotes '""`.

https://stackoverflow.com/questions/17465902/use-of-external-c-headers-in-objective-c

i did a search over the files for `#import <` and i think this is the only "wrong" usage of angles.

could you fix this very little issue for next release?

**Comment by zihejia** [comment]
hi @samzilverberg , thanks for raising it. will fix it.

**Comment by zihejia** [comment]
Thanks @samzilverberg , the fix has been merged into master and it will be picked up in the next release
