### ISSUE TITLE
Compilation error on Xcode 10.3

### ISSUE THREAD

**Issue by graver** [mixpanel/mixpanel-iphone#856]
**Integration Method:** CocoaPods
**Xcode Version:** 10.3
**Library Version:** 3.4.7
**Platform:** iOS
**Language:** Objective-C
**Description:** Compilation fails with the following error: 

```
Pods/Mixpanel/Mixpanel/MPTakeoverNotificationViewController~iphoneportrait.xib:-1: Failed to find or create execution context for description '<IBCocoaTouchPlatformToolDescription: 0x7faf7d866a10> System content for IBCocoaTouchFramework-EightAndLater <IBScaleFactorDeviceTypeDescription: 0x7faf7d866590> scaleFactor=2x'. These intermediate objects were non-nil: (
MPTakeoverNotificationViewController~iphoneportrait.xib
```

**Expected Behavior:** Complication succeeds

**Comment by graver** [comment]
This was a derived data issue. Sorry for the red herring.

**Comment by nickgarfield** [comment]
@graver which steps did you take to resolve this? I deleted everything in Derived Data, but am still experiencing this error after cleaning and re-building.

**Comment by BeechMachine** [comment]
@graver same. Cleaned the build and deleted Derived Data but that didn't fix the issue.

**Comment by graver** [comment]
@nickgarfield @BeechMachine I closed Xcode, deleted everything in the derived data folder, and relaunched and rebuilt. Nothing out of the ordinary on that front.

**Comment by BeechMachine** [comment]
@nickgarfield - in case this helps. I did the same as @graver, but I also restarted my computer. It started working after that :)

**Comment by erdinc** [comment]
no luck at my site,

deleted derived data,
deleted pods folder and reinstalled
restart xcode

same error.

**Comment by zihejia** [comment]
hi @erdinc, have you tried to reboot your computer?

**Comment by awschuerholz** [comment]
This usually happens because of a hung ibtoold process:

```
launchctl bootout user/$UID/com.apple.CoreSimulator.CoreSimulatorService
pkill -KILL -x -U $UID ibtoold
rm -rf ~/Library/Developer/Xcode/DerivedData
```
