### ISSUE TITLE
Use of outdated hashing function - CC_MD5

### ISSUE THREAD

**Issue by martianplatypus** [mixpanel/mixpanel-iphone#858]
**Integration Method:** CocoaPods / Carthage / Manual
**Xcode Version:** Version 10.1 (10B61)
**Library Version:** v3.4.7
**Platform:** iOS / App Extension / watchOS / tvOS
**Language:** Objective-C

**Description:** 
The method `- (NSString *)getImageHash:(NSData *)imageData` in `MPABTestDesignerSnapshotResponseMessage` class uses the MD5 algorithm to obtain the hash string of a screenshot, which is then set in the payload object, as seen in `- (void)setScreenshot:(UIImage *)screenshot`. 

Such hashing algorithm is known to be not fully collision resistant, and therefore is vulnerable to collision attacks.  See [M5 - Insufficient Cryptography](https://www.owasp.org/index.php/Mobile_Top_10_2016-M5-Insufficient_Cryptography) for reference.

Even though the code is not used in a security context, it should be updated to use a different hashing algorithm because MD2 and MD5 (CC_MD functions) will be deprecated when the iOS 13 SDK is officially released. As stated in the CommonCrypto headers: 
> This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger). [-Werror,-Wdeprecated-declarations]

**Solution:**
Switch from using the soon-to-be deprecated MD5 algorithm to a stronger one, such as SHA-256 or SHA-512

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
