### ISSUE TITLE
Use of weak hash algorithm - CC_SHA1

### ISSUE THREAD

**Issue by martianplatypus** [mixpanel/mixpanel-iphone#859]
**Integration Method:** CocoaPods / Carthage / Manual
**Xcode Version:** Version 10.1 (10B61)
**Library Version:** v3.4.7
**Platform:** iOS
**Language:** Objective-C
**Description:** 
Similar to #858, `MPWebSocket stringBySHA1ThenBase64Encoding` uses the SHA-1 hashing algorithm. This algorithm is considered cryptographically weak and its usage is not recommended.

**Solution:**
As stated in [iOS 13 CryptoKit documentation](https://developer.apple.com/documentation/cryptokit/insecure/sha1), update the code to use a stronger hash algorithm, like SHA-512.

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
