### ISSUE TITLE
Put image files in Asset Catalog 

### ISSUE THREAD

**Issue by maremmle** [mixpanel/mixpanel-iphone#86]
Since iOS 7 image files can be stored nicely in asset catalogs. As a project can contain unlimited amount of asset catalogs and i suggest to create an asset catalog for all the image files that come with Mixpanel. 

Note on iOS 6 and prior: As an asset catalog is just a directory containing the image files and some meta data files, the images still can be used in older project too.

**Comment by samgreen** [comment]
This change has been done.
