### ISSUE TITLE
Crash when deploying to WatchOS 5 from Xcode 11

### ISSUE THREAD

**Issue by tealshift** [mixpanel/mixpanel-iphone#866]
**Integration Method:** CocoaPods
**Xcode Version:** 11 GM Seed 2
**Library Version:** 3.4.9
**Platform:** watchOS 5.3.1
**Language:** Swift & Objective-C
**Description:** I get this https://stackoverflow.com/questions/57979776/dyld-abort-with-payload-crash-from-xcode-11-on-watchos-5?noredirect=1#comment102375400_57979776 crash on launch. Removing the pod resolves the mysterious crash.
I don't know if it matters, but the parent iOS app contains the 'Mixpanel-swift' pod.
**Expected Behavior:** App should launch normally

**Comment by zihejia** [comment]
Hi @tealshift , are you using Mixpanel swift library, if so, do you mind if you open a new ticket there and close this one? https://github.com/mixpanel/mixpanel-swift. I will take a look in the meantime. Thanks for bringing it up.

**Comment by tealshift** [comment]
Actually, the pod I'm trying to use in the watch extension is 'Mixpanel', even though the iOS app uses 'Mixpanel-swift'. It's confusing, sorry. I don't think Mixpanel-swift supports watchOS, which is rather inconvenient.

**Comment by zihejia** [comment]
hi @tealshift , `Mixpanel-swift` does supports watchOS, please give it a go. Mix them together will cause some problem.

**Comment by tealshift** [comment]
Ok, I must have gotten myself confused. I just retested, and `Mixpanel-swift` causes this very same crash. It's installed in both iOS app and Watch extension. (dear gods, deploying to Apple Watch takes like 20 minutes) 
I think I will open this issue on the swift project GitHub. Thanks for your tips!

**Comment by tealshift** [comment]
Reopened here: https://github.com/mixpanel/mixpanel-swift/issues/329
