### ISSUE TITLE
iOS Mixpanel Library Crashes in -[MixpanelExceptionHandler mp_handleUncaughtException:] on iOS 13

### ISSUE THREAD

**Issue by jeffhunter** [mixpanel/mixpanel-iphone#867]
**Integration Method:** Carthage
**Xcode Version:** 11.0
**Library Version:** 3.4.9
**Platform:** iOS
**Language:** Objective-C
**Description:** 
We are observing numerous crashes in `-[MixpanelExceptionHandler mp_handleUncaughtException:]` in iOS 13. This is with the latest version of the Mixpanel library (3.4.9). Stack trace looks like this:

```
Crashed: com.apple.main-thread
0  libsystem_platform.dylib       0x19b54a598 _os_unfair_lock_recursive_abort + 36
1  libsystem_platform.dylib       0x19b54853c _os_unfair_lock_lock_slow + 300
2  libobjc.A.dylib                0x19b57eaec objc_loadWeakRetained + 108
3  libobjc.A.dylib                0x19b57ecc8 objc_loadWeak + 20
4  Foundation                     0x19bb21630 -[NSConcreteHashTable countByEnumeratingWithState:objects:count:] + 140
5  Mixpanel                       0x100916c08 -[MixpanelExceptionHandler mp_handleUncaughtException:] + 133 (MixpanelExceptionHandler.m:133)
6  Mixpanel                       0x100916a68 MPSignalHandler + 100 (MixpanelExceptionHandler.m:100)
7  libsystem_platform.dylib       0x19b54a894 _sigtramp + 56
8  libsystem_kernel.dylib         0x19b636f1c abort_with_payload_wrapper_internal + 100
9  libsystem_kernel.dylib         0x19b636eb8 abort_with_payload_wrapper_internal + 26
10 libobjc.A.dylib                0x19b580254 _objc_fatalv(unsigned long long, unsigned long long, char const*, char*) + 104
11 libobjc.A.dylib                0x19b5801ec _objc_fatalv(unsigned long long, unsigned long long, char const*, char*) + 26
12 libobjc.A.dylib                0x19b57c974 weak_clear_no_lock + 314
13 libobjc.A.dylib                0x19b57e324 objc_storeWeak + 332
```

This message is also available:

`BUG IN CLIENT OF LIBPLATFORM: Trying to recursively lock an os_unfair_lock`

I believe that 100% of the crashes are occurring on iOS 13.0.

**Comment by zihejia** [comment]
hi @jeffhunter , thanks for bringing it up. We will release a new version with full iOS 13 support

**Comment by mwasim22** [comment]
Any update over this @zihejia ??

**Comment by zihejia** [comment]
Hi @jeffhunter @mwasim22 We have released a version with a fix to this problem. 
https://github.com/mixpanel/mixpanel-iphone/releases/tag/v3.5.0
I'm closing this one now. Please feel free to reopen it if the problem still exists. Thanks!
