### ISSUE TITLE
iOS Deployment target issue

### ISSUE THREAD

**Issue by gligorkot** [mixpanel/mixpanel-iphone#870]
https://github.com/mixpanel/mixpanel-iphone/blob/5be3385af99f3c4cd4c1971b834e45c41576f48e/Mixpanel.podspec#L12

Some features in the Mixpanel code are using `UNUserNotificationCenter` which is only available on iOS 10.0 and above, so deployment target needs to be adjusted to 10.0 and above, otherwise there are warnings in the code.

<img width="370" alt="Screen Shot 2019-11-14 at 3 58 59 PM" src="https://user-images.githubusercontent.com/7002604/68823270-27f14200-06f8-11ea-8b2b-2d05c4ae5da6.png">

**Comment by tmm1** [comment]
Ping?

**Comment by zihejia** [comment]
hi @gligorkot @tmm1  We released a new version [v3.6.1]( https://github.com/mixpanel/mixpanel-iphone/releases/tag/v3.6.1) which contains a fix for this issue. I'm closing this issue for now, please feel free to to reopen it if the problem still exists.

**Comment by gligorkot** [comment]
Thanks!
