### ISSUE TITLE
Feature: Orientation default property

### ISSUE THREAD

**Issue by a-kriya** [mixpanel/mixpanel-iphone#873]
It'd be useful to know if users prefer to perform certain actions in landscape mode compared to portrait, or vice-versa.

Was slightly surprised when I noticed that this isn't already a default prop and that there are no existing feature reqs for it in the issues section here. I thought it may be possible in the MixPanel dashboard to filter the events where "screen height < screen width", but it looks like comparison can only be performed against hard values, and not another prop.

Filing this ticket to gauge interest of the community, and if it seems specific to my case, I'll go the route of adding it as a super prop.

**Comment by zihejia** [comment]
hi @a-kriya , you can create a custom property to achieve this. https://help.mixpanel.com/hc/en-us/articles/360030848432-Custom-Properties.  I'm closing this one now, if you have any question to Mixpanel, you can also have a look at Mixpanel community. https://community.mixpanel.com/
