### ISSUE TITLE
Crash: __27-[Mixpanel setCurrentRadio]_block_invoke + 4308353040

### ISSUE THREAD

**Issue by zhangduyu** [mixpanel/mixpanel-iphone#876]
**Integration Method:** CocoaPods
**Xcode Version:** 11.2.1
**Library Version:** 3.4.9
**Platform:** iOS
**Language:**  Objective-C
**Description:** I got a crash report from firebase, please help to take a look.
**Expected Behavior:** 

Crashed: com.mixpanel.e522cfb5a28d8a0c008957e7f6bfdd3d.0x107736060EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000008 Raw Text
--
0 | CoreFoundation | -[__NSDictionaryM objectForKeyedSubscript:] + 148
1 | (Missing) | (Missing)
2 | (Missing) | (Missing)
3 | Chope | **Mixpanel.m line 1474__27-[Mixpanel setCurrentRadio]_block_invoke + 4308353040**
4 | libdispatch.dylib | _dispatch_call_block_and_release + 32

**Comment by JMStack** [comment]
same issue

**Comment by zihejia** [comment]
hi @zhangduyu @JMStack ,  We released a new version [v3.6.1]( https://github.com/mixpanel/mixpanel-iphone/releases/tag/v3.6.1) which contains a fix for this issue. I'm closing this issue for now, please feel free to to reopen it if the problem still exists.
