### ISSUE TITLE
Crash: MPSwizzler.m line 

### ISSUE THREAD

**Issue by zhangduyu** [mixpanel/mixpanel-iphone#877]
**Integration Method:** CocoaPods
**Xcode Version:** 11.2.1
**Library Version:** 3.4.9
**Platform:** iOS
**Language:** Objective-C
**Description:** I got a crash report from firebase, please help to take a look it.
**Expected Behavior:** 

Crashed: com.apple.main-threadEXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000fbcacc4a0 Raw Text
--
0 | libobjc.A.dylib | objc_release + 16
**1 | Chope | MPSwizzler.m line 44mp_swizzledMethod_2 + 44**
2 | UIKitCore | -[UIView(Internal) _didMoveFromWindow:toWindow:] + 1824
39 | UIKitCore | UIApplicationMain + 1936
40 | Chope | main.m line 21main + 21
41 | libdyld.dylib | start + 4

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
