### ISSUE TITLE
Mixpanel().showNotification() throws an EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by restys** [mixpanel/mixpanel-iphone#880]
Xcode 11.3.1

When trying to call Mixpanel().showNotification() after setting showNotificationOnActive = true

error is on Mixpanel.m line 983:
    dispatch_async(self.serialQueue, ^{
        dispatch_async(self.networkQueue, dispatchBlock);
    });

Tried calling from main thread, background thread and also adding delay. All leads to the same error.

**Comment by zihejia** [comment]
Hi @restys , would you please share the full error log?

**Comment by zihejia** [comment]
hi @restys , I'm closing this one now. Please feel free to reopen it by providing more information, like sdk version, ios version, full crash log etc. Thanks!
