### ISSUE TITLE
Add Swift Package Manager Support

### ISSUE THREAD

**Issue by SmartAkashNara** [mixpanel/mixpanel-iphone#883]
Add Swift Package Manager Support

![Screenshot 2020-03-04 at 12 12 06 PM](https://user-images.githubusercontent.com/61772249/75851993-020bbc80-5e11-11ea-8fe7-5358b307ff49.png)

**Comment by zihejia** [comment]
hi @SmartAkashNara , we have an existing issue for adding Swift Package Manager Support under Mixpanel swift repo https://github.com/mixpanel/mixpanel-swift/issues, I'm closing this one now.
