### ISSUE TITLE
Issue auto-generating unique distinctId to enable multiple users on same device

### ISSUE THREAD

**Issue by amuresia** [mixpanel/mixpanel-iphone#884]
**Integration Method:** CocoaPods
**Xcode Version:** 11.3.1
**Library Version:** 
```
  - Mixpanel-swift (2.7.0):
    - Mixpanel-swift/Complete (= 2.7.0)
  - Mixpanel-swift/Complete (2.7.0)
  - Mixpanel-swift
    - Mixpanel-swift
  Mixpanel-swift: af074beb44bdac38ab611e1d575a073bbb3d6780
```
**Platform:** iOS
**Language:** Swift
**Description:** 
I want to correctly identify users that have not signed up/ logged in yet.
I tried different approaches but if several users sign up using the same device, then the people profiles in mixpanel get messed up due to the IFA being 0000-...
# Scenario 1:
User installs the app and creates a new account. 
I expect one user profile to be created with the following activities visible:
- Signed up
- Verified account
# Scenario 2
User installs the app, creates a new account and logs out. The user creates another account on the same device.
I expect two user profiles to appear in mixpanel:
### User 1:
- Signed up
- Verified account
- Signed out
### User 2:
- Signed up
- Verified account

I was reading the docs that suggest setting `MIXPANEL_RANDOM_DISTINCT_ID=1` but that didn't seem to work, the distinctId was still 0000-...
Also, this issue https://github.com/mixpanel/mixpanel-iphone/issues/112 suggests that it should be `MIXPANEL_NO_IFA`.
I am not really sure how to proceed, could you please advise?

PS: I tried assigning a random UUID after calling mixpanel.reset() when the user signed out. However, user 2 did not appear at all in mixpanel.

## Code snippets:
On startup I assume that I have to create a new alias and I proceed to check if the user is logged in
```
if isLoggedIn {
            createMixpanelAlias = false
            prepareSessionForAuthenticatedUser()
        }
        else {
            mixpanel.identify(distinctId: NSUUID().uuidString)
        }
```
Note: If the user signed up then I set `createMixpanelAlias = true`
```
fileprivate func prepareSessionForAuthenticatedUser() {
            if self.createMixpanelAlias {
                self.mixpanel.createAlias(user.id, distinctId: self.mixpanel.distinctId);
            }
            self.mixpanel.identify(distinctId: user.id)
            self.mixpanel.people.set(properties: [ "$email": user.email,
                                                   "$first_name": user.firstName,
                                                   "$last_name": user.lastName,
                                                   "$name": user!.firstName + " " + user!.lastName
            ])
        }
}
```
On sign out I reset and create a new UUID.
```
mixpanel.track(event: "Signed out")
isLoggedIn = false
mixpanel.reset()
mixpanel.identify(distinctId: NSUUID().uuidString)
```

**Comment by zihejia** [comment]
hi @amuresia , thanks for bring this up. Are you using swfit? If so,  would you move this issue to Mixpanel swift repo? https://github.com/mixpanel/mixpanel-swift/issues. I will take a look.
I'm closing this one now.
