### ISSUE TITLE
Rich Push Notifications actions not working

### ISSUE THREAD

**Issue by yarikpwnzer** [mixpanel/mixpanel-iphone#887]
**Integration Method:** CocoaPods
**Xcode Version:**  11.3.1
**Library Version:** 3.6.0
**Platform:** iOS
**Language:** Objective-C
**Description:**
1. Make Rich Push notifications with buttons with actions to redirect to url or deep link.
2. Click on notification button.
3. App will be opened on home screen without redirection to specific url or deep link inside app.

**Expected Behavior:** 
App should be redirected to specific url or deep link inside app.

P.S. From debugging I see that Mixpanel SDK use deprecated method openUrl:.

**Comment by jbwyme** [comment]
Thanks for the report @yarikpwnzer! Can you confirm that you've [delegated the handling of the notification response to the Mixpanel SDK](https://github.com/mixpanel/mixpanel-iphone#4-delegate-the-handling-of-the-notification-response-to-the-mixpanel-sdk)?

**Comment by yarikpwnzer** [comment]
@jbwyme missed that, closing the issue. Thank You!

**Comment by yarikpwnzer** [comment]
@jbwyme ah I didn't miss that :) I see documentation was changed 22 days ago...

**Comment by yarikpwnzer** [comment]
@jbwyme update it here also https://developer.mixpanel.com/docs/ios-push-notifications
