### ISSUE TITLE
Architectures Intel 32-bit when submit to the App Store

### ISSUE THREAD

**Issue by KAMIKAZEUA** [mixpanel/mixpanel-iphone#891]
**Integration Method:**  Manual
**Xcode Version:** 111.4
**Library Version:** 3.6.0
**Platform:** iOS 
**Language:** Objective-C
**Description:** 

When I submit my app I got this warning: 
<img width="468" alt="Screenshot" src="https://user-images.githubusercontent.com/3391456/78717717-b8d7ec80-7929-11ea-9b6d-6ceec94c8e64.png">

This is wrong, because its iOS, why to include desktop arch's in the lib? 

**Expected Behavior:** 
Don't use **wrong** architectures and no warnings when submitting for App Store.

**Comment by E-MIII** [comment]
Hey it’s been so nice to have you guys back in my life

**Comment by zihejia** [comment]
hi @KAMIKAZEUA , the issue has been fixed in [v3.6.1]( https://github.com/mixpanel/mixpanel-iphone/releases/tag/v3.6.1). I'm closing this issue for now, please feel free to to reopen it if the problem still exists.
