### ISSUE TITLE
socket:  code:1001 reason :Stream end encountered

### ISSUE THREAD

**Issue by AracyGit** [mixpanel/mixpanel-iphone#893]
**Integration Method:** CocoaPods
**Xcode Version:** 11.3.1
**Library Version:** 
**Platform:** iOS 
**Language:** Objective-C  
**Description:** 
**Expected Behavior:** 

"webSocketDidOpen" then "didCloseWithCode" 
 code:1001 reason :Stream end encountered

socket url is "wss://switchboard.mixpanel.com/connect?key=***&type=device"

**Comment by zihejia** [comment]
Hi @AracyGit , do you still have the issue? It might be a connectivity issue at that point. I will close this one now but please contact  Mixpanel support if the problem exists or reopen it if you think this is SDK related.
