### ISSUE TITLE
MPNotificationServiceExtension crash when mp_media_url is empty string

### ISSUE THREAD

**Issue by jmartini** [mixpanel/mixpanel-iphone#901]
**Integration Method:** CocoaPods
**Xcode Version:** 11.4.1
**Library Version:** 3.6.1
**Platform:** App Extension
**Language:** Objective-C
**Description:** 
The MPNotificationServiceExtention will cause an uncaught exception if the payload contains an empty string for payload field "mp_media_url":
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:`

To create an empty "mp_media_url" payload: 

1.  In the Mixpanel message creator, enter any text into "Image url" field. 
2.  Save the message.
3.  Remove text from "Image url" field. Note that the UI now shows the default, example url in this field now.

This message will now send the empty "mp_media_url". 

**Expected Behavior:** 
No crash if "mp_media_url" is an empty string.

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
