### ISSUE TITLE
Rich push notifications 3.6.0 CocoaPods with no `use_frameworks!` 

### ISSUE THREAD

**Issue by MoeMamdouh** [mixpanel/mixpanel-iphone#905]
**Integration Method:** CocoaPods with no `use_frameworks!` 
**Xcode Version:** 11.5
**Library Version:** 3.6.0
**Platform:** iOS
**Language:** Objective-C - react-native
**Description:** 
i'm using ios sdk version 3.6.0 and follow the docs to integrate with the MixpanelNotificationServiceExtension but i can't use `use_frameworks!`  in pod [here](https://github.com/mixpanel/mixpanel-iphone#2-add-mixpanel-as-a-dependency)
the issue is the mixpanel not founded in NotificationService.h

<img width="909" alt="Screen Shot 2020-06-22 at 11 45 06 PM" src="https://user-images.githubusercontent.com/16561058/85338688-0c96b280-b4e3-11ea-8340-b4474fcbf02a.png">

and the rich PN is not working

**Comment by Minishlink** [comment]
Replace the import with `#import "Mixpanel/MPNotificationServiceExtension.h"`

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
