### ISSUE TITLE
Data is not refreshing in MixPanel Dashboard.

### ISSUE THREAD

**Issue by kiranSDM** [mixpanel/mixpanel-iphone#906]
**Integration Method:** CocoaPods / Carthage / Manual
CocoaPods
**Xcode Version:** 
11.2.1
**Library Version:** 
Latest 
**Platform:** iOS / App Extension / watchOS / tvOS
iOS
**Language:** Swift / Objective-C
Swift
**Description:** 
My data is not reflecting on the dashboard report.My token is correct, report is correct but the events names and count are not correct in the reports. Insight report is also not showing list of events. It is not working as expected.
 Mixpanel.mainInstance().optInTracking() i call this only once when app launches after initialising the Mixpanel with Token.
Mixpanel.mainInstance().track(event:"EventName",
                                      properties: ["key": "value"]) 
**Expected Behavior:** 
Data should reflect on server in few minutes.Reports should show all events.

**Comment by zihejia** [comment]
hi @kiranSDM , I'm really sorry for the late response. You can reach out to our support to get a timely answer next time(https://help.mixpanel.com/hc/en-us/requests/new). Since it's not SDK related, I'm closing this one now.
