### ISSUE TITLE
Expose flushInterval with (Mixpanel *)sharedInstanceWithToken method

### ISSUE THREAD

**Issue by lorenc-tomasz** [mixpanel/mixpanel-iphone#911]
When using `+ (Mixpanel *)sharedInstanceWithToken:(NSString *)apiToken launchOptions:(NSDictionary *)launchOptions trackCrashes:(BOOL)trackCrashes automaticPushTracking:(BOOL)automaticPushTracking optOutTrackingByDefault:(BOOL)optOutTrackingByDefault` flushInterval param is set either to 1 or to 60 seconds if no instace is exist. Maybe it's good to consider exposing this param on that methids?

**Comment by zihejia** [comment]
Hi @lorenc-tomasz , Sorry for the late response. you can use [initWithToken:launchOptions:flushInterval:trackCrashes:](https://mixpanel.github.io/mixpanel-iphone/Classes/Mixpanel.html#//api/name/initWithToken:launchOptions:flushInterval:trackCrashes:) or set `flushInterval` after calling sharedInstance. like ` self.mixpanel.flushInterval = 20;`
