### ISSUE TITLE
Crash on archivePeople (3.6.2)

### ISSUE THREAD

**Issue by freak4pc** [mixpanel/mixpanel-iphone#912]
**Integration Method:** CocoaPods
**Xcode Version:** 11.7
**Library Version:** 3.6.2
**Platform:** iOS
**Language:** Swift
**Description:** 
Since upgrading to 3.6.2 we've been seeing several crashes with the following error and stack track:

<img width="679" alt="image" src="https://user-images.githubusercontent.com/605076/94582313-c6d94b00-0284-11eb-9e8a-4e6a19c76ff2.png">

Raw crashing thread:

```
Crashed: com.mixpanel.ae06b421c103391071878e0ffd2d9de8.0x108a12aa0.archive
0  libobjc.A.dylib                0x1a7a4f978 objc_msgSend + 24
1  Foundation                     0x194cd2d64 _encodeObject + 212
2  Foundation                     0x194be001c -[NSKeyedArchiver _encodeArrayOfObjects:forKey:] + 380
3  Foundation                     0x194bdd7d4 -[NSArray(NSArray) encodeWithCoder:] + 164
4  Foundation                     0x194cd314c _encodeObject + 1212
5  Foundation                     0x194c256d0 +[NSKeyedArchiver archiveRootObject:toFile:] + 236
6  Mixpanel                       0x107d2be04 -[Mixpanel archiveObject:withFilePath:] + 1327 (Mixpanel.m:1327)
7  Mixpanel                       0x107d2b354 __25-[Mixpanel archivePeople]_block_invoke + 1249 (Mixpanel.m:1249)
8  libdispatch.dylib              0x1935d8ac8 _dispatch_client_callout + 20
9  libdispatch.dylib              0x1935e708c _dispatch_sync_invoke_and_complete_recurse + 68
10 libdispatch.dylib              0x1935e6b3c _dispatch_sync_f_slow + 176
11 Mixpanel                       0x107d2b2cc -[Mixpanel archivePeople] + 1247 (Mixpanel.m:1247)
12 Mixpanel                       0x107d2b034 -[Mixpanel archive] + 1225 (Mixpanel.m:1225)
13 Mixpanel                       0x107d2ae28 __32-[Mixpanel flushWithCompletion:]_block_invoke + 1165 (Mixpanel.m:1165)
14 libdispatch.dylib              0x1935d6fd0 _dispatch_call_block_and_release + 32
15 libdispatch.dylib              0x1935d8ac8 _dispatch_client_callout + 20
16 libdispatch.dylib              0x1935dfc08 _dispatch_lane_serial_drain + 580
17 libdispatch.dylib              0x1935e0734 _dispatch_lane_invoke + 408
18 libdispatch.dylib              0x1935ea528 _dispatch_workloop_worker_thread + 708
19 libsystem_pthread.dylib        0x1daf2c908 _pthread_wqthread + 276
20 libsystem_pthread.dylib        0x1daf3377c start_wqthread + 8
```

**Expected Behavior:** 
No crash

**Comment by freak4pc** [comment]
Any ideas @zihejia ? This affects a non-minimal amount of our users. (Several hundred crashes over a couple of weeks)

**Comment by zihejia** [comment]
hi @freak4pc , I will have a look. which iOS versions do those crashes happen?

**Comment by freak4pc** [comment]
Sorry for the lat reply @zihejia, we're seeing a 80/20 split between iOS 13 and iOS 14. Our minimum target as of today is iOS 11.

**Comment by emisvx** [comment]
Having the same issue using 3.6.3.

**Comment by emisvx** [comment]
Can confirm that the same issue seems to be happening on 3.6.3.

**Comment by freak4pc** [comment]
Any thoughts or revelations in this ? @zihejia

**Comment by zihejia** [comment]
@freak4pc , the issue seems to be different than the one I fixed earlier(https://github.com/mixpanel/mixpanel-iphone/pull/910). This is more like causing by a race condition. @emisvx could you paste your crash log in case there are some differences?

**Comment by freak4pc** [comment]
@zihejia Could be, but we've tried tracking it down and couldn't find anything specific. We also thought it's related to non-exclusive access to reference types so we've changed everything to value types which didn't help (I imagine could be happening inside the SDK). 

Perhaps some locking in these steps inside the SDK could be helpful? Since you do all of these actions in a private queue, we can't (as a consumer) do a lot about any race conditions externally.

**Comment by zihejia** [comment]
hi @freak4pc , thanks for the diagnosing, I will have a look.

**Comment by zihejia** [comment]
hi @freak4pc , we made a fix to the race condition. https://github.com/mixpanel/mixpanel-iphone/releases/tag/v3.6.4. I'm closing this issue now, please feel free to reopen it if the problem still exists.

**Comment by freak4pc** [comment]
![image](https://user-images.githubusercontent.com/605076/102681510-97bedf80-41ca-11eb-825b-5b7ee284d1c1.jpeg)

Thank you ! 🎉🥳
