### ISSUE TITLE
[Question][Bug] Why mixpanel doesn't have option to test pushes with sandbox? `"content-available": 1` is not sent within `aps` object 

### ISSUE THREAD

**Issue by lorenc-tomasz** [mixpanel/mixpanel-iphone#913]
Why mixpanel doesn't have option to test pushes with sandbox? It only send pushes on production so it's almost impossible to test and debug push notifications on debug.

**Comment by lorenc-tomasz** [comment]
Also how to send "content-available": 1 with Mixpanel ?

**Comment by lorenc-tomasz** [comment]
I have noticed the mixpanel doesn't sent `"content-available": 1` within `apn` key when custom key is added.

**Comment by lorenc-tomasz** [comment]
Workaround:

You can send `{"aps":{"content-available":1}}` as Custom JSON but still it should be added to payload if custom content is available

**Comment by zihejia** [comment]
hi @lorenc-tomasz , I'm really sorry for the late response. You can use the preview mode to test your pushes. https://help.mixpanel.com/hc/en-us/articles/360001302503-Send-Push-Notifications-from-Mixpanel#:~:text=You%20can%20preview%20a%20push,to%20receive%20the%20test%20notification. If you have more questions, please feel free to reach out to our [support](https://help.mixpanel.com/hc/en-us/requests/new) to get a timely answer.
