### ISSUE TITLE
Module 'Mixpanel' not found.

### ISSUE THREAD

**Issue by oussamakenzup** [mixpanel/mixpanel-iphone#919]
**Integration Method:** CocoaPods
**Xcode Version:** 12.1
**Library Version:** 3.6.3
**Platform:** iOS 
**Language:** Objective-C
**Description:** Issue when integrating Mixpanel Notification Service, Module Mixpanel not found in NotificationService.h
**Expected Behavior:** For the Notification Service target to work properly following Mixpanel documentation.

I followed the steps in Mixpanel/Mixpanel-iphone [Readme](https://github.com/mixpanel/mixpanel-iphone/blob/master/README.md). Because the website [documentation](https://developer.mixpanel.com/docs/ios-push-notifications) has a typo for Rich Push Notifications  NotificationService.h being repeated should a one .m file.

I followed everystep well, installed the pods but I couldn't run no matter what. Because we use Flipper the usage of use_frameworks! gives us some issues. I have tried use_frameworks! :linkage => :static instead and some workaround to make use_frameworks! works. I tried changing Require only App-Extension-Safe Api to No, adding Mixpanel path to Podfile, adding paths to Notification target build settings all didn't work and I get Module 'Mixpanel' not found in NotificationService.h

I also tried starting everything over as I thought maybe my project got corrupted. I see Mixpanel being installed with pods but I cannot import it from NotificationService.h

Here the end of my podfile:

```
target 'NotificationService' do
  pod 'Mixpanel'
end
```

Here is our NotificationService.h file:

```
@import Mixpanel;

@interface NotificationService : MPNotificationServiceExtension

@end

```

Is there any solution to make this work? Thank you.

**Comment by zihejia** [comment]
It might be similar to https://github.com/mixpanel/mixpanel-iphone/issues/905

However Mixpanel is deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
