### ISSUE TITLE
Remove deprecated unarchiveObjectWithData method

### ISSUE THREAD

**Issue by kyleclegg** [mixpanel/mixpanel-iphone#922]
The method unarchiveObjectWithData is deprecated and deemed unsecure/less secure than unarchive*OfClass. Please remove the following instance of use:

Mixpanel.m

**Comment by kyleclegg** [comment]
Any word on this? Our organization would welcome the improved security.

**Comment by zihejia** [comment]
hi @kyleclegg , we will be working on this soon.

**Comment by jaredmixpanel** [comment]
@kyleclegg this issue is fixed in v3.6.5
