### ISSUE TITLE
Concurrency Issue with TimedEvents

### ISSUE THREAD

**Issue by timbo24** [mixpanel/mixpanel-iphone#926]
**Integration Method:** Carthage
**Xcode Version:** 12.3 
**Library Version:**  3.6.2
**Platform:** iOS
**Language:** Objective-C
**Description:** Race condition when calling `eventElapsedTime`
**Expected Behavior:** Not crashing

We're seeing crashes due to the timedEvents property inside of Mixpanel.m not being thread safe. In all other instances, outside of initialization, accesses to timedEvents is wrapped and dispatched to the serialQueue but not in eventElapsedTime.

Suggested change:

    NSNumber *startTime = self.timedEvents[event];

    ->

    __block NSNumber *startTime;
    
    dispatch_sync(self.serialQueue, ^{
        startTime = self.timedEvents[event];
    });

**Comment by timbo24** [comment]
PR open https://github.com/mixpanel/mixpanel-iphone/pull/927

**Comment by zihejia** [comment]
Thank you so much @timbo24 , your PR has been approved and merged, it will be included in the next release!

**Comment by zihejia** [comment]
We have released it! https://github.com/mixpanel/mixpanel-iphone/releases/tag/v3.7.1 Thanks again! I'm closing this issue for now.

**Comment by timbo24** [comment]
Thank you!
