### ISSUE TITLE
Integration with UrbanAirship crashes on App startup with version 14 of UrbanAirship SDK

### ISSUE THREAD

**Issue by amilici** [mixpanel/mixpanel-iphone#938]
**Integration Method:** Manual with bindings for Xamarin
**Xcode Version:** 12.4 (Using VisualStudio Mac though because Xamarin, version 8.8.7)
**Library Version:** 3.0.0
**Platform:** iOS 
**Language:** C# (Xamarin)
**Description:** App crashes on start up. Mixpanel - Urban Airship integration is calling [MPConnectIntegrations setUrbanAirshipPeopleProp] which tries to access the channelID property of UAPush and results in "unrecognized selector sent to instance". The channelID property of UA push was removed in version 14 of the UrbanAirship iOS SDK.
**Expected Behavior:** The app doesn't crash on start up and Mixpanel correctly integrates with the latest version of the UrbanAirship SDK.

**Comment by zihejia** [comment]
hi @amilici , we will fix it, thanks for bringing it up.
