### ISSUE TITLE
3.9.x build failure on Mac Catalyst due to MPFree deprecation

### ISSUE THREAD

**Issue by arthurofbabylon** [mixpanel/mixpanel-iphone#957]
Mixpanel's 3.9.0 and 3.9.1 versions do not compile on Mac Catalyst targets as "MPFree" is explicitly marked as unavailable.

**Comment by zihejia** [comment]
Hi @arthurofbabylon , the error is the Messaging and Mobile A/B testing features. We are deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our support if you need to continue the conversation. Sorry for the inconvenience. 

Alternatively, if you don't need Messaging and A/B testing(M&E), you can use our 4.0.0.beta version. It's in parity with 3.9.x just without M&E. After Jan 1, 2022, we will release 4.0.0.
