### ISSUE TITLE
Crash in connectToABTestDesigner

### ISSUE THREAD

**Issue by mlostekk** [mixpanel/mixpanel-iphone#959]
**Integration Method:**  Manual
**Xcode Version:**  Version 13.1 (13A1030d)
**Library Version:**  3.9.1
**Platform:** iOS 
**Language:** Swift & Objective-C
**Description:** 
When trying to open the A/B Test designer, the app crashes with the following log.

```
2021-12-02 08:56:34.060399+0100 Skoove Debug[7287:771336] +[MPSwizzler swizzleSelector:onClass:withBlock:named:async:]: unrecognized selector sent to class 0x100daaf68
2021-12-02 08:56:34.072759+0100 Skoove Debug[7287:771336] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[MPSwizzler swizzleSelector:onClass:withBlock:named:async:]: unrecognized selector sent to class 0x100daaf68'
*** First throw call stack:
(0x181db204c 0x19a426f54 0x181e8ef44 0x181d47474 0x181d465b0 0x102845a58 0x100d52340 0x100d34b1c 0x100d73580 0x106fcc6d4 0x106fce3b4 0x106fde898 0x181d6acd4 0x181d24eac 0x181d383b8 0x19d6c838c 0x1846d86a8 0x1844577f4 0x100790efc 0x100e79a24)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[MPSwizzler swizzleSelector:onClass:withBlock:named:async:]: unrecognized selector sent to class 0x100daaf68'
terminating with uncaught exception of type NSException
```

Here is the stacktrace:
![Bildschirmfoto 2021-12-02 um 08 57 10](https://user-images.githubusercontent.com/10534316/144380878-1e74e867-f48d-4baf-a156-7f5481dcb1c1.png)

The interesting thing is that its crashing in the FBSDKSwizzler. We are using a react native app and have recently upgraded the FBSDK to the latest version. That might be relevant

**Expected Behavior:** 
The A/B Test designer should open without a crash and allow for configuring an AB Test

**Comment by zihejia** [comment]
Hi @mlostekk ,  on Jan 1, 2022, we’ll remove the Messages & Experiments feature from Mixpanel([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our support if you need to continue the conversation. Sorry for the inconvenience.
