### ISSUE TITLE
Pod update failing

### ISSUE THREAD

**Issue by gonxas** [mixpanel/mixpanel-iphone#968]
**Integration Method:** CocoaPods 
**Xcode Version: **  Version 13.1 (13A1030d)
**Library Version: ** 4.0.0
**Platform:** iOS 
**Language:** Objective-C
**Description:**
Since today (I'm not sure when it started, it's been a while since I last updated all pods, when trying to do pod update on my project I'm getting `[!] CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/6/6/9/Mixpanel/4.0.0/Mixpanel.podspec.json Response: Timeout was reached`
Also, if I try to ping this url from the terminal, I get *unknown host* (Tried from different terminals, on both OSX and linux, on different parts of the world with the same result).
On the contrary, if I try to open it on a browser it opens as expected.

**Expected Behavior:** 
When doing Pod update, pod should be successfully installed.

**Comment by zihejia** [comment]
hi @gonxas , this usually means something wrong with your internet settings, please try restarting your mac and resetting your internet, that often fixes the problem. Since this is not related to Mixpanel. I'm closing this one now.

**Comment by gonxas** [comment]
hi @zihejia.

I've restarted the mac, tested with different wifis locally, and tested it on a computer on a complete different country, got the same results on all tests. Can't this be somehow linked to the version update from 2 days ago?

**Comment by zihejia** [comment]
hi @gonxas , that's weird, what will happen if you change the Podfile to point to some older versions?

**Comment by gonxas** [comment]
Hi @zihejia . I tried with both 3.7 and 3.9.2 and got the same result.
I also did a ```ping https://cdn.jsdelivr.net``` and I get ```ping: cannot resolve https://cdn.jsdelivr.net: Unknown host```, so I guess the problem may come from there. Thanks for the help.
