### ISSUE TITLE
What is an alternative for addPushDeviceToken in the latest sdk version 4.0.0

### ISSUE THREAD

**Issue by tc-sgupta** [mixpanel/mixpanel-iphone#969]
**Integration Method:** Swift Package Manager
**Xcode Version:** 13.2.1
**Library Version:** 4.0.0
**Platform:** iOS
**Language:** Swift / Objective-C
**Description:** `addPushDeviceToken` seems to be removed. What is an alternative for this method. 
**Expected Behavior:** Alternative for ``addPushDeviceToken`` method

**Comment by zihejia** [comment]
hi @tc-sgupta , Mixpanel is no longer supporting the Messaging feature. This is a planned deprecation since early last year. Please see this for more detail: https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/. Sorry for the inconvenience.

**Comment by tc-sgupta** [comment]
@zihejia What happens if we use release 3.9.2 and keep calling that method. Will `addPushDeviceToken` method call be ignored by mixpanel.

**Comment by zihejia** [comment]
hi @tc-sgupta , it should not cause any crash and it will be ignored by mixpanel.
