### ISSUE TITLE
Could not Build Objective-C module 'Mixpanel'

### ISSUE THREAD

**Issue by acfriedman** [mixpanel/mixpanel-iphone#978]
**Integration Method:** SPM
**Xcode Version:** Xcode 13.2.1
**Library Version:** v4.1.1
**Platform:** iOS
**Language:** Swift & Objective-C
**Description:** Compilation error: 
<img width="1774" alt="Screen Shot 2022-01-28 at 3 20 47 PM" src="https://user-images.githubusercontent.com/7318614/151616868-4163e079-940c-4038-9230-7874c445e275.png">
**Expected Behavior:** Successful compilation 

Looks like adding `#import "MixpanelGroup.h"` to `Mixpanel.h` resolves the issue

**Comment by zihejia** [comment]
Hi @acfriedman , this has been fixed in v4.1.2. Thanks for bringing it up. I'm closing it now, please feel free to reopen if the problem still exists.
