### ISSUE TITLE
Crash on [MPVariantAction executeSelector:withArgs:onObjects:].

### ISSUE THREAD

**Issue by YanxiFeng** [mixpanel/mixpanel-iphone#995]
**Integration Method:** CocoaPods 
**Xcode Version:** 13.4.1
**Library Version:** 3.7.1
**Platform:** iOS
**Language:** Objective-C
**Description:** 
**Expected Behavior:** 
com.mixpanel.983e524b40bcb07ee429fc0308ebe8d2.0x104a14710.archive
SIGABRT ABORT 0x00000001a5d48d88
0
libsystem_kernel.dylib
__pthread_kill + 8
3
libsystem_c.dylib
err + 286
4
ChopeDashboard
MPVariant.m - 
+[MPVariantAction executeSelector:withArgs:onObjects:].cold.1 + 1869044
5
ChopeDashboard
Mixpanel.m - 
-[Mixpanel unarchive] + 1393
6
ChopeDashboard
Mixpanel.m - 
-[Mixpanel archiveObject:withFilePath:] + 1375
7
ChopeDashboard
Mixpanel.m - 
__25-[Mixpanel archiveGroups]_block_invoke + 1286
8
libdispatch.dylib
_dispatch_client_callout + 16
9
libdispatch.dylib
_dispatch_lane_barrier_sync_invoke_and_complete + 56
10
ChopeDashboard
Mixpanel.m - 
-[Mixpanel archiveGroups] + 1283
11
ChopeDashboard
Mixpanel.m - 
-[Mixpanel archive] + 1246
12
ChopeDashboard
Mixpanel.m - 
__32-[Mixpanel flushWithCompletion:]_block_invoke + 1185
13
libdispatch.dylib
_dispatch_call_block_and_release + 24
19
libsystem_pthread.dylib
start_wqthread + 8

**Comment by jaredmixpanel** [comment]
@YanxiFeng You're on a very old version of the SDK. This code has been removed. Please update to the latest version.
